Jackett/Jackett

src/Jackett/Indexers/BlueTigers.cs

> BlueTigers has a new infrastructure now.
SSL is disabled (redirected to non-ssl domain)
Provider crash if you keep using SSL (with 2 options for SSL activated too)
JigSaw

Fixed Disabled SSL on tracker side with BlueTigers Provider

---

src/Jackett/Content/custom.js
src/Jackett/Content/index.html
src/Jackett/Content/login.html
src/Jackett/Controllers/AdminController.cs
src/Jackett/Controllers/PotatoController.cs
src/Jackett/Controllers/TorznabController.cs
src/Jackett/Models/Config/ServerConfig.cs
src/Jackett/Services/ServerService.cs
src/Jackett/Startup.cs
src/Jackett/Utils/WebApiRootRedirectMiddleware.cs

This fixes support for putting Jackett behind a reverse proxy. 
Tested fully with my setup of Jackett living behind a HTTPS proxy via "my-example-site.com/jackett/".
Redirects and download links work correctly with newly added "Base Path Override" configuration option. For my example site, it would be "jackett".

Better reverse proxy support

---

src/Jackett/Jackett.csproj
src/Jackett/Services/ProtectionService.cs
src/Jackett/Utils/StringCipher.cs

The current protection service that encrypts and decrypts the indexers is bound to the current machine. If you use Jackett in a Docker container, the data is corrupted every time you create a new container even if the data is persisted. To alleviate this, the option to use an environment variable "JACKETT_KEY" that can be any string as an optional encryption method is introduced. If no environent variable is specified the functionality remains the same.

Updated encryption service for better use with Docker

---

src/Jackett/Utils/TorznabCapsUtil.cs

Comparing number to string was failing when imdb id had a leading zero

Fix IMDB Matching

---

src/Jackett/Indexers/PhxBit.cs

> Wrong base for downloads -> Users were unable to download torrents.
Now fixed. Able to download with Passkey without logged in.
JigSaw

Download FIX for PhxBit

---

src/Jackett/Indexers/TorrentLeech.cs

A few days ago TL started returning some dates with CR / LF. 
This just cleans string.

Deal with carriage return in date string

---

src/CurlSharp/SSLFix.cs
src/Jackett/CurlHelper.cs
src/Jackett/Utils/Clients/HttpWebClient.cs
src/Jackett/Utils/Clients/UnixSafeCurlWebClient.cs

> SSL Fix is enabled by default, recoded ciphers list
> Jackett HTTP Web Client is now using TLS by default (1.2, 1.1, 1)
Fixed ISS. #311 and so many others.
JigSaw

SSL Fix by default, Now use TLS (1.2, 1.1, 1) by default

---

README.md

The "issues page" link in the Contributing section was pointing to the old repo! I just updated.

Update "issues page" link in README

---

src/Jackett/Indexers/BitHdtv.cs

Addressing this issue https://github.com/Jackett/Jackett/issues/359
> Bit-HDTV announced on their forum they changed things, in particular the format of the url to download the .torrent files which prevents Jackett to retrieve them.
> 
> Old format : /download.php?/123456/dl.torrent
> New format : /download.php?id=123456

Modified to use new download URL format

---

src/Jackett/Jackett.csproj

`FrenchADN.cs` was referenced as `FrenchAdn.cs` and thus breaking the builds on case sensitive filesystems (Mono builds).
I've changed the file names to reflect the actual names.

Fix builds on case-sensitive filesystems

---

README.md

For #317 
The wording is a little ambiguous since there is more than one "`.tar.gz`"  file on the releases page.

Update README.md for Linux/OSX installation

---

src/Jackett/Indexers/MoreThanTV.cs

I wanted to fix searching for seasons but I accidentally ended up rewriting almost the entire indexer.
The issue was that MoreThanTV has "torrent groups" named "Season 1/2/3" etc.. and the torznab response literally said "<title>Season 1</title>", of course sonarr won't accept that. It can now grab all torrent group items and rewrites the title so sonarr can parse it.
Another issue was that the previous indexer searched for "Arrow S01" while you can only find the groups if you search for "Arrow Season 1".
Let me know if changes are required or something is not clear.

Rewrote MoreThanTV indexer

---

src/Jackett/Indexers/PirateTheNet.cs
src/Jackett/Indexers/TorrentSyndikat.cs

Mono doesn't seem to like Windows Timezone names

German Timezone

---

src/Jackett/Content/custom.js

It usually is expected that the main input field in a model is focused.

Manual search: Focus text field when opened

---

src/Jackett/Content/custom.js
src/Jackett/Content/index.html
src/Jackett/Jackett.csproj
src/Jackett/Models/ReleaseInfo.cs
src/Jackett/Models/ResultPage.cs

files: Number of files
grabs: Number of times item downloaded
downloadvolumefactor: factor for the download volume, in most cases it should be set to 1, if a torrent is set to freeleech set it to 0, if only 50% is counted set it to 0.5
uploadvolumefactor: factor for the upload volume, in most cases it should be set to 1, if a torrent is set to neutral leech (upload is not counted) set it to 0, if it's set to double upload set it to 2

Add missing torznab attributes files, grabs, downloadvolumefactor, uploadvolumefactor

---

src/Jackett/Indexers/IPTorrents.cs

The url URL to POST login credentials has recently been updated to `take_login.php`.

Fix IPTorrents POST url

---

src/Jackett/Jackett.csproj

This might fix the System.IO.DirectoryNotFoundException: Directory '.../Definitions' not found issues.

 	Change definition to Content

---

src/Jackett/Indexers/BB.cs

Changes the comic book id to use category id 7 to match Bb site.

Comicbooks id is now 7 at Bb.

---

src/Jackett/Indexers/AnimeTorrents.cs

AnimeTorrents: Skip releases which newbie user's can't download yet

---

src/Jackett/Definitions/torrentsectorcrew.yml

Torrent Sector Crew: Fix rows selector for people with "Empfohlene Torrents in der Liste anzeigen" disabled.

---

src/Jackett/Indexers/MoreThanTV.cs

The logic to check if the query is for TV is not working correctly because the query can contain sub categories.
This will fix it.

Fix TV search for MoreThanTV

---

src/Jackett/Indexers/BakaBT.cs

BakaBT alternative releases were being ignored because they have different class names.
This will include them in search queries.

Support alternative versions of releases on BakaBT

---

src/Jackett/Controllers/DownloadController.cs

Ensure that the filename of a torrent file sent to browser client doesn't contain invalid characters.
This modification resolves #1084 .

Ensure proper filename of generated torrent

---

src/Jackett/Indexers/BroadcastTheNet.cs

Fixes Jackett/Jackett#1096
In short, BTN's old API url is no longer working. The new url is https://api.broadcasthe.net

Update the BTN API url

---

src/Jackett/Jackett.csproj

file systems on linux are case sensitive

fix build on linux

---

src/Jackett/Definitions/limetorrents.yml

Remove season tag without episode (search doesn't support it)

Limetorrents: remove season tag without episode from keywords

---

src/Jackett/Definitions/icetorrent.yml

Correct the HTML parsing so rows are returned.  They probably changed the HTML of the page recently.

Fix parsing for IceTorrent

---

src/Jackett/Definitions/tntvillage.yml

The size reported from the plugin will be defined by category matching.
This is needed for applications like Sonarr/Couchpotato/Headphone to work.

TNTVillage plugin: Change reported size based on category

---

src/Jackett/Indexers/T411.cs

T411 weirdly changed their internal ID mapping to episode number.
Eg. Jackett would return S03E05 instead of S03E04.
I also cleaned the code.

Fixed T411 TV Series episode category offset

---

src/Jackett/Indexers/BitHdtv.cs

Width on the table element changed again (back to 750.)  This should stop us
from caring about the width and just find the right table.  Basically looks for
the table after the paging bar.

BitHDTV - Stop trying to keep up with changing width

---

src/Jackett.Test/TestIIndexerManagerServiceHelper.cs
src/Jackett/Indexers/AggregateIndexer.cs
src/Jackett/Jackett.csproj
src/Jackett/Services/IndexerManagerService.cs
src/Jackett/Services/ServerService.cs

This adds just a basic first implementation of a special
torznab feed that will make all configured trackers available
with all the supported query params.
- This should close Jackett/Jackett#1247
- This also contributes to Jackett/Jackett#921

Adding an aggregate torznab feed for all configured trackers

---

src/Jackett/Indexers/T411.cs

Updated T411 domain references to the new domain used.

Updated T411 domain references to the new domain used.

---

src/Jackett/Indexers/AggregateIndexer.cs
src/Jackett/Indexers/BaseIndexer.cs
src/Jackett/Services/IndexerManagerService.cs

This patch improves the general stability of the aggregate.
- Result is generated even if some trackers failed to answer
or some other issue were encountered
- Fixes Jackett/Jackett#1316

Fixing a bunch of issues with the newly added AggregateIndexer

---

src/Jackett/Indexers/AnimeBytes.cs
src/Jackett/Models/IndexerConfig/Bespoke/ConfigurationDataAnimeBytes.cs

Sonarr gets confused if you add a S01 on anime seasons. Since animbytes includes the season name in the title, the episode number is enough for a full match.

Fixed sonarr not finding episode numbers with animebytes

---

README.md

- Adds detailed instructions on syncing ca certs and avoiding SIP issues
outlined in https://github.com/Jackett/Jackett/issues/1179

Update README with more detailed OS X instructions

---

src/Jackett/Definitions/anidex.yml

@kaso17 FYI I found out today that anidex does not always have a magnet link corresponding to returned search results. As a result it is more reliable to use the torrent link instead of the magnet link that my definition currently uses. To do this one just needs to change the download selector from `td:nth-child(6) > a` to `td:nth-child(5) > a`.

Switch anidex to use to torrent link vs magnet link

---

src/Jackett/Definitions/tokyotosho.yml

- Fixed definition failing test, https://www.tokyotosho.info/ redirects to https://www.tokyotosho.info/index.php
- Changed language to UTF-8.
- Added "public" type

Fix tokyotosho failing test and add type

---

src/Jackett/Definitions/horriblesubs.yml

This will fix my personal use case in sonarr.
Instead of 
`Natsume Yuujinchou Roku -​ 05 [480p]`
I need 
`[Horriblesubs] Natsume Yuujinchou Roku -​ 05 [480p]`
I like to keep my subtitles in sonarr consistent, so I made a tag filter in sonarr that requires horriblesubs to be in the torrent title for some series. This is also how the torrent title looks like when horriblesubs publishes to other trackers.

[Horriblesubs] prepend horriblesubs tag to title for better filtering in sonarr

---

src/Jackett/Definitions/kickasstorrent.yml

Hi! This is referring to issue #1379 and should fix it (at least it does for me)! What it does is add username and passkey (input by the user) and uses them to log in through a simple POST request. I haven't tested it much (and I'm not sure the `test` part does anything) but I've been able to successfully search, effectively circumventing the CAPTCHAs (yay!).
Should KAT be changed to "semi-private" or not? Because technically it's a public tracker, but for Jackett's purposes, it seems it can't be used without an account.
Cheers and good night,
Joe

Add KAT passkey login

---

README.md
src/Jackett/Definitions/deildu.yml

I had a few problems with category. Because of poor categorizing on the tracker I had to disable Jackett from reading the categories. All HD content on the tracker is in one category so category mapping had issues with using the same id.
It still searches with categories though and everything else works.

add tracker Deildu

---

src/Jackett/Definitions/nyaasi.yml

The previous parsing logic was failing due to the `UTC` in the supplied format which wasn't present in the string.

Nyaa.si: Fix date field so it correctly parses as UTC time.

---

src/Jackett/Definitions/tokyotosho.yml

It was previously parsing the time as local time.

TokyoTosho: Fix date field so it correctly parses as UTC time

---

src/Jackett/Definitions/nyaa-pantsu.yml

* Fix size field to handle "Unknown" as a value.
* Remove upload/download factor fields as pantsu is a public tracker.

NyaaPantsu: Parse date, seeder, leecher, & grab values for torrents.

---

src/Jackett/Definitions/horriblesubs.yml

Update indexer definition to support dates in the format of `mm/dd` as well as `mm/dd/yy` since [`/lib/search.php`](http://horriblesubs.info/lib/search.php?value=naruto) returns `mm/dd/yy` while [`/latest/php`](http://horriblesubs.info/lib/latest.php) only returns `mm/dd`.
Fixes #1402.

HorribleSubs: Fix date parsing for RSS feed.

---

src/Jackett/Definitions/anirena.yml

* Doesn't parse categories or dates.
* There may be a better approach as their RSS feed supports searching.
* Ex: https://www.anirena.com/rss.php?s=naruto
* Fixes #1391.

First pass at an AniRena definition.

---

src/Jackett/Definitions/nyaa-pantsu.yml

Looking at the html of nyaa-pantsu search page, the date field is using a class of .date-short not .date.
this corrects the above.

Fix #1383 nyaa-pantsu date selector incorrect

---

src/Jackett/Definitions/nyaa-pantsu.yml

- Selectors needed to be updated.
- Adds support for advanced search on nyaa-pantsu. If you leave the category id empty it will behave like it did before.
If you want to find a specific id, go to https://nyaa.pantsu.cat/ and create the filter you want to use and press search. In the url, `c` is the category id.

Fixed nyaa-pantsu indexer and added category filter.

---

src/Jackett/Definitions/tokyotosho.yml

Adds support for advanced search on tokyotosho. If you leave both settings empty it will behave like it did before.
If you want to find a specific id, go to https://www.tokyotosho.info/ and create the filter you want to use and press search. In the url, `type` is the type id.

Add advanced search to TokyoTosho indexer.

---

src/Jackett/Definitions/anidex.yml

Adds support for advanced search on Anidex. If you leave both settings empty it will behave like it did before.
If you want to find a category or language id, go to https://anidex.info/?id=1&adv=1&lang_id=1&q= and create the filter you want to use and press search. In the url, `id` is the category id and `lang_id` is the language id.

Add advanced search to Anidex indexer

---

src/Jackett/Definitions/thegeeks.yml

- The Geeks uses SSL
Currently, if a user tries to add thegeeks.click, he will face a redirection error.

[Fix] Redirection errors

---

src/Jackett/Indexers/RevolutionTT.cs

Resolves issue #1259 with searching broken regarding provider RevolutionTT. Null pointer check added to resolve unexpected content in the table added by the provider on a recent update,

Resolved null pointer causing searches to fail on RevolutionTT

---

src/Jackett/Definitions/torrent9.yml

The site has changed domain name.

Torrent9: Domain change .top -> .cc

---

README.md
src/Jackett/Definitions/yggtorrent.yml

Hi,
I've seen @ploufs PR on the same subject.
Think this version is more functional :
- Using /alpha/ instead of /dev/
- Working login system. As Ygg is now private
- Working date translation/compatibility
- Disabled TV-show search (I'll reactivate it soon, when YggTorrent will introduce filters in search options)
Thank you

Replace T411 (closed) with YggTorrent (new replacement)

---

src/Jackett/Definitions/kickasstorrent.yml

I had issues with KAT requesting a relogin and I thought it was time I made a real login test (the one I wrote was a scam) and added error handling. Succeeds with correct credentials, gracefully fails otherwise.
On a sidenote : testing KAT as a provider currently fails because searching with an empty string returns no results (hence Jackett sees it as a failure). This should be addressed but as long as the user is logged in, searching works.
EDIT: As you can see, the sidenote has been addressed by me!

Update KAT definition for real login test, error handling and indexer testing logic

---

src/Jackett/Indexers/yts.cs
src/Jackett/Jackett.csproj

Hi!
I installed Radarr and noticed there was no yts.ag! Since that's the only place I want movies from, I added it. Seems to be working great for me (search and RSS feed) - let me know if there is anything else I should do with this.
Note: I had to hack around a few things because the YTS api didn't seem to cooperate (comments left in the code).

Added yts.ag as an indexer.

---

src/Jackett/Indexers/TorrentBytes.cs

To get a larger number of results, users should increase the number on the website, similar to how it's implemented for TorrentLeech. Since TorrentBytes can be slow at times, making one large request will not be that much slower from one small request, but will nearly half the time taken compared to two smaller requests.

Use only one request on Torrentbytes to search

---

src/Jackett/Indexers/BB.cs

When querying for a whole season, in addition to "S##", also query for "Season #", as per the bB torrent naming rules. 
However, sonarr still doesn't download those, so then rewrite "Season #" back to "S##" for TV shows.

Improve season query logic for bB

---

src/Jackett/Definitions/yggtorrent.yml

Hello,
Here is an update of YGG indexer, including :
1. Making three request for each query (on 3 first pages) :
This is a little trick for having more results, as YGG not accept a "max results" parameter yet. So now it returns up to :
- 39 results in search (3x more than actual version)
- 69 results in blank-search/test (3x more than actual version)
2. Added video categories
3. Fixed parsing time error (cf. https://github.com/Jackett/Jackett/issues/1633)
4. Fixed parsing size error (cf. https://github.com/Jackett/Jackett/issues/1633)
4. Added comment info parsing
5. Added connection test to fix broken torrent files. cf. https://github.com/Jackett/Jackett/issues/1590 https://github.com/Jackett/Jackett/pull/1536)
6. More precise selectors
Thank you

YGG config update

---

README.md

@kaso17 Following your question on #1705. I’m really no expert but this works and is built-in AFAIK. `curl` doesn’t care if the file already exists and the options provided make it independent from where the user runs the commands.
I don’t really remember how I did it when I installed Jackett, but I think I downloaded the file manually, then used `cert-sync`.
Cheers!

Fix instructions for certificates on macOS

---

src/Jackett/Definitions/t411v2.yml

I'm 99% sure that since they've resurrected they're fully public (no login needed, no ratio, etc.) and since even Jackett isn't asking for login info, it should be reflected here.

Make T411v2 public

---

src/Jackett/Indexers/SceneAccess.cs

SceneAccess is now "free-leech for life", and has been for about a month or so. Can't say I'm familiar with Jackett's codebase, but I looked around a bit and this seems to be the way releases are usually flagged as freeleech (or in this case all releases).
Snippets from recent SceneAccess announcements:
>2) Site is now permanently free-leech. Keep earning those coins as they will become very useful in the future. 
>The site is FREELEECH, this means ALL SECTIONS, ALL RELEASES and NO ratio requirements, the only thing you have to remember is to seed the files!

SceneAccess is now permanently free-leech

---

src/Jackett.Console/install_service_macos.sh

Fixes #1784
I'm not sure if and how I should enhance the README. "Run the script from anywhere in the Terminal" or "Run using /path/to/install_service_macos.sh in Terminal"?

Fixing macOS script

---

src/Jackett/Content/custom.js
src/Jackett/Content/index.html

For as long as I can remember, Jackett's coloured lock glyphs next to a tracker's name never displayed correctly on macOS. On Chrome (which I usually use), they show up as red, orange or green coloured empty square boxes and on Safari as the Lock or Lock with Key emoji (with no colour applied). Weirdly enough, the Chrome squares actually are the same emoji but they don't render (I'm guessing because it’s stubbornly trying to apply Helvetica).
Since this works flawlessly on Windows, it should also work just as well on macOS. That’s why I’ve changed them to use the standard Bootstrap lock glyph. These locks do look a little more "fat" though and don't add the key when the tracker is of type `private` but it doesn't rely on OS/Browser-dependent handling of emojis and provides a more uniform …

[UI] Changing the locks

---

src/Jackett/Definitions/manicomioshare.yml

Sonarr does not understand the name of the series because of the word "Ep.". Changing to "E", he starts to consider the episode number correctly.

Fixed "Unknown series" on sonarr for tracker manicomioshare

---

README.md
src/Jackett/Definitions/1337x.yml
src/Jackett/Definitions/zooqle.yml

Q: From a *yml definition*, is there a way to fetch a *magnet URI* from the *details* page, in a similar way to how *.torrent links* are fetched via the *download section* and *download field in the search section* pairing?
Q: I currently call the *dateparse filter* three times in order to process the three differently formatted dates that are available on the *search page* rows. Is there a way to conditionally select which dataparse to use?

add 1337x public tracker. Closes #1384

---

src/Jackett.Updater/Program.cs

rapidetracker was removed with 8f869995e9acd631c685fa77ccc4ec552a46b922 but cleanup was not included.

RapideTracker: Cleanup after removal.  Closes #1870

---

src/Jackett/Indexers/TorrentLeech.cs

TorrentLeech renamed the existing 4k category and added a new "Real 4K UltraHD HDR" category. This PR adds the new category (but leaves the old one too).

Add the new 4K category for TorrentLeech

---

README.md
src/Jackett/Definitions/elitehd.yml

HDClub is back as EliteHD according to TF article https://torrentfreak.com/hdclub-russias-leading-hd-only-torrent-site-returns-as-elitehd-170930/     
This definition is untested, as it requires an invitation or an existing login carried over from HDClub.     
The assumption is that only the domain has changed.

add EliteHD

---

src/Jackett/Indexers/Rarbg.cs

* Add 4k Movie and TV categories for RARBG
Currently it does not look like torrentapi.org indexes the 4k movie categories but I've added them anyway in case they get added in the future.
Also, torrentapi.org returns "Movies/TV-UHD-episodes" for RARBG's 4k TV category. This may be due to RARBG's top100 page.
* Update Rarbg.cs

RARBG: Adding 4k categories

---

src/Jackett/Definitions/hyperay.yml

hyperay switched domains in feb '17
source: opentrackers.org

hyperay: update link and add description

---

src/Jackett/Definitions/btdb.yml

the btdb site does not use categories and supplies magnets for all sorts of content.
So the btdb definition now always returns category `100001 Other` for all search results.
Added info in settings to provide instructions on setting up btdb on Sonarr and Radarr.
Tested on Jackett Dashboard, Sonarr and Radarr.

btdb: fix #1900 add support for Sonarr and Radarr

---

src/Jackett/Definitions/cpabien.yml

this avoids redirection by .cc domain
add .cc as legacylink
also add original .co as legacylink

cpabien: switch to .org domain fix #1933

---

src/Jackett/Services/IndexerManagerService.cs

Added the aggregate indexer to be retrievable from IndexerManagerServe.GetWebIndexer()

Fix for download links in aggregate search

---

src/Jackett/Definitions/secretcinema.yml

Enables searching for Secret Cinema (query and imdbid)
Jackett does not seem to support if clauses within a range template so I had to add the nzbcat parameter to make the category ids unique without impacting the search filter.

Fix Secret Cinama searching

---

src/Jackett/Indexers/Hounddawgs.cs

There was a bug where Jackett would report the number of grabs as seeders which breaks functionality that relies on those number. This PR fixes that.

Fix Hounddawgs grabs/seeders/peers

---

src/Jackett/Indexers/BeyondHD.cs

BeyondHD recently added a new "Internal" category for 4K remuxes: `FraMeSToR 4K REMUX`

BeyondHD: Add new `FraMeSToR 4K REMUX` category

---

README.md

Update the documentation to reflect some of the last weeks changes to the supported frameworks. 
Encouraging use of the latest version of Mono shouldn't cause us much grief as the mono team have made fewer breaking changes in the last couple of years and continue to make bug fixes that should help Jackett run smoothly on newer distrubutions.

Update requirements for Jackett

---

.gitignore
Installer.iss
appveyor.yml
build.cake
build.ps1
src/Jackett.sln

Switch to Cake build system instead command line script
Advantages
- Popular C# build system https://cakebuild.net/
- Can now replicate the build process locally (Previously, it could take repeated builds on AppVeyor to get it right and RDP to debug failures)
- More control over the process
- Implemented 755 file permissions for the Mono Binaries (Fixes https://github.com/Jackett/Jackett/issues/1336)

Switch to Cake Build System

---

src/Jackett.Common/Definitions/b2s-share.yml
src/Jackett.Common/Definitions/speed-share.yml
src/Jackett.Common/Indexers/BJShare.cs
src/Jackett.Test/Jackett.Test.csproj

BJ-Share:
- If an anime is being searched, remove the episode number from search, eg: from "Dragon Ball Super 118" to "Dragon Ball Super", and filter later (tracker does not allow direct episode search).
BJ-Share / Speed Share / B2S Share:
- If the row result is an anime, change the output from eg: "Dragon Ball Super S10E118" to "Dragon Ball Super E118", reason: Season numbering to animes is all wrong on these trackers, so sonarr does not accept that result. (tv shows output is not altered)

Anime search fix to BJ-Share, B2S-Share and Speed-Share

---

README.md

http://infinity-t.org/ is the official "recommendation" as an replacement.

Hounddawgs removed

---

src/Jackett.Common/Indexers/GimmePeers.cs

modified the ProcessPage Method to select the last table with the browsetable class attribute so that if the Top 20 table is visible it will be ignored and the master list is the only one that will display.  Works with Top 20 on and off.

Update GimmePeers.cs for Top 20

---

src/Jackett.Common/Indexers/PolishTracker.cs

CategoryMapping update to reflect latest changes on polishtracker site.
Fix to allow search over multiple categories (search url cat[]=6&cat[]=9 instead of cat[]=6,9)

PolishTracker update

---

src/Jackett.Common/Indexers/TorrentBytes.cs

Since TorrentBytes announced that they had updated the categories, I decided to update the mappings here.
Missing ones were added, the ones that do not exist anymore were removed and some mapped types were corrected to better reflect the contents of the category.
Sorted in alphabetical order by the true category name. This should make any future changes easy to see as long as that convention is kept.

Update TorrentBytes category mappings

---

src/Jackett.Common/Indexers/Hebits.cs

Hebrew search results were not coming when using hebits tracker.
Encoding was not used there. Now added encoding.

Fixed Hebits hebrew encoding

---

src/Jackett.Common/Definitions/torrentz2.yml

Two optional filters in settings : 
- Safe search (exclude adult content)
- Verified results (only return verified torrents)
:)

Added Torrentz2 filters safe-search and verified

---

src/Jackett.Common/Definitions/jpopsuki.yml

I noticed that a lot of torrents were missing when comparing the search results for Jpopsuki to their actual website.
It seemed that Jackett didn't support 'grouped torrents' (torrents with multiple releases)
So, I disable grouping and fixed the indexes for columns.

Jpopsuki add support for torrents with red background

---

src/Jackett.Common/Indexers/TorrentDay.cs

The top level categories have hyphen in them. -6 is Music, but 6 is XXX/Movies. It looks like -6 is not a searchable category.

Cat 6 is actually XXX/Movies

---

README.md
src/Jackett.Common/Definitions/torrentkim.yml

This site is pretty awful, most of the search list differs from one another and the best list is hidden, using the search bar on top only returns google results that are un-usable.
Still, it should be working pretty great for a first release.
Please note:
1: The site does not provide a correctly formatted list for "newest" releases and when you make an empty search, you are redirected to the google search page. As such, when doing the "test" from Jackett's webUI, we will be searching for 미운우리새끼 because I know for a fact that results are available.
2: For the seeds / peers, I'm not 100% sure what the first number is and what the second is since I wasn't able to find a torrent with enough activity to confirm. I went with my guts feeling. Might need to be updated later on.
3: My ONLY goal …

Adding TorrentKim first version

---

src/Jackett.Common/Indexers/TorrentSyndikat.cs

Fix for Issue #2788 : [torrentsyndikat] Exception (torrentsyndikat): String was not recognized as a valid TimeSpan.: Parse error (Test)

Fix for Issue #2788

---

src/Jackett.Common/Definitions/hachede.yml

Change TV Shows search format for Spanish style and add [spanish] for detected Spanish language in Sonarr/Radarr

Hachede: fix TV Shows search and spanish language

---

src/Jackett.Common/Indexers/TorrentLeech.cs
src/Jackett.Common/Jackett.Common.csproj

Following the unveiling of V5 at TorrentLeech.org, the indexer runs into two different problems.  First, the introduction of CloudFlare, and second a rewrite of the UI.
CloudFlareUtilities 1.1.0 seems to dislike the flavor of CloudFlare used by TL so I bumped it to version 1.2.0 to fix the: "Clearance failed after 4 attempt(s)" as referenced in #2882.
The SearchUrl that was used in V4 no longer returns the torrent list in the results as it is hidden in a JavaScript call to a JSON which leads to #2864.  So, instead, we now grab the JSON directly and parse the results into a fully functional release array.
This pull request is to address the several issues raised for this tracker since the change.

TorrentLeech - Fix for V5 Interface

---

src/Jackett.Common/Indexers/BeyondHD.cs

This adds the following categories:
- 102: Movie / 4K Disk
- 103: Movie / 4K Remux
-  38: Movie / WEB-DL
- 106: Internal / BHDStudio 1080p
- 105: Internal / BHDStudio 720p
- 104: TV Show / 4K
-  99: TV Show / Sports
- 100: TV Show / Sports / WEB-DL
Additionally 94: `Movie / 4K` was renamed to `Movie / 4K Other` to
match the updated category name on the tracker.

BeyondHD: Add new / missing categories

---

src/Jackett.Common/Definitions/zamundanet.yml

Currently Jackett grabs the human readable titles which are in the following format: 
``` {Movie.Title} / {Movie.TitleTranslated} ({Movie.Year})```
That's great for reading, but unfortunately it doesn't provide enough information to radarr and sonarr for automatic detection of movie quality. 
The pull request aims to solve this by extracting the title from the direct download link which usually contains the needed information.
**Important:** 
I'm not .net developer and I couldn't set up usable environment under linux to test this. Please merge with caution as it may be broken.

Zamunda.net: Improve torrent titles

---

src/Jackett.Common/Services/Interfaces/IServerService.cs
src/Jackett/Services/ServerService.cs

.NET core uses HttpRequest instead of HttpRequestMessage

DotNet Core preparation

---

src/Jackett.Common/Definitions/xbytes2.yml

xbytesv2 adds two years in title, when a show has season episodes released in two different years. For example, supergirl season 3, has episodes in 2017 and 2018. In this case xbytesv2 name the episode like this: "Supergirl (2017 18/S03/E13/AMZ WEB DL 1080p/AC3 5 1 /DUAL/SUB) Grupo V2" 
This new filter, removes both years from title.
Please don't remove this replace (S01 E01 -> S01E01):
- name: re_replace
args: ["S(\\d{1,2}) E(\\d{1,2})", "S$1E$2"]

Added new replace

---

src/Jackett.Common/Indexers/AnimeBytes.cs

Allow length of 48 for passkey for future changes in AnimeBytes codebase.

Update AnimeBytes required passkey length

---

README.md
src/Jackett.Common/Indexers/Newpct.cs

Support for "newpct" group of web pages (www.tvsinpagar.com, descargas2020.com, torrentrapid.com, etc.)
Movies are only returned in "rss" mode.
For TV, both "rss" and episode search are supported.

Add spanish tracker Newpct

---

src/Jackett.Common/Definitions/isohunt2.yml

Sometimes when parsing, the size of the rel was not enough to have Gb instead Mb or Kb to Mb or whatever
So the size in row is for example 1.015.22 Mb (less than 1024)
So in this case the parser return error
I searched a way to replace this, I found a solution, hope that works in a log way

Quik fix to size row

---

src/Jackett.Common/Content/index.html

btn-danger looks too scary for a log there is no need for this to be a danger red, use green for positivity.

changed log button from btn-danger to btn-success

---

src/Jackett.Common/Indexers/BJShare.cs

BJ-Share changed its domain from bj-share.me to bj-share.info

Update BJ-Share to new domain name

---

src/Jackett.Common/Indexers/NCore.cs

Sonarr is search for a tilte if the result title is different it reject it.
So it is not enough that Jackett give the result it must give with the same language.
Workaround create a new title from the original one and from the title.
It also make some fine tunning:
if title not contains the language we add it from category

Additional fix for #1450

---

src/Jackett.Common/Definitions/metaltracker.yml

use artist instead of keyword if artist is supplied to make it somewhat compatible with lidarr(by default supplies artist and album with empty keyword)

Use Artist instead of keyword

---

src/Jackett.Server/Controllers/ResultsController.cs
src/Jackett/Controllers/ResultsController.cs

I'm running following with "linuxserver/jackett" docker image:
```
Jackett 0.8.1209.0
Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
OS version: Unix 4.4.0.119 (64bit OS) (64bit process)
mono version: 5.12.0.226 (tarball Thu May  3 09:48:32 UTC 2018)
```
and making request to Potato feed with only apikey and imdb ID with example of "tt0859635" but in the result the ID is as "tt859635":
```
{
"results": [
{
"release_name": "Super....",
"torrent_id": "magnet:?...",
"details_url": "https://torr...",
"download_url": "magnet:?...",
"imdb_id": "tt859635",
"freeleech": true,
"type": "movie",
...
```
I assume the change that could solve this is to wrap the value with `ParseUtil.GetFullImdbID` function call as `release.Imdb` might be `long`.
Tested the change by building the code and …

Zeros are removed from Imdb ID after "tt" in Potato API result

---

src/Jackett.Common/Definitions/uhdbits.yml

Fix error 'Invalid non-ASCII or control character in header: 0x0009' on download (Tab character, upstream bug in kestrel)

Fix UHDBits definition

---

src/Jackett.Common/Indexers/Nordicbits.cs

This is a fix for #3750 ...
Currently only the old 'V2' themes are supported and therefore not many people can use this tracker, as the default is a V3 unless changed by the person.
With this new update, I have added support for the v3 theme but continue to keep the old support for v2 by looking after the .css file loaded and return the proper _fDom in FindTorrentRows...
I have also added a extended error msg, when torrents can't be found that it could be because of an unsupported theme.

Update Nordicbits - Add support for all themes

---

src/Jackett.Common/Indexers/HorribleSubs.cs

* This is needed for things like configuring tag restrictions in Sonarr

HorribleSubs Indexer - Make sure release title contains "[HorribleSubs]"

---

src/Jackett.Common/Definitions/yggtorrent.yml

Jackett allows to replace MULTI with FRENCH, which might be useful to grab dubbed releases only.
For people, such as me, who prefers sub over dub, this would allow us to blacklist the word "FRENCH", commonly used for dubbed content.
It has been tested on my personal setup and works as expected.

VOSTFR option added to "Replace MULTI" on YggTorrent

---

README.md
src/Jackett.Common/Indexers/Orpheus.cs

apollo is now https://orpheus.network/
this is not tested, but I imagine the categories are the same

move from apollo to orpheus

---

src/Jackett.Common/Definitions/eztv.yml
src/Jackett.Common/Utils/LoggingSetup.cs
src/Jackett.Server/Helper.cs
src/Jackett.Server/Program.cs

Microsoft logs are now correctly log by NLog.
By default, these are deactivated for service log.
You can set tracing enabled option or Enhanced logging to true for log again.

manage Microsoft logs by NLog

---

src/Jackett.Common/Indexers/NCore.cs

Correction for #4199
After the last page a new link was appeared for premium action.
Now it will not parsed as page link

Correction for #4199

---

src/Jackett.Common/Definitions/audiobookbay.yml

True without quotes is boolean in yaml, should be string

fix audiobookbay categorymappings id type

---

src/Jackett.Common/Indexers/HorribleSubs.cs

- Now returns batches in results along with individual episodes
- Now returns all episodes for a show instead of just the first page
- No longer makes a bunch of unnecessary API calls (faster results)
- Now populates the comments/details link if available
- Fixes #4425 
- Fixes #4426

Fix Up the HorribleSubs Indexer

---

src/Jackett.Common/Indexers/EliteTracker.cs

fix parse error in EliteTracker indexer (again).
EliteTracker has revert a modification on his tooltip.
Normally this fix will work in all cases.

fix parse error in EliteTracker indexer

---

src/Jackett.Common/Definitions/hdforever.yml

Gazelle API from HD-Forever doesn't push languages, releasers, and download factors. Here is a remplacement.
src/Jackett.Common/Indexers/HDForever.cs should be deleted.

Incomplete HD-Forever API remplacement.

---

src/Jackett.Common/Definitions/hdspain.yml

In HD-Spain tracker, Sxx format for complete season doesn't work, they are titled Tx (Temporada is the meaning of Season in Spanish, so T is used instead of S).
In this commit, I added an additional regexp that changes S with T, and deletes 0 before S.

Added regexp for searching complete seasons in PyMedusa

---

README.md
src/Jackett.Common/Indexers/Torrentscsv.cs

This is a basic indexer for the torrents.csv project (https://gitlab.com/dessalines/torrents.csv).  It's prepopulated with a internet based torrents.csv instance (https://torrentscsv-ml) but you can always change the Site Link to your own self-hosted version.
This is my first C# project and first indexer/definition for Jackett.  It was adapted mostly from the yts.cs indexer.  Many thanks to the author of that file.

Indexer for Torrents.csv initial commit

---

src/Jackett.Common/Definitions/hd4free.yml

without the whitespaces days is replaced with dmonths because the turkish word for month is ay

Fixed published date on hd4free when language is set to english

---

README.md

Just a typo fix in the README.md file.

Fixed typo, loose vs lose.

---

src/Jackett.Common/Indexers/Torrentscsv.cs

Fixed the category mapping so that sonarr, radarr, nzbhydra2, etc return results when using a category
Update list of trackers that get added to the infohash

Fixed categories, updated tracker list for Torrents.csv

---

src/Jackett.Common/Indexers/BJShare.cs

While researching why this doesn't work: https://github.com/Jackett/Jackett/issues/4414#issuecomment-471376387. I noticed that it would just run `TodayUrl` query and generate a lot of noise (exceptions which are logged because the `<font color="red">` element doesn't exist) on some `<tr>`s that are not video content. 
Instead there should not be an attempt to create a release from that.
I did not shuffle the code around, but it could probably be tested just after qQuality is created. Happy to change that.
If it should just return the content, so perhaps we should just safeguard it from null and let it fall into default case?

BJShare: Only set quality if available

---

src/Jackett.Common/Models/TorznabQuery.cs

Those seems to be the only two public properties missing from TorznabQuery#Clone.
This closes #4414.

Add missing properties to TorznabQuery#Clone

---

src/Jackett.Common/Indexers/Pretome.cs

Use link 'title' attribute. The text gets truncated by the website automatically if its longer than a certain length causing matching problems.

Change release name to use 'title' attribute

---

src/Jackett.Common/Definitions/bithumen.yml

On site the date is 02.18 08:31  (Without year):
Result with previous yml:
```
<title>Smurfs.The.Lost.Village.2017.2160p.UHD.BluRay.HDR.REMUX.TrueHD.Atmos.7.1.HEVC.HUN-Legacy</title>
<guid>https://bithumen.be/details.php?id=569959</guid>
<jackettindexer id="bithumen2">BitHUmen2</jackettindexer>
<comments>https://bithumen.be/details.php?id=569959</comments>
<pubDate>Mon, 18 Feb 2008 00:00:00 +0100</pubDate>
```
Result with corrected one:
```
<title>Smurfs.The.Lost.Village.2017.2160p.UHD.BluRay.HDR.REMUX.TrueHD.Atmos.7.1.HEVC.HUN-Legacy</title>
<guid>https://bithumen.be/details.php?id=569959</guid>
<jackettindexer id="bithumen">BitHUmen</jackettindexer>
<comments>https://bithumen.be/details.php?id=569959</comments>
<pubDate>Mon, 18 Feb 2019 08:31:00 +0100</pubDate>
```

PublishDate to torrents from current year was handled wrongly.

---

src/Jackett.Common/Definitions/cpabien.yml
src/Jackett.Common/Definitions/cpasbienclone.yml
src/Jackett.Common/Definitions/gktorrent.yml
src/Jackett.Common/Definitions/torrent9.yml
src/Jackett.Common/Definitions/torrent9clone.yml

The MULTI was before the year so it was not supported by Radarr,Couchpotato etc..
Now it is handle as the FRENCH and TRUEFRENCH language

cpasbien, cpasbienclone, gktorrent, torrent9, torrent9clone: fix title with MULTI language.

---

src/Jackett.Common/Definitions/yggtorrent.yml

Brooklyn.Nine-Nine.S06E17.SUBFRENCH.720p.HDTV.x264-AMB3R is recognized as french content instead of english content, even if "Replace VOSTFR with ENGLISH" is enabled

Manage SUBFRENCH as VOSTFR to avoid "English is wanted, but found French"

---

README.md

Without the `/api` on the end it works but with it doesn't so maybe a typo?

I think this is a typo?

---

src/Jackett.Common/Indexers/TorrentSyndikat.cs

TS removes too short words automatically, so don't try to handle this client-side.
Adding the wildcard causes problems with not indexed words (stopwords) such as "how" (as in "how to sell drugs online fast"). Searching for terms like this leads to empty results:
"+How* +to* +sell* +drugs*" -> no results
"+How +to +sell +drugs" -> all results
I think at one time, adding the wildcards manually may have been necessary, but this does not seem to be the case with the current TS version.

TorrentSyndikat: Do not filter query, remove wildcard operator.

---

src/Jackett.Common/Indexers/MejorTorrent.cs

The web now uses https instead http. Without this, the indexer doesn't work.

http to https

---

src/Jackett.Common/Definitions/torrenting.yml

I apologize for my inexperience, but I was able to resolve an issue, so wanted to share. I noticed that the downloadvolumefactor was not detecting freeleech items properly. From looking at the html through chrome, the span should contain Freeleech just like the existing code was written, but that wasn't working. I enabled enhanced logging, and when looking through the dump from enhanced logging, noticed it should be FreeLeech. I changed the code locally and it resolves the issue.

[Torrenting] Resolve Issue with Download Volume Factor

---

src/Jackett.Common/Indexers/MejorTorrent.cs

Page character encoding changed from iso-8859-1 to UTF-8.

Change to UTF-8

---

src/Jackett.Common/Definitions/greekteam.yml

The tracker has updated it's html layout and removed a column from the browse list. I have adapted and tested the definition to the new table format.

Fixed definition of greekteam tracker

---

src/Jackett.Common/Indexers/Newpct.cs

Fix for #5774
Currently https://descargas2020.org/ultimas-descargas/ doesnt work, returning null value.
When this happens, it searches on the clon sites that works and have the same lastest releases links, for example http://www.tvsinpagar.com/ultimas-descargas/pg01 and http://torrentlocura.com/ultimas-descargas/pg01

Fix for array can't be null for NewPct

---

src/Jackett.Common/Definitions/hdcity.yml

HDCity queries are sensitive to character accents:
Radarr currently doesn't find the movie called "Alita: Ángel De Combate" because all releases on HDCity are called "Alita Angel De Combate". 
Interestingly testing with Jackett I found out that searching for "Alita ngel De Combate" "Alita ng l De C mbate" or any version of replacing characters with spaces still returns all the results. 
That being the case, my suggestion is simply to replace any non-alphanumeric character with spaces to avoid missing results. This still allows to retrieve titles with accents like "El Sangriento Imperio Romano Calígula" as the query for "El Sangriento Imperio Romano Cal gula" works exactly the same way

Fix accents on title for HDCity

---

README.md
src/Jackett.Common/Definitions/booktracker.yml
src/Jackett.Common/Definitions/torrentwal.yml

With TorrentKim going down, I wanted to utilize Jackett with a Korean public tracker so I added a definition for TorrentWal. The format of the website is nearly identical to TorrentKim and the yml is essentially the same as https://github.com/Jackett/Jackett/pull/2620 with some modifications to make sure the data makes sense.
There is no support for seeder/leecher ratios from what I can gather on the website (every torrent seems to have 0/0 ratio and the search URL doesn't even provide those numbers). But everything else should be working! A blank search will pull up "유희열" as the search term. There's no justification for that; I used the previous user's search conditional and I happened to be watching a show called "Yoo Huiyeol's Sketchbook" ("유희열의 스케치북").
I'm not sure how the previous …

Added TorrentWal Support and updated tracker list.

---

src/Jackett.Common/Jackett.Common.csproj
src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs

Fixes #4982 
Test it, it works for me, it should be working.
The only problem is with user-agent, it's now fixed with the BrowserUtil.ChromeUserAgent value.
A website that is protected by cloudflare, once bypassed with some user-agent, it cannot be changed (it must be one during the same session).
If you need some different user-agent with some websites (static during the same session), you have to separate the EmulateBrowser property from the request, it shoud be linked with the HttpWebClient classes.

Cloudflare Bypass: Replaced CloudFlareUtilities with CloudflareSolverRe

---

src/Jackett.Server/Controllers/BlackholeController.cs

Subclasses of BaseIndexers.cs override the default behaviour when downloading to the blackhole directory.
When the default behaviour is to check if the uri is already a magnet link, some indexers, such as Rarbg.cs, directly call |RequestStringWithCookies| to download the content of a torrent link, but with a magnet link instead resulting in http/https errors.
This pull request puts the default behaviour of the BaseIndexers directly in the Blackhole controller, allowing to download a magnet link into a .magnet file in the blackhole folder when the magnet link is directly available.

Fix magnet link in the blackhole controller

---

src/Jackett.Common/Definitions/channelx.yml

- it should be noted that UNIT3D has a config option for direct download or download check page. 
```
download:
selector: a[href*="/download/"]
attribute: href
```
VS
```
download:
selector: a[href*="/download_check/"]
attribute: href
```
Im not sure if this can be checked in Jackett as to what is being used. If possible all UNIT3D based trackers yml's should be updated.

(Update) channelx.yml

---

src/Jackett.Common/Definitions/elitetorrent-biz.yml

Some links in result are like these ones:
```html
<a class="nombre" href="https://www.elitetorrent.one/peliculas/dumbo-1080p-castellano/" title="Dumbo">Dumbo</a>
<a class="nombre" href="https://www.elitetorrent.one/peliculas/dumbo-hdrip-vose/" title="Dumbo">Dumbo</a>
```
If many results are found, text in a is the same for all of them, but link is different and include info about quality or language, so it would be nice to have them in title returned by jackett.

Get title from href to get format info

---

src/Jackett.Common/Utils/ParseUtil.cs

Currently receive `Incorrect parameter: invalid imdbid format` error when searching for content which uses an 8 digit IMDB id.

Support 8 digit IMDB ID's

---

src/Jackett.Common/Indexers/BJShare.cs

On BJ-Share when a empty query is used the year wasn't retrieved on the title, instead it comes as description, thins kind of behavior didn't allow the RSS to work on Radarr, since no year was informed.

Fix BJ-Share indexer issue when retrieving rss with empty query

---

src/Jackett.Common/Indexers/TorrentDay.cs

Headphones sends audio/album searches to category 3010 (and 3050) but 3010 isn't populated for this tracker.
If having two Torznab categories mapping to the same ID is illegal then maybe we can probably just remove line 92?

add AudioMP3 / 3010 for headphones search support

---

README.md
appveyor.yml
build.cake
src/Jackett.Common/Jackett.Common.csproj
src/Jackett.Server/Helper.cs
src/Jackett.Server/Jackett.Server.csproj
src/Jackett.Server/Services/FilePermissionService.cs
src/Jackett.Server/Startup.cs
src/Jackett.Test/Jackett.Test.csproj
src/Jackett.Test/WebUtilityHelpersTests.cs
src/Jackett.Tray/Jackett.Tray.csproj
src/Jackett.Updater/Jackett.Updater.csproj

Updated Jackett so that it runs on .NET Core 3.0 now
.NET Core 3.0 brings the following benefits https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/
One of the benefits is the ability to create single file executables. I haven't enabled this yet, but its only a one line change to turn it on (would likely also require some changes to the updater).
This means that builds for LinuxAMDx64, LinuxARM32, LinuxARM64 and macOS will now run on .NET Core 3.0 instead of 2.2. Windows and Mono remain on full framework. Once .NET Core 3.1 is released (November) I'll look to moving Windows over to .NET Core as well
Tested on
-Windows 10 x64
-Debian running Jackett with Mono
-Debian running Jackett standalone (.NET Core)

Update to .NET Core 3.0

---

src/Jackett.Common/Indexers/BJShare.cs

It fixes the search of BJ-Share to match radarr and sonarr standards. Fix issue #4365 too.

Fixed search to match with Sonarr and Radarr standards.

---

src/Jackett.Common/Indexers/AnimeBytes.cs

Updates to account for the updates to synonyms as described in #6181 , fixes #6186
Removes Artists. It was being declared, but never used. It feels a bit more complicated to implement, you would probably have to have a dictionary containing Artist objects, whose class would also need to be defined. 
For now this just makes sure we have the same functionality as before.

Update synonyms AnimeBytes

---

src/Jackett.Common/Definitions/magico.yml

Previous setting was replacing all non latin characters. Since this is a greek tracker this is a major pain

Use \w and \d to respect non latin characters

---

src/Jackett.Common/Indexers/Xthor.cs

I'm sorry for this disgusting fix, i don't know the language C#.
There is surely a cleaner way to fix that.
The old code only looks just for category 5070, but not for a specific anime category.
Latest release:
With the fix:

[Xthor] Fix for anime search for xthor

---

build.cake
install_service_systemd.sh
jackett_launcher.sh
src/Jackett.Common/Services/UpdateService.cs

Improvements over #6249
* Moved the launcher script into jacket directory. Can survive updates and can be automatically updated in future releases.
* Fix file permissions in mono variant
NOTE: The mono variant is not affected by issue https://github.com/Jackett/Jackett/issues/5208#issuecomment-547565515
NOTE2: I tested carefully the LinuxCoreARM64 and the LinuxMono variants.

updater: improvements in systemd jackett_launcher

---

src/Jackett.Common/Definitions/hdcity.yml

All releases on this tracker are both spanish and english unless "vose" is specified. So english tag should also be appended to title

Append english to the language too

---

src/Jackett.Common/Definitions/1337x.yml

Very similar to commit e874255.
Fixes "System.ArgumentException: '', hexadecimal value 0x0F, is an invalid character."
(example: a search for "Legend of Korra S02")

1337x - Remove \u000f from title

---

jackett_launcher.sh

+ Execute script with system default bourne shell. On Debian this is "dash" by default, which has a much lower memory foot print compared to bash. As well systems without bash won't fail. "${BASH_SOURCE[0]}" cannot be used then but "readlink -f" is another reliable method to get a full file path, using another coreutils binary like "dirname".
+ Execute Jackett with "--NoRestart" option. This has currently not effect, but it assures that the updater never attempts to restart the Jackett process, which is done by the systemd unit already. This avoids possible restart collisions if anything about the updater behaviour changes, e.g. to fix the originating issue.
+ Remove the "Jackett update complete" print. This is simply wrong if Jackett was stopped ordinarily and the updater itself logs to …

jackett_launcher.sh fine tuning

---

src/Jackett.Common/Definitions/1337x.yml
src/Jackett.Common/Definitions/extratorrent-ag.yml
src/Jackett.Common/Definitions/isohunt2.yml
src/Jackett.Common/Definitions/katcrs.yml
src/Jackett.Common/Definitions/kickasstorrent-kathow.yml

Magnet links with "&#039;" in the &dn= parameter fail when being sent to qBittorrent. Encoding as %27 allows the download to start. (Example: Schindler's List - Tigole/QxR)

Encode "&#039;" for magnet URL

---

src/Jackett.Common/Definitions/hdcity.yml

HDCity uses for complete seasons the definition T+[season], when clients like sonnar search for complete seasons append to search S[season]. With this modification allow to replace S for T in search seasons.

Added support to search Complete Seasons

---

src/Jackett.Common/Definitions/hdcity.yml

Missing spaces in fields args that broke the HDCity template.

Bug in fields args broke HDCity template

---

src/Jackett.Common/Indexers/TorrentBytes.cs

The title of a torrent on TorrentBytes is either taken from the text within the `<a>` itself, or from `<a title>` attribute if the text within the `<a>` has been truncated due to the length of the title. Worth noting is that `<a title>` is only present when the title's been truncated, hence why both methods are used. Anyway; so far so good.
Problem arises however on torrents with free leech, more specifically on those who's title hasn't been truncated and thus taken from the text within the `<a>` tag. When a torrent has free leech on TorrentBytes they add `[F L]` to the end of it, so you get something like `My.Awesome.Release.720p.WEBRip.x264-JACKETT [F L]`. The current `.ToString()` method of getting the title already does a great job at removing the `[F L]` part automatically for us …

[TorrentBytes] Remove trailing whitespace

---

src/Jackett.Common/Indexers/720pier.cs

Fix for #6368 
The login script needed more fields that needed to be downloaded from a current login form. This downloads the login page and extracts the needed hidden fields. It now checks the remember me box on login as well.
While testing I found that `PerfomQuery` also failed because the code for `release.Link` and `release.PublishDate` weren't selecting the right fields. I fixed those to be more generic so they should be more resistant to future changes.
I made a couple readability changes as well. Made the names more consistent, var everywhere instead of only a couple places, moved some things around to utilize language features, sort & remove usings.
I was curious why we're overriding `configData` when all it's doing is pointing back to base. Doesn't make sense but I left it in …

[720pier] Fix login and search parsing for indexer 720pier

---

src/Jackett.Common/Definitions/speedtorrentreloaded.yml

Speedtorrend Reloaded changed their template and removed the class ".tableinborder" from the top level table resulting in jackett not being able to fetch any data.
This is the definition fix for this change.

speedtorrent reloaded: removed .tableinborder from row selector

---

README.md

https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md
https://github.com/Jackett/Jackett/issues/6769

.NET Core 3 requires macOS 10.13 or greater

---

src/Jackett.Common/Services/UpdateService.cs
src/Jackett.Updater/Program.cs

@ngosang per your comment in #6677 I've separated the pull requests. This one just fixes the bug in both update scripts, and will close #6671 
I'll be sending 2 additional pull requests, one to cleanup code style for readability, and one to convert spaces to tabs in just these two files.

Fix file location bug in paths with spaces during updates

---

src/Jackett.Common/Definitions/1337x.yml
src/Jackett.Common/Definitions/extratorrent-ag.yml
src/Jackett.Common/Definitions/isohunt2.yml
src/Jackett.Common/Definitions/kickasstorrent-kathow.yml
src/Jackett.Server/Controllers/DownloadController.cs

@garfield69 tested with:
* http://127.0.0.1:9117/dl/elitetorrent-biz/?jackett_apikey=ygm5k29tomyy11df26gio7iouhqx9k4&path=Q2ZESjhBYnJEQUIxeGdOQ21admtZdjAzUVB3YW5MdUJxMEdweEJMdl8yd3A2NmNBWVRnYnNMU1RkSk1qSjhsYUQtcUJRZGhTMHpRYmpJWVJwbUttTm84cGtyZW56Vkhzcmo1VWVVbERBUmFFem5mUWdOOW8xUnRILWlBdkp5dVo0bFV1MGlqaFlON0JmYnNjUGxwb2VlUVJ5Q2JpQ2pVRDVZWVhIR3p1cEZmOXpXc1JycS1MdDczeEd3NUd1NHZvTHcyR0p3&file=ispansi+espanoles+dvdrip
* http://127.0.0.1:9117/dl/1337x/?jackett_apikey=ygm5k29tomyy11df26gio7iouhqx9k4&path=Q2ZESjhBYnJEQUIxeGdOQ21admtZdjAzUVB5Vm1YQmlDYkVFRVpKcEJsN2I4Vjd6YVFJdkFGRGF4Slg5Yk8tVjFCU2t1WHNZQ1AyYmpsNFBlQndqeG5vQk02Um1BNXJhajk3VklOX2M5SFBudGo0bGJDYlVYUDZ5Nnl2TEdfRHM0dlNQdXF4TlBoc3VDejAxY2RWdFgwUi1NWHkwaFhIMHY2WXBRQmF2OGxEb0FkWklxVXBOXzRQVTBDLXhRenl2V1VCaHo1MXNGWnBxbWZ5MF9wbTF1LW05Z3JoWHVra …

core: fix magnet link encoding. resolves #5372 #4761

---

src/Jackett.Server/Controllers/BlackholeController.cs
src/Jackett.Server/Controllers/DownloadController.cs

@garfield69 this fix a security issue. An attacker with a fake jackett_apikey can known if a tracker is configured or not. I fixed it by checking the authorization first.
Tested in download / blackhole links

core: security fix, authorization first in download / blackhole links

---

README.md
src/Jackett.Common/Definitions/bibliotik.yml

Adds support for the private tracker Bibliotik. I'm happy to maintain this going forwards as it seems no other contributors have access and invites have been closed for years.
This is my first new tracker addition, so please feel free to critique.

Add support for bibliotik #1443

---

src/Jackett.Common/Utils/DateTimeUtil.cs

Previous version works well with dates like "Yesterday 15:30" or "Today 15:30"
Now it can handle "Monday 15:30" as well (means last Monday at 15:30 h)

core: improve fuzzytime date parser to handle week days. resolves #6832

---

src/Jackett.Common/Definitions/soundpark.yml

I'm getting this errors when downloading:
```
Error downloading soundpark https://sound-park.world/album/torrent-XXX
CardigannIndexer (soundpark): Download selector a[href^="/album/download-torrent/"] didn't match
```

Fix sounpark download for non members accounts

---

src/Jackett.Common/Jackett.Common.csproj
src/Jackett.Common/Services/IndexerManagerService.cs
src/Jackett.Server/Controllers/DownloadController.cs
src/Jackett.Server/Jackett.Server.csproj

4 packages updated -> Jackett is now using the latest version of all packages except for AutoMapper -> Will have a go at that another day -> There is a few changes needed to make it work
-Minor code changes made to support newer version of YamlDotNet and BencodeNET
-Logic update for AssemblyName as I've been experiencing restore 'weirdness'  https://stackoverflow.com/questions/208084/how-to-use-a-different-assembly-name-for-different-configurations

Package update

---

build.cake

Latest version of msys2 includes tar, so no need to manually install it
Should make build fractionally faster and remove below errors

No need to install Tar now

---

src/Jackett.Common/Definitions/estrenosdtl.yml

Search `fast and shaw` => Links to an old domain and can be fixed with replacement.
The old domain `https://www.estrenosdtl1.net/` is blocked in Spain where most users come from.

estrenosdtl: fix old download links. resolves #6924

---

src/Jackett.Common/Definitions/torrentland.yml

Fixed the problem identifing results always as English now they will be identified as Spanish or English depending of title..

Improved search adding language tags

---

src/Jackett.Common/Definitions/nyaasi.yml

Now will show [PuyaSubs!] and [Spanish] in the previous version [PuyaSubs!] was deleted and only show [Spanish] at the end of the file, now will be less confusing because you will be able to see original name but with [Spanish] after [PuyaSubs!]

Improved [PuyaSubs!] tag

---

src/Jackett.Common/Indexers/LostFilm.cs

- Improves indexer setup error logging for #6801. Though when this error happen there's no other solution but to setup indexer from scratch
- Improves empty response handling for #6945. Reason of getting empty responses is unknown but might be related to host being blocked in specific countries (RU).
- Improved search & filter algorithm for #2631. Specifically it fixes "The Magicians (2018)" search query giving no results

Improve LostFilm.tv indexer

---

src/Jackett.Tray/Main.cs

By default .NET Core sets UseShellExecute to false due to being cross platform

Make Tray compatible with .NET Core

---

src/Jackett.Common/Indexers/HDBitsApi.cs

This PR adds an improved HDBits indexer that uses their JSON API rather than scraping the HTML, which means it should be more robust and less likely to break due to potential layout changes in the future. It also adds some more functionality that currently isn't available in the existing indexer, like IMDb support and more release information.
I've added this indexer under a new name rather than replacing the existing one to avoid breaking people's setups when (if) this indexer gets added to Jackett. Not sure if there's a process in place how breaking changes usually are handled, but I'd love for this indexer to replace the existing one at some point. The breaking change is the use of passkey instead of password in the configuration. The API _does_ support using password instead of …

Add improved HDBits indexer

---

src/Jackett.Common/Definitions/torrentz2.yml

`searchP` is not existing anymore, and the default (without any suffix) is `peers`

torrentz2: Fix sorting of torrents

---

src/Jackett.Test/Jackett.Test.csproj
src/Jackett.Test/WebUtilityHelpersTests.cs

This allows unit tests to run on Linux and macOS

Allow unit tests to run in non-Windows environments

---

src/Jackett.Common/Indexers/AnimeBytes.cs

Fixes what was discussed in the comments on #7027 
AKA fixes, the "Include Raws" setting for AnimeBytes having no effect.

AB fix RAW tag setting

---

src/Jackett.Common/Indexers/CardigannIndexer.cs

If you have the link `https://yggtorrent.ws/` in `yggtorrent` tracker.
1. In the current implementation the configuration dialog doesn't show and you have to edit the .json / .yaml manually.
2. With this PR the error will be logged and the dialog will be open (without captcha). I didn't test but I think you will be able to change the link. @garfield69 could you test?
The logged exception will be like this:
```
02-05 19:08:06 Error Exception in GetConfigurationForSetup (yggtorrent): System.Net.Http.HttpRequestException: Name or service not known
---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at …
```

core: show configuration dialog when GetConfigurationForSetup fails

---

src/Jackett.Server/Controllers/IndexerApiController.cs

Add support for a "configured" parameter in the API 2.0. Only return configured indexers if true.
Would be nice to have, no breaking changes.

API 2.0 - indexers "configured" parameter

---

src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
src/Jackett.Common/Utils/Clients/WebClient.cs
src/Jackett.Common/Utils/StringUtil.cs

This change should fix ALL POST REQUESTS in Jackett with encoding != UTF8. That mean searches #4346, login #3061 ...

core: fix form encoding. resolves #4346 #3061

---

src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs

Orpheus returns a different message warning the user of a lack of freeleech tokens and thus breaks when using the option without having freeleech tokens. Checking for the message makes it correctly fall back to downloading without a token.

orpheus: fix free leech token option breaking the tracker

---

src/Jackett.Common/Definitions/theresurrection.yml

The Resurrection needs you to do a "downloadcheck" before giving back the download url to the .torrent-file. This has now been fixed as I've overlooke it last night.

[Fix Tracker] The Resurrection downloading .torrent

---

src/Jackett.Common/Definitions/immortuos.yml

Immortuos has done some server changes and currently the old url lead to the login page of the forum.
Include currently working login page in addition to the old one in case they revert the changes.
Adding account and testing connection in Jackett worked on my end.
Fixes #7177

[Fix Tracker] Change login url for Immortuos

---

src/Jackett.Common/Definitions/thefallingangels.yml

Link for downloading .torrent-file when enabled HTTPS differs from normal download link.

TFA: Fix if enabled download via HTTPS

---

src/Jackett.Common/Definitions/thefallingangels.yml

Some titles have included some special tags in the beginning.
This removes one or two of those.

TFA: Remove leading [Release Group] / [Req] combination from title

---

src/Jackett.Common/Definitions/theresurrection.yml

The Resurrection changed the name of the parameter for the categories from "categories" to just "category". Old search still worked, but to prevent errors in the future this was adopted.
Changed Typo in category 18 to "Staffeln HD".

[The Resurrection]: Changed parameter name for categories

---

src/Jackett.Common/Indexers/TorrentLeech.cs

TorrentLeech supports searching by IMDb ID, which the current Jackett indexer does not yet implement.

TorrentLeech: Add support for IMDb search

---

src/Jackett.Common/Content/custom.css
src/Jackett.Common/Content/custom.js
src/Jackett.Common/Content/index.html
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Indexers/HDBitsApi.cs
src/Jackett.Common/Models/DTO/Config.cs
src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationHDBitsApi.cs
src/Jackett.Common/Models/IndexerConfig/ConfigurationData.cs
src/Jackett.Common/Models/IndexerDefinition.cs

This PR adds some more configuration to the HDBits API so one easily can select which codecs and mediums one's interested in. I thought about adding them as additional categories at first, but they're more like filters - so it wasn't really feasible to do in a usable and logical way.
In order to achieve this and make it configurable in a nicer way, I also took the liberty of adding support for checkboxes to the indexer configuration. The final result looks like this:

Add codec and medium filters to HDBits API

---

src/Jackett.Service/Jackett.Service.csproj
src/Jackett.Tray/Jackett.Tray.csproj

We no longer need to support NET461 for Tray and Windows service since these are for Windows users only

Windows service and Tray: NET Core only

---

src/Jackett.Server/Startup.cs

Starting in Chrome 80, following [an update](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00) to the `SameSite` draft standard, Chrome rejects cookies with the `SameSite=None` attribute that do not also have the `Secure` attribute.
https://www.chromestatus.com/feature/5633521622188032
Currently the Jackett cookie is configured with `SameSite` set to `None` and the `SecurePolicy` set to the default `SameAsRequest`. This means that HTTP requests will redirect indefinitely because the cookie set by the login page will be rejected.
To fix this, the Jackett cookie should be configured with `SameSite` set the to default `Lax`.
ASP.NET Core was modified to change the behavior of `SameSiteMode.None`. Previously the behavior matched the older 2016 draft and resulted in the …

Change cookie SameSite from None to Lax

---

src/Jackett.Common/Definitions/theresurrection.yml

Change login method to post.
Revamped error parsing.
Add test selector.
Somehow accounts were listed online more than once with last version. After testing with this new version this didn't happen any longer.

[The Resurrection] Fix multiple logins

---

src/Jackett.Common/Utils/LoggingSetup.cs

There is no standard size, but a value between 1 MB and 10 MB is more reasonable than having a lot of small files. 2 MB file can be send through email or uploaded to GitHub.

core: increase log size to 2 MB

---

src/Jackett.Common/Utils/Extensions.cs

Fixes #7333
`obj == null || obj.IsEmpty()` causes VS to suggest merging sequential checks. The result of the merge is `obj?.IsEmpty() == true` which returns false when null. This is the source of the bug.
I prefer the null coalescing operator `??` for this scenario out of the alternatives. This removes the suggestion and keeps the intended result. Two other code options that would do the same thing but IMO make the code less readable are flipping the operands `obj?.IsEmpty() == true || obj == null` or using the `Nullable<bool>` function that returns a specific value when null `(obj?.IsEmpty()).GetValueOrDefault(true)`
This same information has been committed to the code in a comment above the function.

Fix IsEmptyOrNull to return true when IsNull

---

src/Jackett.Common/Indexers/FunFile.cs

@garfield69 In this case if you add the `?` symbol to make the field optional, you are breaking the ratios for all torrents. We have to check case by case.

FunFile: fix error caused by #7369 Resolves #7451

---

src/DateTimeRoutines/DateTimeRoutines.csproj
src/Jackett.Common/Jackett.Common.csproj
src/Jackett.IntegrationTests/Jackett.IntegrationTests.csproj
src/Jackett.Server/Jackett.Server.csproj
src/Jackett.Service/Jackett.Service.csproj
src/Jackett.Test/Jackett.Test.csproj
src/Jackett.Tray/Jackett.Tray.csproj
src/Jackett.Updater/Jackett.Updater.csproj

No build warnings were found after removing suppression, but in Jackett.Common the specific warning suppressed was concerning NuGet packages not getting the right dependency versions, which is not something we should be ignoring, IMO.

Remove warning suppression

---

src/Jackett.Common/Indexers/Fuzer.cs

Fixes #7502
The issue was `.ToString()` in that case returned the Class Name instead of the text contents of the Node. So the date was only split into a single string in an array. Length-2 makes it [-1] which threw the error.

Fix parse error in Fuzer

---

src/Jackett.Common/Definitions/torrent-explosiv.yml

Remove the [Group tag] at the beginning of the scraped title.
Improve automatic use of Jackett with title matching.

Torrent-Explosiv: Remove [Group Tag] in title

---

src/Jackett.Common/Definitions/xtremezone.yml

`movie-search` mode wasn't saying it supported imdb, so it was skipping the searches and returning 0 results from an "unsupported" search.
fixes #7520
can check off XtremeZone in #4859

XtremeZone: add imdb search support

---

README.md

The original sort was case sensitive. This should be case insensitive so humans can read it easier.

Sort trackers alphabetically

---

src/Jackett.Common/Jackett.Common.csproj

I fixed the CloudflareSolverRe library in https://github.com/RyuzakiH/CloudflareSolverRe/pull/18 but the maintainer seems unavailable.  Meanwhile I published the patched version in Nuget.org until he release a new version.

core: fix CloudflareSolverRe library. Resolves #7397

---

install_service_systemd.sh
install_service_systemd_mono.sh
jackett_launcher.sh

I tested all the scripts carefully.
* Detects if the user is unknown
* Detects if the systemd unit path doesn't exist (fedora/centos users will have to make a little change, but I added the explanation in the output)
* Runs `jackett_launcher.sh` with the default shell
* Works if the folder has whitespaces
* Increase verbosity

core: improve linux install scripts. resolves #5533 #6098 #5407

---

.editorconfig
src/DateTimeRoutines/DateTimeRoutines.cs
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Utils/DateTimeUtil.cs

Most changes are suggested by ReSharper
Disabled some checks in `DateTimeRoutines.cs` because it's a third party library and we can need the public methods in the future.
I have doubts about private constants stating with `s_`

style: improve date utils code style

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/CardigannIndexer.cs

This PR removes duplicate functions relating to WebResult classes when we aren't looking at the content returned.

Use base class when not looking at content variable

---

src/Jackett.Common/Utils/Clients/BaseWebResult.cs
src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
src/Jackett.Common/Utils/Clients/WebClient.cs

This puts a public encoding variable into the `BaseWebResult` class for use in converting `ContentBytes` into `ContentString`, and populates it in the Run functions for now.

Move encoding for results into BaseWebResult to prepare for class merging.

---

src/Jackett.Common/Indexers/BakaBT.cs
src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Indexers/LostFilm.cs
src/Jackett.Common/Indexers/PiXELHD.cs
src/Jackett.Common/Indexers/TorrentHeaven.cs
src/Jackett.Common/Indexers/XSpeeds.cs
src/Jackett.Common/Indexers/pornolab.cs
src/Jackett.Common/Indexers/rutracker.cs
src/Jackett.Common/Services/UpdateService.cs
src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
src/Jackett.Common/Utils/Clients/WebByteResult.cs
src/Jackett.Common/Utils/Clients/WebClient.cs
src/Jackett.Server/Helper.cs

This PR changes `WebClientByteResult.Content` into `WebClientByteResult.ContentBytes` in preparation for merging the two classes.

core: rename WebClientByteResult.Content to WebClientByteResult.ContentBytes

---

.gitattributes

Git is breaking some files after 6afaf39d5a48ef6ece3b5cb22f81c13c82f74664

core: add more binary formats in .gitattributes

---

README.md

Since we are now running self contained .NET Core, no .NET is required on the host system

Readme: Full framework now no longer needed

---

src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs

This version updates the regular HttpWebClients to use the same version as the *NetCore versions. It's tested in Mono on FreeBSD and working.

Update standard clients to X509Certificate2

---

src/Jackett.Common/Content/custom.js
src/Jackett.Common/Content/index.html

The default value was to remove configuration after 2 hours.
https://datatables.net/reference/option/stateDuration

webui: save search sorting and number of entries indefinitely. resolves #4558

---

src/Jackett.Common/Utils/Clients/WebClientResult.cs

This PR adds the ability to implicitly convert a WebByteResult into a WebStringResult without having to use things like AutoFac Mappers. This is in preparation for removing AutoFac mappers for Byte and String results, and prepares for removing more distinct functions across the two classes so they can be merged easier.

core: add implicit string result conversion

---

src/Jackett.Common/Utils/Clients/BaseWebResult.cs
src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs

This pulls the code determining which Encoder to use into the BaseWebResult class, and implements it in a way that it isn't executed unless it needs to be used at least once and caches the result for future access (standard lazy eval).
We do lose access to adding log entries in the encoding determination code by moving it, but I don't feel like these entries matter too much anyway.

base: Move web-result encoding logic to internal lazy evaluaion.

---

src/Jackett.Common/Utils/Clients/WebClient.cs
src/Jackett.Common/Utils/Clients/WebClientResult.cs
src/Jackett.Server/Helper.cs

The Web Results class grouping is finally ready to be removed from Autofac.Mapper pairings so this PR removes all Autofac code concerning these classes. As I go through this old code, I keep seeing weird things that show that the large scope and different ways of doing things really were confusing people. Example as you can see in the changes, Mapper.Map already converts the ContentBytes to ContentString and assumes Bytes will never be null. But in the webclient function, we convert and assign the string a second time, but we check for null in this case. Since passing null to `Encoding.GetString()` throws a null argument exception, I decided checking for null is better and changed my conversion code to match.
Hopefully as we continue to go through the whole code base, we'll find and …

core: Remove Autofac mappings for WebResult classes.

---

src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
src/Jackett.Common/Utils/Clients/WebClient.cs

This PR moves all code that is identical in the 4 implementations of the WebClient class into the base WebClient where possible. If a full function isn't identical, and the ability to call `base.Func()` is an option for the function, then this method is used to remove as much code as possible from the base classes.

core: move identical functions up to base WebClient instance.

---

src/Jackett.Common/Utils/DateTimeUtil.cs
src/Jackett.Test/Utils/DateTimeUtilTests.cs

This modifies the date match Regex to include more options for matching in the DateTimeUtils when attempting to match "today" "tomorrow" or "yesterday"
This new Regex will match the following examples with any amount of whitespace between today and the other components (minimum 1 space between today and at), case insensitive, and can include an optional [time].
- today
- today at
- today, at
- today,
The `?:` specifies these are non-capturing groups, which helps speed up match times by not attempting to add the inner matches to the `.Groups[x]` property.

core: improve date parsing for today/yesterday/tomorrow. resolves #7701

---

src/Jackett.Common/Indexers/Abnormal.cs
src/Jackett.Common/Indexers/AniDub.cs
src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/BitHdtv.cs
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Indexers/Corsarored.cs
src/Jackett.Common/Indexers/DanishBits.cs
src/Jackett.Common/Indexers/HDOlimpo.cs
src/Jackett.Common/Indexers/InternetArchive.cs
src/Jackett.Common/Indexers/LostFilm.cs
src/Jackett.Common/Indexers/NCore.cs
src/Jackett.Common/Indexers/Newpct.cs
src/Jackett.Common/Indexers/Norbits.cs
src/Jackett.Common/Indexers/Nordicbits.cs
src/Jackett.Common/Indexers/Partis.cs
src/Jackett.Common/Indexers/Shazbat.cs
src/Jackett.Common/Indexers/SolidTorrents.cs
src/Jackett.Common/Indexers/TVstore.cs
src/Jackett.Common/Indexers/Torrentech.cs
src/Jackett.Common/Utils/Clients/BaseWebResult.cs
src/Jackett.Common/Utils/Clients/WebByteResult.cs
src/Jackett.Common/Utils/Clients/WebClient.cs
src/Jackett.Common/Utils/Clients/WebClientResult.cs
src/Jackett.Test/TestWebClient.cs

Moving up the Content properties in preparation for merge. Next PR will rename class names to base where refactoring the code base isn't necessary.

core: Move WebResult String and Byte properties to base class.

---

src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs

Tested in Redacted and AlphaRatio.
I think this should work for all Gazelle trackers.

redacted: fix double login in gazelle trackers. resolves #6461

---

src/Jackett.Common/Definitions/1337x.yml

Update to current proxy link.
This changes regularly (maybe once or twice a month?) and causes redirect errors. Is there any way to allow the redirects? https://github.com/unblocked-pw/unblocked-pw.github.io
Not sure if there are other sites using the same proxy, but they would need updated too.
Currently testing will fail due to an ongoing issue, but the site itself is fine - https://github.com/Jackett/Jackett/issues/7743

Update 1337x Proxy

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/Rarbg.cs

missing Games/PS4 and Movies/x265/1080
remove duplicate category 49
sort categories by ID.
@garfield69, after digging into the functions when seeing the duplicated category, I found no reason why we can't duplicate the category if they contain more than one category of results. Was there a particular reason you can remember as to why we made it a practice to avoid this?

Rargb: Update category mappings. Resolves #7760

---

src/Jackett.Common/Utils/BrowserUtil.cs

Tested with all public trackers and it's working in almost all of them.
The two only public trackers with the exception `Clearance failed after 30 attempt(s)` are:
* cpasbien
* demonoid
But that is because they have reCAPTCHA with image challenge. I think we should add cookies for both.
Maybe works for #7325 but not tested
Update: Tested badasstorrents and it's working too, but I don't remember having problems with this tracker.

core: update user-agent. resolves #7743 resolves #6099

---

src/Jackett.Common/Definitions/fanoin.yml
src/Jackett.Common/Indexers/TorrentSyndikat.cs

When searching for a season (manual search --> i.e. "**West World S03**") the indexer for TorrentSyndikat adds a "+" to every word. (AND Operator).
The search string then looks like this --> "**+West +World +S03**"
Unfortunately searching for  "+West +World +S03" doesn't yield any results on TS altough West World S03**E01** is available. 
Thats beacause a wildcard operator needs to be added to "S03" so it looks like this "**+West +World +S03***"
The code was revised to add a wildcard operator IF the search string ends with S01 / S02 / S03 and so on. Matching with RegEx "**s[0-9]{2}$**"
Is that an expected behaviour? Sonarr for example only has an automated search for "West World S03". (Without episodes) 
I'm new to to Github (not to coding though), so if something's missing please let me …

Fixed indexer TorrentSyndikat.cs - Adding wildcard to season search string

---

src/Jackett.Common/Definitions/glodls.yml

gtdb.to is apparently the new official domain
glodls.to works fine still
glodls.rocks looks to be dead

Update GloTorrents Links

---

src/Jackett.Common/Definitions/blutopia.yml

The main problem was the `login.test` selector. In UNIT3D the search result page doesn't contain the `login.test` selector and that trigger the re-login when it's not necessary. I check the error message instead. I think this fix can be applied to all UNIT3D trackers.

blutopia: login with user/pass and fix login redirect

---

src/Jackett.Common/Definitions/hdcity.yml

When they aren't VOSE, hdcity releases are both in Spanish and English . This PR just appends both tags instead of only [Spanish], so custom profiles looking for Dual releases can operate properly.

append both Spanish and English when it's not VOSE

---

src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs
src/Jackett.Common/Indexers/AnimeTorrents.cs
src/Jackett.Common/Indexers/BitHdtv.cs
src/Jackett.Common/Indexers/FileList.cs
src/Jackett.Common/Indexers/FunFile.cs
src/Jackett.Common/Indexers/HDOlimpo.cs
src/Jackett.Common/Indexers/NewRealWorld.cs
src/Jackett.Common/Utils/Extensions.cs

This PR removes the unused Enumerable extension `IsEmpty()` (replaced in favor of `.Any()`) and adds a new function `FirstIfSingleOrDefault<T>(T replace = default)`
This gives us an inline way of checking if there's only one element in a collection and returning it or the supplied default value if it's not the only element. I've also replaced all existing implementations with this new function that I could find by searching for `== 1` in the whole solution.

Add enumerable extension FirstIfSingleOrDefault

---

src/Jackett.Common/Indexers/Feeds/BaseNewznabIndexer.cs
src/Jackett.Common/Utils/Extensions.cs

This refactors the in house `T? TryParse<T>(string)` extension method to be faster by avoiding using reflection. It narrows the compatible types by doing so, but is currently only used for long and int, which are still compatible, as well as all other built in ValueTypes

Remove reflection in Nullable TryParse extension

---

src/Jackett.Common/Indexers/Norbits.cs

norbits: fixed no results when the tracker returns one torrent

---

src/Jackett.Common/Definitions/ettv.yml

ettv.to now redirects to ettvdl.com
Most proxies are broken by this and so have been moved to legacylinks for now

ETTV: update primary URL and proxies

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/Meta/BaseMetaIndexer.cs
src/Jackett.Common/Indexers/Meta/Fallbacks.cs
src/Jackett.Common/Indexers/Meta/ResultFilters.cs
src/Jackett.Common/Indexers/TVstore.cs
src/Jackett.Common/Models/TorznabQuery.cs
src/Jackett.Common/Utils/Extensions.cs

All of the IEnumerable and ICollection extension methods in Extensions.cs could either be inlined, weren't used, or were hiding better implementations at the calling method. This PR removes them all in favor of their alternatives.
This means that the only Enumerable extension remaining would be the one in #7837 if it's accepted and merged.

Remove enumerable related extensions

---

src/Jackett.Common/Services/CacheService.cs

This line got removed from the code and was missed in the review of #7342
I've put it back where it was (raw revert) but I don't know if this is the best place for it, since we've already confirmed that the existing cache item has the same GUID, so should we be replacing it with the new one every time it's fetched?

Revert accidentally deleted line. Resolves #7870

---

src/Jackett.Common/Indexers/TorrentDay.cs

This should fix the issue with TorrentDay. I was able to isolate the problem thanks to the stack trace in https://github.com/Jackett/Jackett/issues/7875#issuecomment-604997487

TorrentDay: fix invalid cast in results parser. Resolves #7875

---

src/Jackett.Common/Definitions/audiobooktorrents.yml

audiobooktorrents: fix title

---

src/Jackett.Common/Indexers/HDBitsApi.cs
src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationHDBitsApi.cs

Adds the filter "Origin" as well as fixing the search issue mentioned [here](https://github.com/Jackett/Jackett/issues/4859#issuecomment-605667831) by also allowing "Undefined" as Codec and Medium.

HDBits API: Add missing filter options

---

src/Jackett.Common/Indexers/Meta/Fallbacks.cs
src/Jackett.Common/Indexers/Meta/ResultFilters.cs
src/Jackett.Common/Services/ImdbResolver.cs
src/Jackett.Common/Services/IndexerManagerService.cs
src/Jackett.Common/Services/Interfaces/IImdbResolver.cs
src/Jackett.Common/Utils/Extensions.cs

This PR removes `NonNull<T>` and `NonNullException` from the extension libraries in favor of explicit checking in the few places it was used.
C#8 introduces nullable reference types, and by extension adds static compile time checking for things like this. These can be implemented when the project is able to fully support the features of C#8

core: remove non-null related extension classes.

---

src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs
src/Jackett.Common/Indexers/Abstract/CouchPotatoTracker.cs
src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs
src/Jackett.Common/Indexers/AlphaRatio.cs
src/Jackett.Common/Indexers/Anthelion.cs
src/Jackett.Common/Indexers/Avistaz.cs
src/Jackett.Common/Indexers/BrokenStones.cs
src/Jackett.Common/Indexers/CinemaZ.cs
src/Jackett.Common/Indexers/DanishBits.cs
src/Jackett.Common/Indexers/HDOnly.cs
src/Jackett.Common/Indexers/Orpheus.cs
src/Jackett.Common/Indexers/PrivateHD.cs
src/Jackett.Common/Indexers/Psytorrents.cs
src/Jackett.Common/Indexers/Redacted.cs
src/Jackett.Common/Indexers/SecretCinema.cs
src/Jackett.Common/Indexers/cgpeers.cs
src/Jackett.Common/Indexers/notwhatcd.cs

* Reorder constructor parameters in abstracts to match BaseWebIndexer
* Make TorznabCapabilities configurable per indexer

core: remove virtual member calls (part 2)

---

src/Jackett.Common/Definitions/torrentdownloads.yml

> I get clearance-failed for https://www.torrentdownloads.me/
> and failed,redirected for https://torrentdownloads.unblockit.pro/
https://github.com/Jackett/Jackett/issues/8085#issuecomment-610718909
`new=1` is the source of the issue for those proxies. Seems to be unneeded though, as removing it doesn't change the order of results for .info on either their site or in Jackett.

torrentdownloads: search string fix

---

src/Jackett.Common/Definitions/kickasstorrent-kathow.yml
src/Jackett.Common/Definitions/kickasstorrent.yml

Removed **unblockit.pro** proxy from kickasstorrent, had added it there by mistake.
**unblockninja** proxy is working again, but is (now?) for kickasstorrent-kathow, not kickasstorrent. The site itself defaults to using the search string `/usearch/torrents-search.php?q=` however `/katsearch/page/1/` works fine on it as well, so doesn't cause an issue in Jackett.
**kickasstorrent.cr** and **katcr.to** appear to be a different clone altogether (possibly of the original KAT), rather than proxies of either kickasstorrent or kickasstorrent-kathow - different favicon, different layout, different categories, etc.. If anyone wants to make them into a separate indexer, have at it.

kickasstorrent: proxy fixes

---

src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs
src/Jackett.Common/Indexers/Avistaz.cs

Tested in PirateHD only! Please, test it in AvistaZ & CinemaZ
@garfield69 I can't use the mapping from https://github.com/Jackett/Jackett/issues/7593#issuecomment-597441820 because we can't send cat > 3 to the tracker (just cat= 1, 2 or 3)
To fix #8049 (example 2 / issue 2) I had to add the category Movies in some cases. Eg, if you select MoviesHD only it's fine. If you select Movies you will see 2 categories in the results.

avistaz: fix category parsing. resolves #7593

---

src/Jackett.Common/Definitions/torrent9.yml

Following up on the discussion under this commit - https://github.com/Jackett/Jackett/commit/ea0325a1737558ff16c49cd64694a736a875ef00
The homepages of .is and .to don't contain a list of torrents, so Jackett gives a 'found no results' error. A blank search using /search_torrent/ can't be used as it redirects to their homepages (which are on www. and www4. respectively, rather than ww1.). www. and www4. can't be used either as they then redirect to ww1. to perform a search.
For an empty search or test, /top_torrent/ works for both proxies and oxtorrent.me .
I tested with followredirect removed so as links weren't being replaced without me realising, which I think is what was happening with my earlier attempts. Confirmed they still worked when it was re-enabled.
All other legacylinks …

torrent9: add /top_torrent/ so proxies can work

---

src/Jackett.Common/Models/ResultPage.cs
src/Jackett.Server/Controllers/ResultsController.cs

I was debugging qBittorrent when I found the problem was in Jackett.
This PR fix the links (comments, download...) in RSS, Torznab and Potato feeds. Only links with Unicode characters were affected but nowadays are a lot. I hope this fix some of the issues related to RSS/Torznab/Potato download links like: #7869 #5267 #5875
Some of them are related to "magnet redirect" too so this won't fix them.
The internal API used by Jackett UI was not affected by this bug.
Fixes https://github.com/qbittorrent/qBittorrent/issues/11877

core: fix links in rss, torznab and potato feeds

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
src/Jackett.Common/Utils/CookieUtil.cs
src/Jackett.Test/Utils/CookieUtilTests.cs

After fixing cookie storage in #8133 I noticed that I still have a lot of '.json.bak' files in the Jackett configuration folder. After deleting them they were created again in each request. The cause was we were parsing bad the cookies with '=' character in the value. Most Cloudflare cookies include it so we were sending bad cookies and solving the challenge in each request.
This PR should increase performance in several ways: we are not solving the challenge again (it takes time), we are not making extra requests and we are not updating the Jackett configuration in each request (both files '.json' and '.json.bak').
Tested with the client HttpWebClient2NetCore only. Please do some tests with the site 1337x in other clients.

core: fix cookie parsing (part 2)

---

src/Jackett.Common/Definitions/4thd.yml
src/Jackett.Common/Services/ConfigurationService.cs
src/Jackett.Common/Services/WindowsServiceConfigService.cs
src/Jackett.Server/Services/ServiceConfigService.cs
src/Jackett.Service/Service.cs
src/Jackett.Test/Definitions/DefinitionsParserTests.cs

This test will validate all cardigann definitions. The Azure Pipeline will fail if something is wrong. The error contains the indexer, the line and the field.
```
Error while parsing Cardigann definition 4thd.yml
YamlDotNet.Core.YamlException: (Line: 13, Col: 9, Idx: 240) - (Line: 13, Col: 9, Idx: 240): Exception during deserialization
---> System.Runtime.Serialization.SerializationException: Property 'dec' not found on type 'Jackett.Common.Models.CategorymappingBlock'.
```

test: add unit test to validate all cardigann definitions

---

src/Jackett.Common/Definitions/divteam.yml

Same as with hdcity, content is Dual (Spanish and English) by default, unless VOSE specified. 
There's also Spanish content which might or might not be flagged as VOSE (it seems it usually doesn't, unless original language is something like Galician, which is a very edge case).
In case of false positives when flagged as Dual but only Spanish, Radarr/Sonarr will still find Spanish and download, so just by handling MediaInfo properly nothing happens.
In case of the ones flagged as VOSE, there's no much we can do so I think it's a nice tradeoff

Add language flags taking VOSE into account

---

src/Jackett.Common/Indexers/CardigannIndexer.cs

This replaces #8009 and follows the current syntax styles to add functions eq (equals) and ne (not equals). These functions take exactly 2 parameters, and compares their value, returning `.True` or `.False` as appropriate.
I was able to test this on several yml indexers and it doesn't break the existing template logic for and/or.
As a byproduct of where and how I added this, the following extra features are now also available:
* Parentheses around variable names in and/or are now optional
* And/Or now support 2+ variables instead of just 2-3
* Nested functions are now allowable e.g `and eq (.Config.Language) "English" eq (.Results.Page) "3"`
* Parenthesis can be used around nested functions to show grouping precedence
* `(and .Var1 .Var2)` evaluates to either `(.Var1)` or `(.Var2)`
* New …

Cardigann: Add template functions eq/ne

---

src/Jackett.Common/Definitions/magnetdl.yml

Listed in the Accessing MagnetDL section from https://www.magnetdl.com/site/help/

magnetdl: add official .org proxy

---

src/Jackett.Common/Definitions/magnetdl.yml

Testing in Sonarr (presumably also Lidarr and others) currently finds no results due to the use of `download/movies/` for empty search.
Searching for `of` was the best fix :
- searching `the` or single characters 404s out
- `of` returns more results than other common words I could think of
- gives a good mix of movies, tv, audio, etc.
Added a second results page (40 per) to improve odds of getting at least one for the relevant cat, and just generally returning search results.
Let me know if there's a downside to any of this that I've missed.

magnetdl: fix search tests for Sonarr et al

---

src/Jackett.Common/Indexers/CardigannIndexer.cs

This adds a Template variable .Today.Year that includes the current year to resolve #8258. It also updates the `getTemplateVariablesFromConfigData()` code to utilize C#8 features to be more concise.
Seeing as this is the simplest place to add global template variables and we've added multiple non-config data variables here because of that, I've also renamed the function to match the intended purpose.

Cardigann: Add .Today.Year to template variables. Resolves #8258

---

src/Jackett.Common/Definitions/nyaasi.yml

This was removed in fe5c1d49629c004c7f186317525d2c4563c80336 and I'm not sure why.

Restore filter config for nyaasi

---

src/Jackett.Common/Models/IndexerConfig/ConfigurationData.cs

Cleans up some internals of ConfigurationData for clarity. Using pattern matching instead of an enum.

Core: remove ItemType enum in favor of pattern matching

---

src/Jackett.Common/Definitions/cili180.yml

[Proxy list](https://www.liaorenso19.xyz/) found on the homepage:
Proxies listed as http, but https works fine.
Not sure if Cili180 is another candidate for https://github.com/Jackett/Jackett/issues/8355, but I left cilijj.xyz as the primary URL. It still works fine. Happy to move it down if that's preferred.

cili180: add liaorenso1#.xyz proxies

---

src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs
src/Jackett.Common/Indexers/BitHdtv.cs
src/Jackett.Common/Indexers/DigitalHive.cs
src/Jackett.Common/Indexers/Fuzer.cs
src/Jackett.Common/Indexers/GazelleGames.cs
src/Jackett.Common/Indexers/IPTorrents.cs
src/Jackett.Common/Indexers/SceneHD.cs
src/Jackett.Common/Indexers/Superbits.cs
src/Jackett.Common/Indexers/TorrentDay.cs
src/Jackett.Common/Indexers/TorrentLeech.cs
src/Jackett.Common/Indexers/digitalcore.cs

Before this change the message was:
Your cookie did not work: Your cookie did not work
Now:
Your cookie did not work: Found 0 results in the tracker

core: fix cookie login message

---

src/Jackett.Common/Definitions/vizuk.yml

Certificate expired on 26 april

vizuk: ignore expired certificate.

---

src/Jackett.Common/Definitions/1337x.yml
src/Jackett.Common/Definitions/btdb.yml
src/Jackett.Common/Definitions/demonoid.yml
src/Jackett.Common/Definitions/rutor.yml

Following up on https://github.com/Jackett/Jackett/issues/8381 and https://github.com/Jackett/Jackett/commit/832dcc82c49a4f9055bf7d3f56f4123f425e50aa
Proxies checked:
- black-mirror.xyz
- unblockninja.com
- unblockit.one
- root.yt
new-rutor.org is also down

assorted: removed down proxies

---

src/Jackett.Common/Definitions/yourbittorrent.yml

HTML has diverged from *.com and *2.com - no longer works with Jackett.
If someone wants to have a look to see if it's salvageable, feel free. I couldn't see anything.

yourbittorrent: remove *.host proxy

---

src/Jackett.Common/Definitions/amigosshare.yml

Add Brazilian string to title when video contains Brazilian Portuguese audio stream.
Useful for Sonarr/Radarr detect language

Add Brazilian string to title

---

src/Jackett.Common/Indexers/AnimeBytes.cs

Previous link was valid only for anime section; music section uses `torrents2.php`, however to simplify and consolidate both sections, an universal link is available that redirects user to an appropriate page.

Use universal torrent link for AnimeBytes

---

src/Jackett.Common/Definitions/bibliotik.yml

error    too many spaces inside braces  (braces)

core: validate yaml definitions (yamllint part 6 #8575)

---

src/Jackett.Common/Definitions/vhstapes.yml
src/Jackett.Common/Services/IndexerConfigurationService.cs
src/Jackett.Common/Services/IndexerManagerService.cs
src/Jackett.Common/Services/Interfaces/IIndexerConfigurationService.cs
src/Jackett.Updater/Program.cs

The PR allows to change the indexer id without breaking backward compatibility. Note that changing the id must be justified.
Steps to rename the id:
1. Rename the indexer id (in yaml or c#)
2. Edit `IndexerManagerService.cs` to add `old id` and `new id` in the map
3. Optional: you can rename the yaml / c# too
* yaml: rename the file and add the `old file name` into `Program.cs` to be removed by the updater
* c#: rename the file and the class name (not need to change `Program.cs`)
4. Optional: The tracker name / description is not related to the id and it can be changed anytime
How it works for the user:
1. The updater will remove the old .yaml definition (if it's a .yaml indexer) and the new one will be extracted in the folder.
2. In the first start, Jackett will rename the old …

core: allow to rename indexer id (part 3 #8355)

---

src/Jackett.Common/Indexers/BJShare.cs

Removed handling that removed the original audio from the details, since the tracker doesn't use it anymore and it was causing some issues.
Signed-off-by: Christian Franchin dos Santos <christianfranchin@gmail.com>

Removed handling that removed the original audio from the details.

---

src/Jackett.Common/Definitions/topnow.yml

`https://topnow.se/index.php?search=` - no results
`https://topnow.se/index.php` - homepage with latest torrents

topnow: fix keywordless search

---

src/Jackett.Common/Definitions/btsow.yml

current - https://btsow.club/
redirect - https://tellme.pw/btsow
new - https://bteve.com/
tested, working

btsow: new URL

---

src/Jackett.Common/Definitions/pleasuredome.yml

Existing pleasuredome definition breaks on login due to site changes renaming the form and login page locations. This changes fixes it in my testing.

Fix login handling for pleasuredome

---

src/Jackett.Common/Definitions/magnetdl.yml

https://www.magnetdl.com/o/of/age/desc/ - 404
change to - https://www.magnetdl.com/2/2020/age/desc/ (or any year up to 2999)
Tested, working

magnetdl: fix keywordless search

---

install_service_macos

TL/DR: Update macOS install script with quarantine permissions; should fix #5589
The added lines read the `com.apple.quarantine` attribute from the `jackett` executable, replace the first 4 characters (`0081` -> `00c1`) so Gatekeeper won't complain anymore and set the modified attribute for the `jackett` executable and all DLL and dylib files.

Update macOS install script

---

src/Jackett.Common/Definitions/torrentz2.yml

Site is working, but untested in Jackett due to `Clearance failed after 10 attempt(s).`

torrentz2: restore fixed unblockit proxy

---

src/Jackett.Common/Definitions/jpopsuki.yml

Fixes #9125 for real and opts to use ajax.php instead of torrents.php to slim down request size.
Tested and confirmed working:
```
2020-07-11 08:15:01.6590 Info Jackett startup finished in 3.516 s
2020-07-11 08:15:22.0874 Info CardigannIndexer (jpopsuki): Relogin required
2020-07-11 08:15:37.5195 Info Manual search for "test" on jpopsuki with 50 results.
```
PLEASE NOTE:
Currently jpopsuki has issues if you try to do searches with an empty searchstr in tandem with `disablegrouping=1`. This usually results in an HTTP 200 `Database Error` response. This issue is with jpopsuki though, so there's nothing much we could do unless we wanted to work around parsing while torrent grouping was enabled, which is basically impossible since ordering is not correct with grouping enabled among other …

jpopsuki: use ajax.php for searching and fix search query params

---

src/Jackett.Common/Definitions/liaorencili.yml

Sources:
http://www.lrcili.xyz/
https://www.cilipro.xyz/
and some older sites working again
Tested, working.

liaorencili: update proxies

---

src/Jackett.Common/Definitions/racingforme.yml

Add keywords filter search replacement to ensure compatibility with search terms of races since S##E## is not compatible.
e.g. S2020E02 Becomes `2020 Round 2`

RacingForMe: Search replacement compatibility

---

src/Jackett.Common/Definitions/torrent9.yml

Fix for https://github.com/Jackett/Jackett/pull/9299

torrent9: remove *.is from legacylinks

---

src/Jackett.Common/Definitions/btgigs.yml
src/Jackett.Common/Definitions/hdspain.yml
src/Jackett.Common/Definitions/karagarga.yml
src/Jackett.Common/Definitions/onejav.yml
src/Jackett.Common/Definitions/torrentleech-pl.yml
src/Jackett.Common/Indexers/CardigannIndexer.cs

Currently if an optional variable is defined in a Cardigann indexer, and it exists for one result, all subsequent results have the same incorrect value of the variable set.  I think it needs to be explicitly unset if it's missing in a result to avoid this.
As an example, on bibliotek, I was extracting an author variable and editor variable for each result. Author and editor are optional but at least one will exist. For results that don't have authors (they have editors instead) the author remains set at the last found value even.  So instead of:
Title 1 by author 1
Title 2 by editor2
I'm ending up with:
Title 1 by author 1
Title 2 by author1
This fix resolves the issue for me, though I'm not familiar with Jackett so might have missed a side effect!

Fixed: Unset variable in CardigannIndexer if it's missing in the row

---

src/Jackett.Common/Definitions/kickasstorrent-kathow.yml
src/Jackett.Common/Definitions/kickasstorrent.yml

Not sure if this is just a fallback while newkatcr.co is down, but the proxy has switched to kathow, for now at least. I'll check after newkatcr.co is back up if this reverts.

kickasstorrent & kickasstorrent-kathow: switch unblockninja proxy

---

src/Jackett.Common/Definitions/demonoid.yml

```
Newspost - July 17th, 2020	
Additional domains
We are adding two additional domains where you can visit us.
The first domain is Dnoid.pw
The second domain is Dnoid.to
```
untested due to use of Cloudflare's DDoS protection hcaptcha challenge

Demonoid: add dnoid.to & dnoid.pw

---

src/Jackett.Common/Definitions/ettv.yml

ettvdl.com redirects to ettvcentral.com
Announcement - https://www.ettvcentral.com/forum/view/topic/domain-change-s01e02-upload-rights--1225
Official proxy list - https://ettvproxies.com/

ettv: remove ettvdl.com & add ettv.be

---

src/Jackett.Common/Definitions/1337x.yml
src/Jackett.Common/Definitions/btdb.yml
src/Jackett.Common/Definitions/ettv.yml
src/Jackett.Common/Definitions/eztv.yml
src/Jackett.Common/Definitions/glodls.yml
src/Jackett.Common/Definitions/idope.yml
src/Jackett.Common/Definitions/kickasstorrent.yml
src/Jackett.Common/Definitions/magnet4you.yml
src/Jackett.Common/Definitions/monova.yml
src/Jackett.Common/Definitions/nyaasi.yml
src/Jackett.Common/Definitions/oxtorrent.yml
src/Jackett.Common/Definitions/prostylex.yml
src/Jackett.Common/Definitions/rutor.yml
src/Jackett.Common/Definitions/tokyotosho.yml
src/Jackett.Common/Definitions/torrent9clone.yml
src/Jackett.Common/Definitions/torrentdownload.yml
src/Jackett.Common/Definitions/torrentdownloads.yml
src/Jackett.Common/Definitions/torrentz2.yml
src/Jackett.Common/Definitions/zooqle.yml

proxyportal.pw & uk-unblock.pro have also been dropped
KAT obviously untested
BTDB & nyaa.si removed by proxy site

assorted: change unblocked proxy domain to *.rest

---

src/Jackett.Common/Definitions/hdcity.yml

Until Sonarr add double language managment at titles like radarr, it is better to removed.

[HDCity] Removed English from not VOSE

---

src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Models/DTO/TorrentPotatoResponseItem.cs
src/Jackett.Common/Models/ReleaseInfo.cs

There are several sites with wrong seeds/leechers like 4,294,967,295
We can fix that by increasing the variable to long (to avoid casting error)
and then set a valid value (0 seeds/leechers)

core: change seeds/leechers type to long. resolves #6558

---

src/Jackett.Common/Utils/Clients/WebClient.cs

Print HTML in debug mode. Fix bugs in old implementation too

core: refactor http webclient part 17 #8529

---

src/Jackett.Tray/Main.cs

core: fix windows tray crash. resolves #8398

---

src/Jackett.Common/Definitions/hachede.yml

This changes was missing yesterday, the FULLBR detects it as HDTV-1080p in the case of HacheDe, with this change it already detects it correctly as BRDISK

[HacheDe] Add BRDISK in the title if the release is a FullBR

---

src/Jackett.Common/Indexers/TorrentSyndikat.cs

Resolves #9543.
Could we add a [`hacktoberfest` repo topic](https://github.com/digitalocean/hacktoberfest/pull/596)?

Adjust Torrent-Syndikat indexer to new API

---

src/Jackett.Common/Indexers/BJShare.cs

BJ-Share: Added support for new entry layout when there's only one row for an grouped torrent, eg: The Walking Dead: World Beyond

BJ-Share: Added support for new entry layout when there's only one row for a grouped torrent

---

src/Jackett.Common/Indexers/TorrentSyndikat.cs

The old search string cleanup-stuff was only needed for web-based searches. The new API doesn't require that.
However, wildcards after simple season definitions are required so we search for single episodes as well.
Fixes the bug reported by [this comment](https://github.com/Jackett/Jackett/issues/9543#issuecomment-703506425).

torrentsyndikat: only add wildcard to season queries

---

README.md
src/Jackett.Common/Indexers/BB.cs

A slash was being added twice to the URL. Once from the base URI, once from the relative path. Despite still being a valid URI, sonarr freaks out and cannot deal with it and throws away any such links.
something like: https://domain.tld//index.php?arg=bork

[bB] Prevent double slash in links

---

src/Jackett.Common/Indexers/YTS.cs

In particular, move the group name (YTS) to the end, where it belongs.

Fixed: Create scene-style names in YTS

---

src/Jackett.Common/Indexers/Redacted.cs

This PR turns Redacted to Cookie/Username based login. 
Until the core issue is fixed, the API usage remains unusable.
https://github.com/Jackett/Jackett/issues/9751
@garfield69 please consider merging this.

redacted: reverted from api to user based login

---

src/Jackett.Common/Indexers/AwesomeHD.cs

Resolves https://github.com/Jackett/Jackett/issues/9861
There're times when `smallcover` and `cover` are returning invalid URIs.

ahd: fixed an issue caused by invalid uri

---

src/Jackett.Common/Definitions/kickasstorrent-kathow.yml
src/Jackett.Common/Definitions/kickasstorrent.yml
src/Jackett.Common/Definitions/kickasstorrents-to.yml

Proxy list for kathow - https://ww2.kickass.how/
Ignore https://thekat.app/, https://kickasshydra.dev/, and https://kickasshydra.net/

assorted kickasstorrents clones: add and amend proxies

---

src/Jackett.Common/Indexers/CardigannIndexer.cs

As per @ilike2burnthing [request](https://github.com/Jackett/Jackett/issues/9029#issuecomment-716907578), here's a PR that add a check for redirect when pulling the login page.
This fix the redirect(307) issue with yggtorrent. See https://github.com/Jackett/Jackett/issues/9959#issuecomment-716058618 for more info.
It was not tested with other indexers.

Cardigann: add check for redirect when pulling login page

---

src/Jackett.Common/Indexers/AnimeBytes.cs

Music support seems to have disappeared from Jackett recently, this adds it back. Fixes #10018

Animebytes: Add music category

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Models/DTO/Indexer.cs
src/Jackett.Common/Models/TorznabCapabilities.cs
src/Jackett.Common/Models/TorznabCapabilitiesCategories.cs
src/Jackett.Common/Models/TorznabCatType.cs
src/Jackett.Common/Models/TorznabCategory.cs
src/Jackett.Test/Common/Indexers/BaseWebIndexerTests.cs
src/Jackett.Test/Common/Indexers/CardigannIndexerTests.cs
src/Jackett.Test/Common/Models/DTO/IndexerTests.cs
src/Jackett.Test/Common/Models/TorznabCapabilitiesCategoriesTests.cs
src/Jackett.Test/Common/Models/TorznabCapabilitiesTests.cs
src/Jackett.Test/TestHelpers/TestCategories.cs

* Core: Categories are stored in a real tree
* Sorting: First Torznab categories sorted by Id and then custom cats sorted by Name
* Filtering: Results with child category are not removed when searching by parent category. Details in #8049
* Jacket UI: Add parent category when at least one child category exists
* Torznab (caps): Remove non existent children categories. Remove duplicated categories. Details in #10006

core: rewrite category code from scratch. resolves #8049

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/SolidTorrents.cs
src/Jackett.Common/Models/TorznabCapabilitiesCategories.cs
src/Jackett.Test/Common/Indexers/BaseWebIndexerTests.cs
src/Jackett.Test/Common/Indexers/CardigannIndexerTests.cs
src/Jackett.Test/Common/Models/DTO/IndexerTests.cs
src/Jackett.Test/Common/Models/TorznabCapabilitiesCategoriesTests.cs
src/Jackett.Test/Common/Models/TorznabCapabilitiesTests.cs
src/Jackett.Test/TestHelpers/TestCategories.cs

* When category ids in the indexer are "strings" we create a unique hash to make it compatible with Torznab
* This PR also fix several issues related to custom cats

core: add custom cats in indexers with string categories. resolves #9746

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Utils/MagnetUtil.cs
src/Jackett.Test/Common/Indexers/BaseWebIndexerTests.cs
src/Jackett.Test/Common/Utils/MagnetUtilTests.cs
src/Jackett.Test/TestHelpers/TestWebIndexer.cs

* global list of public trackers
* infohash => magnet link (only in public trackers)
* magnet link => infohash

core: generate magnet link from infohash and vice versa. resolves #8590

---

src/Jackett.Common/Definitions/torrentproject2.yml

Cats can be shown in results by searching using `/browse?t=`.
I have likely missed some, so feel free to double check, but that's all I could find.
Keywordless search gives 50 results per page, but keyword search only gives 20, meaning you get 100 for an update in Sonarr/Radarr/*arr, but only 40 for a search. Not sure whether to bump that up with another page or not.
It's also possible to search by cat on the site, e.g.  `/browse?t=2020 type:music`, but it's not always consistent with the cat id - music, movies, games, xxx, and other all work, but apps is type:applications, and I have no idea what they're using for TV (or documentaries, or mobile). So yea, basically I didn't add that as I couldn't figure it out.

torrentproject2: change search, add categorymappings

---

src/Jackett.Common/Indexers/RuTracker.cs

When the TV series torrent doesn't have a metadata in the title, it doesn't match the regexp schema, so I've fixed this by making the $5 group optional.
I don't know how to test it properly as I don't have windows, but I've checked it this way:
```
sh-3.2$ cat ~/Documents/test.cs
using System.Text.RegularExpressions;
var regex = new Regex(".+\\/\\s([^а-яА-я\\/]+)\\s\\/.+Сезон\\s*[:]*\\s+(\\d+).+(?:Серии|Эпизод)+\\s*[:]*\\s+(\\d+-*\\d*).+,\\s+(.+)\\][\\s]?(.*)");
var format = "$1 - S$2E$3 - rus $4 $5";
var oldRegex = new Regex(".+\\/\\s([^а-яА-я\\/]+)\\s\\/.+Сезон\\s*[:]*\\s+(\\d+).+(?:Серии|Эпизод)+\\s*[:]*\\s+(\\d+-*\\d*).+,\\s+(.+)\\]\\s(.+)");
Console.WriteLine("Old regex:");
regex.Replace("Чёрное зеркало / Black Mirror / Сезон: 5 / Серии: 1-3 (3) (Оуэн Харрис, Карл Тиббеттс, Отто …
```

Fixed rutracker title formatting for TV series without metadata

---

src/Jackett.Common/Indexers/ShizaProject.cs

Fixes auth check for shizaproject indexer.
Suddenly for now I can't make errorMessage printing work.
During curl requests (with invalid auth) I gets 200 (as in browser) and html. But Jackett gets 302 in this case, I have no idea for now.
/fix #10160

Fix auth check for shizaproject

---

src/Jackett.Common/Definitions/demonoid.yml
src/Jackett.Common/Definitions/exttorrents.yml
src/Jackett.Common/Definitions/ilcorsaronero.yml

TorrentBay and Unblock Ninja seem to be related in some way, so just using the proxies not included or working on Unblock Ninja:
- https://ext.unblockninja.com/ redirects to https://ext.torrentbay.to/
- https://torrent9.torrentbay.to/ has Unblock Ninja in its title
The proxy for TorrentProject is for https://torrentproject.to/ which is a separate site.
Also added 3 more results pages to EXT (25 per, now 100 total), and removed 3 from Il Corsaro Nero (40 per, now 120 total).

assorted: add torrentbay proxies

---

src/Jackett.Common/Definitions/torrent9.yml

Relates to https://github.com/Jackett/Jackett/commit/e2defbcb839006d7daa9a46e542140804e559398
https://torrent9.to/search_torrent/bad-boys-for-life.html,trie-date-d
and
https://torrent9.to/search_torrent/bad%20boys%20for%20life%3Ftrie-date-d
return the same results (same for .gg and .me)
The only issues are with
https://torrent9.to/search_torrent/bad-boys-for-life,trie-date-d
and
https://torrent9.to/search_torrent/bad%20boys%20for%20life%2Ctrie-date-d
which include `,trie-date-d` in the search term (same for .gg and .me)

torrent9: remove *.li domain

---

src/Jackett.Common/Definitions/amigosshare.yml
src/Jackett.Common/Definitions/haidan.yml
src/Jackett.Common/Definitions/pirateiro.yml
src/Jackett.Common/Definitions/tjupt.yml
src/Jackett.Common/Definitions/wdt.yml
src/Jackett.Common/Definitions/ydypt.yml

lint
I take it where lines are commented out at the first character, e.g. https://github.com/Jackett/Jackett/blob/2be45b6c9dacc068e6693600e8663b1ac76c3652/src/Jackett.Common/Definitions/darktracker.yml#L745-L760 we ignore the lint warning?

assorted yml: code tidy

---

README.md
src/Jackett.Common/Definitions/extratorrent-it.yml

ExtraTorrrent.ag is back as https://extratorrents.it/home
The .yml is almost entirely the same as when .ag was removed - https://github.com/Jackett/Jackett/blob/b32dd233563d1bd5f20c318b04f169e9ae8f713f/src/Jackett.Common/Definitions/extratorrent-ag.yml
Changes are to the id, name, desc, links, some updated category mappings (e.g. `Books/Ebook` to `Books/EBook`), and the keywordless search path now being `*/home`.
Also renamed one category: `Wallpapers` to `Pictures - Wallpapers`; and moved and renamed another: `Software - Mobile` (under `Apps`) to `Mobile` (under `Mobile`).

extratorrent-it: add public tracker

---

src/Jackett.Common/Definitions/divteam.yml

Related to issue #10196
A result can be highlighted or not, but not both. When a search is performed and the item is highlighted, it is not currently displayed as a result. Roll back to find a way to filter only when empty search is performed.
In the empty search, the highlighted elements should also be shown but only if their date is less than the last element to show according to the number of elements that the user has selected to show. Not trivial.
This reverts commit e74b64d4117c087c78e8cf633614a3d320b4edb4.

Revert "divteam: drop pinned results resolves #10196"

---

src/Jackett.Common/Indexers/DigitalCore.cs

`A Hit and Run happens when you download something and do not seed it for at least 5 days or until the ratio is 1:1.`
https://digitalcore.club/info/faq

digitalcore: correct MST

---

src/Jackett.Common/Definitions/brasiltracker.yml
src/Jackett.Common/Definitions/gigatorrents.yml
src/Jackett.Common/Definitions/greekdiamond.yml
src/Jackett.Common/Definitions/hddisk.yml
src/Jackett.Common/Definitions/hdzone.yml
src/Jackett.Common/Definitions/polishsource.yml
src/Jackett.Common/Definitions/uniongang.yml

See commits for comments.
Only ones that gave me pause:
**GigaTorrents** - it has a global MR but none for individual seeds, so do we leave this out?
**HDZone** - in a quick browse through their recent torrents, I haven't seen an H&R logo, but should we account for a download having one and include the 14 day MST?

assorted: correct MST and MR

---

src/Jackett.Common/Definitions/bitru.yml

http://bitru.org/browse.php?s=&rek=&sort= or any search including `rek=` instead of `rek=no` redirects to https://yandex.ru/

bitru: fix search redirect

---

src/Jackett.Common/Definitions/sktorrent.yml
src/Jackett.Common/Definitions/trezzor.yml

SKTorrent had category embedded to the torrent name, now checking for innertext instead of title
also SKTorrent added czech movie database rating to the torrent name
Trezzor had "Detaily: " as prefix for all links, removed with regex and improved readability by replacing . with space

fixed torrent names on SKTorrent and Trezzor tracker

---

src/Jackett.Common/Indexers/AniDUB.cs

https://github.com/Jackett/Jackett/issues/8962#issuecomment-734485190
As used by Sonarr, `value="digimon+adventure+27"`
```
Информация
К сожалению, поиск по сайту не дал никаких результатов. Попробуйте изменить или сократить Ваш запрос.
```
```
Information
Sorry, your site search did not return any results. Please try to change or shorten your request.
```
Confirmed in browser.
`value="digimon adventure 27"`
Gives appropriate results in browser.

anidub: fix search, don't replace spaces with +

---

src/Jackett.Common/Services/CacheService.cs
src/Jackett.Common/Services/Interfaces/ICacheService.cs
src/Jackett.Server/Controllers/ServerConfigurationController.cs

* Empty cache when user changes proxy configuration
* Reduce the CPU needed to clean up results that exceed the limit per indexer

core: search cache optimizations #10382

---

src/Jackett.Common/Content/custom.js
src/Jackett.Common/Content/index.html
src/Jackett.Common/Jackett.Common.csproj
src/Jackett.Common/Models/Config/ServerConfig.cs
src/Jackett.Common/Models/DTO/ServerConfig.cs
src/Jackett.Common/Services/CacheService.cs
src/Jackett.Common/Utils/BrowserUtil.cs
src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Server/Controllers/ServerConfigurationController.cs
src/Jackett.Server/Services/ServerService.cs

POC with FlareSolverr integration.
https://github.com/ngosang/FlareSolverr
Details: #9029

FlareSolverr integration. Bypass Cloudflare protection

---

src/Jackett.Common/Definitions/cpabien.yml
src/Jackett.Common/Definitions/dmhy.yml
src/Jackett.Common/Definitions/epizod.yml
src/Jackett.Common/Definitions/exttorrents.yml
src/Jackett.Common/Definitions/hddolby.yml
src/Jackett.Common/Definitions/mypornclub.yml
src/Jackett.Common/Definitions/pirateiro.yml
src/Jackett.Common/Definitions/prostylex.yml
src/Jackett.Common/Definitions/torrentbomb.yml
src/Jackett.Common/Definitions/torrentkitty.yml
src/Jackett.Common/Definitions/torrentproject.yml
src/Jackett.Common/Definitions/torrentz2k.yml
src/Jackett.Common/Definitions/yggcookie.yml
src/Jackett.Common/Definitions/yggtorrent.yml

Re: https://github.com/Jackett/Jackett/issues/10500 - only one not included is mejortorrent (C#)
Also checked my (very out of date) list of sites using Cloudflare DDoS Protection - https://github.com/Jackett/Jackett/issues/7325#issuecomment-603887196
From that, I _think_ I have seen extratorrent-cd and pornleech using it recently, but I may be misremembering, so I'll leave them for now.
The official proxies for 1337x and LimeTorrent are still using it, but the main sites aren't, so I wasn't sure if the info should be included/edited.
Open for suggestions on phrasing, formatting, positioning, etc.

assorted yaml: add info about flaresolverr

---

src/Jackett.Common/Indexers/PolishTracker.cs

I need to my Sonarr and Radarr can recognize if torrent is Polish

PolishTracker: Add POLISH to polish language releases title

---

src/Jackett.Common/Indexers/CardigannIndexer.cs

* Allow GoTemplates in search.headers
* Send search.headers in login.test and download requests

core: cardigann add headers in test and download requests

---

src/Jackett.Common/Definitions/mononokebt.yml

mononoke BT lacked this option, all of the torrent there are in VOSTFR but given the sonarr config, you need or not VOSTFR

mononokebt: add vostfr checkbox for add to titles

---

src/Jackett.Common/Definitions/broadcity.yml

Site is forcing to https. At the moment it gives an error when attempted to add.
```
2021-01-16 18:48:17 	Error 	
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match
at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 777
at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 920
at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IAct …
```

broadcity: update on protocol

---

src/Jackett.Common/Models/ChannelInfo.cs
src/Jackett.Common/Models/ResultPage.cs
src/Jackett.Server/Controllers/ResultsController.cs
src/Jackett.Test/Common/Models/ResultPageTests.cs

Indexer logos were removed long time ago. Just removing the Image tag in the RSS feed that points to a broken image.

core: remove rss feed image (legacy code) #324

---

src/Jackett.Common/Indexers/SubsPlease.cs

The SubsPlease API doesn't support searching for releases by resolution, but this PR adds support for detecting if a resolution was passed as part of the search terms and then filtering the release results to those that match the resolution.

SubsPlease: Enable searching by resolution

---

src/Jackett.Common/Definitions/yggcookie.yml
src/Jackett.Common/Definitions/yggtorrent.yml

https://github.com/Jackett/Jackett/issues/10824
Also removed `searchanddlurl` from yggcookie.
Was going to add the test link for yggcookie as well, but given https://github.com/Jackett/Jackett/issues/10655, we'd just be flooded with issues with no solution. At least this way users can still search, but not download.

yggtorrent: revert to post method for login

---

src/Jackett.Server/Controllers/BlackholeController.cs

Sometimes a torrent's name is very long which causes an exception when writing the blackhole file to disk.
**Only in that specific case**, this PR replaces the file name with a GUID (which still allows torrent clients to pick the files up and does not affect the name of the torrent once loaded in a client) instead of implementing somewhat arbitrary filename-shortening logic, which could possibly result in filename collisions and would require more code.
Open to discussion on the way the filename should be shortened if you're not OK with the GUID solution.

[Bugfix] Fix BlackholeController exception when torrent name is very long

---

src/Jackett.Common/Indexers/Anidex.cs

Also:
- ~added `all languages` option (not sure if that will work)~ (nope, didn't work)
- updated `group_id`

anidex: fix search by language. resolves #10930

---

src/Jackett.Common/Indexers/NCore.cs

https://ncore.cc/ now returns a 301 to https://ncore.pro/

ncore: update domain *.pro . resolves #10956

---

src/Jackett.Common/Indexers/TorrentParadiseMl.cs

Get 'current year' results for keywordless query in torrent-paradise-ml. Resolves #4598

---

src/Jackett.Common/Indexers/DivxTotal.cs

#11027 
DivxTotal does not have an API and needs a lot of page loads to get the desired query results. Because of this you might get more than 100 releases per query, because each page can contain multiple links to full seasons, episodes, tv series, etc. which is then parsed into separate releases.
I've moved some code to return as soon as it's obvious that the loaded page won't be parsable into a release.
Still, queries take a very long time to complete.

DivxTotal improvements. Resolves #11027

---

src/Jackett.Common/Indexers/LostFilm.cs

The current Lostfilm url (https://www.lostfilm.run) is blocked 
```
Доступ к информационному ресурсу ограничен на основании Федерального закона от 27 июля 2006 г. N 149-ФЗ "Об информации, информационных технологиях и о защите информации"
```
Updated to use the correct one https://www.lostfilm.uno

Update LostFilm.tv URL

---

src/Jackett.Common/Indexers/Anidex.cs

Resolves #10488
Anidex doesn't support Season and Episode searches. Including them in the capabilities is causing apps to perform searches with only the show title which returns incorrect results.

Remove invalid Anidex capabilities

---

src/Jackett.Common/Definitions/extremetorrents.yml

This replaces dutch keywords so radarr/sonarr understands it.
I've copied it from: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/film-paleis.yml#L97-L105
Checked locally and it's working as intended.

[ExtremeTorrents] Replace dutch title keywords

---

src/Jackett.Common/Indexers/RuTracker.cs
src/Jackett.Common/Utils/StringUtil.cs
src/Jackett.Test/Common/Utils/StringUtilTests.cs

#11161 
Adds methods to `StringUtil` to help find tags in release titles. These methods are then used to clean up RuTracker's release titles and to find a substring in the form of `year/year` which would indicate that an audio release (such as a music album) is a re-release.
If a release is found to be a re-release, `(Re-release)` is added to the end of the audio release's title.

Feature/rutracker music album rerelease. resolves #11161

---

src/Jackett.Common/Indexers/Anidex.cs
src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/RarBG.cs
src/Jackett.Common/Jackett.Common.csproj

Anidex seems to have been having quite a lot of issues ongoing for a few months now. The pages are returning 500 errors but if you refresh a few times the page loads. Obviously the ideal solution would be for Anidex to resolve this but not much seems to be happening there and this is causing the indexer to go offline in Sonarr.
This change adds retry logic using [Polly](https://github.com/App-vNext/Polly). The retries are configured with a delay between which increases exponentially in order to reduce strain on the server. It will also log a warning message when an error response is received so that the attempts can be tracked.
The default has been set not to retry as the delay will increase the API response times.
Apologies if this isn't meeting coding standards. My VS install is broken …

Add retry logic to Anidex

---

src/Jackett.Common/Definitions/amigosshare.yml
src/Jackett.Common/Indexers/BJShare.cs

I had already contributed for improve Brazilian Portuguese support of AmigosShare tracker.
Now this is to improve BJShare Tracker.
This code only adds "Brazilian" at title to support Sonarr/Radarr detect Brazilian Portuguese content.
I also changed AmigosShare a little.

Better Brazilian Portuguese support

---

src/Jackett.Common/Services/ConfigurationService.cs

This is to address the DietPi issues where they don't use the expected default location, and instead use `$HOME/Jackett` as the config directory. This causes the migrator to copy files to themselves, then remove the config directly entirely.
This change addresses this condition by checking the AppData folder against the assumed #11313 bugged folder on UNIX systems, and if they differ the migration will occur *. In addition, it adds a guard around the deletion portion of the migration function so we don't remove folders we've just migrated to.
\* The reason this change was added only to UNIX is the original migration function was made to copy files onto themselves with an updates security policy on Windows devices only, I didn't want to affect this behaviour.

Don't migrate UNIX configs if the input and output directories are the same

---

src/Jackett.Common/Services/ConfigurationService.cs

Basically checks to see if we're looking at the installation directory.
If we're not, do the migrations, otherwise we don't want to be deleting
or copying the install directory to the user config directory.
Fixes #11463

Don't delete $(cwd)/Jackett if it has jackett

---

src/Jackett.Common/Utils/DateTimeUtil.cs

Exceptions have a huge impact on performance.
When it's possible and meaningful, use Try method version instead of catch and exception.
DateTimeUtil.FromUnkown is used in 26 different points and many times during the results parsing.
Reducing the cost of it should help to improve performance.

[Performance] Convert Parse/Catch to TryParse

---

.github/ISSUE_TEMPLATE.md

Will hopefully dissuade some people from deleting the template or submitting an empty one.
Added link to troubleshooting as well to prevent some issues from being opened in the first place.
We'll still get redundant issues, but maybe this will reduce the number.

issue template: minor edit

---

azure-pipelines.yml

dotnet format bumped to 5.1.225507 today - https://github.com/dotnet/format/blob/main/CHANGELOG.md
Changes include dotnet/format#982 which outputs warnings and errors to StdErr, and we use `failOnStderr`.
--fix-whitespace - https://github.com/dotnet/format/blob/main/README.md

pipelines: fix whitespace

---

src/Jackett.Common/Indexers/NewPCT.cs

Resolving   #11113 
This updates NewPCT to show the year between parentheses on the title.

NewPCT: Show the year between parentheses on the title

---

README.md
src/Jackett.Common/Content/custom.js
src/Jackett.Common/Utils/FilterFunc.cs
src/Jackett.Common/Utils/FilterFuncs/TestFilterFunc.cs
src/Jackett.Test/Common/Utils/FilterFuncs/IndexerBaseStub.cs
src/Jackett.Test/Common/Utils/FilterFuncs/LanguageFuncTests.cs
src/Jackett.Test/Common/Utils/FilterFuncs/TagFuncTests.cs
src/Jackett.Test/Common/Utils/FilterFuncs/TestFuncTests.cs
src/Jackett.Test/Common/Utils/FilterFuncs/TypeFuncTests.cs

[feature] Indexer Test status filter

---

src/Jackett.Common/Content/custom.js
src/Jackett.Common/Content/index.html

Add a checkbox column to the add indexers datatable which allows multiple selection of public indexers to add at one time.

Add the ability to select multiple public indexers at one time.

---

src/Jackett.Common/Indexers/NewPCT.cs

Some internet providers are blocking the connection to this indexer. With this new link the connection is allowed without the need for a proxy or vpn to the indexer

Added new link to NewPCT indexer

---

README.md
src/Jackett.Common/Definitions/animeworld.yml
src/Jackett.Common/Services/IndexerManagerService.cs

animeworld.cx changed their source to unit3d, with this commit the jackett integration is working again.
They also had ast4u as their old trackername, but i removed those references as they now require a new registration and old accounts are not working anymore
I have one question though, they have a categorie for Anime Movies, which I mapped to "TV/Anime" (as it was on the old animeworld.yml), but is this okay or should this be mapped to "Movies"?
Thanks

Update animeworld.cx to new source

---

src/Jackett.Common/Indexers/NewPCT.cs

Fix for #11841
The download url page does not include js function with download link:
https://maxitorrent.com/descargar/serie/fbi/temporada-3/capitulo-11/hdtv/
The torrent download url has to be extracted from https://maxitorrent.com/descargar/torrent/serie/fbi/temporada-3/capitulo-11/hdtv/

newpct: fixed 404 torrent download url. resolves: #11841

---

src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs
src/Jackett.Common/Indexers/Orpheus.cs

Resolves https://github.com/Jackett/Jackett/issues/9860
Resolves https://github.com/Jackett/Jackett/issues/11543
Resolves https://github.com/Jackett/Jackett/issues/11728
This PR supports Orpheus long-standing issue of supporting API token, which I was supposed to implement last year.
It should resolve most issues related to using cookies.
**Note**: `usePassKey` and 2FA is not required when using API Tokens to download torrents, but you might want to merge https://github.com/Jackett/Jackett/pull/11815 first as it supports `usePassKey` for future trackers that may encounter a similar scenario. I will rebase once when the PR has been merged.

orpheus: added api token support

---

src/Jackett.Common/Indexers/Orpheus.cs

@garfield69 @ilike2burnthing 
https://github.com/Jackett/Jackett/pull/11868 was merged before I had completed the rebase. This includes the rebase that I was supposed to include in the previous PR.
note that `has2Fa` is ineffective when `useApiKey` toggle is turned on, so we will leave it as `false`.

orpheus: fixed api toggle

---

src/Jackett.Common/Definitions/gay-torrents.yml
src/Jackett.Common/Definitions/gay-torrentsorg.yml

Adding additional functionality (sort/order, filters for freeleech/active/dead, etc)

Update definitions for gay-torrents.net & gay-torrents.org

---

src/Jackett.Common/Definitions/audiobookbay.yml
src/Jackett.Common/Definitions/ibit.yml
src/Jackett.Common/Definitions/isohunt2.yml
src/Jackett.Common/Definitions/movietorrent.yml
src/Jackett.Common/Definitions/mypornclub.yml
src/Jackett.Common/Definitions/nitro.yml
src/Jackett.Common/Definitions/torrentmax.yml
src/Jackett.Common/Definitions/torrentproject2.yml
src/Jackett.Common/Definitions/torrentsir.yml
src/Jackett.Common/Definitions/torrentwhiz.yml
src/Jackett.Common/Definitions/unlimitz.yml
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Models/IndexerDefinition.cs

This is a follow-up on https://github.com/Jackett/Jackett/pull/11907
This PR moves filters in to be defined individually for each selector.
Example code:
```yaml
selectors:
- selector: a[href^="download.php?id="]
attribute: href
filters:
- name: querystring
args: url
- name: urldecode
- selector: a[href^="magnet:"]
filters:
- name: tolower
```
The first selector's filter will apply `querystring` and `urldecode`. The second selector's filter will apply `tolower`

core: modified filters for selectors

---

src/Jackett.Common/Definitions/arenabg.yml
src/Jackett.Common/Definitions/badasstorrents.yml
src/Jackett.Common/Definitions/limetorrents.yml
src/Jackett.Common/Definitions/torrentdownloads.yml

Follow up to https://github.com/Jackett/Jackett/issues/11865 and https://github.com/Jackett/Jackett/pull/11907
limetorrents and torrentsdownload only have itorrents.org and magnet, so removed `We suggest using the magnet link as a fallback.` as it's redundant.
arenabg and badasstorrents use their own torrents and are unlikely to fail with any regularity, so reworded the info section to work with this.

assorted: add fallback DL

---

src/Jackett.Common/Definitions/torlock.yml
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Models/IndexerDefinition.cs

This is an attempt to resolve https://github.com/Jackett/Jackett/issues/6256. Still needs more testing and feedback before merging.
You can test it out with the following indexer
<details><summary>test6256.yml</summary>
```yaml
---
id: test6256
name: test6256
description: "testing path category mappings"
language: en-us
type: public
encoding: UTF-8
links:
- https://www.torlock.com/
- https://www.torlock2.com/
legacylinks:
- https://torlock.com/
caps:
categorymappings:
- {id: TELEVISION, cat: TV, desc: "TV Shows"}
- {id: MOVIES, cat: Movies, desc: "Movies"}
- {id: MUSIC, cat: Audio, desc: "Music"}
- {id: GAMES, cat: PC/Games, desc: "Games"}
- {id: SOFTWARE, cat: PC, desc: "Software"}
- {id: ANIME, cat: TV/Anime, desc: "Anime"}
- {id: EBOOKS, cat: Books/EBook, desc: "Books"}
- {id: OTHER, …
```

core: fixed category mapping for searchPaths

---

src/Jackett.Common/Definitions/lesaloon.yml

Right now, if loginbutton doesn't have value "XZ", your ip will be ban for few minute.

[lesaloon]: Fix login issue

---

README.md
src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/IIndexer.cs
src/Jackett.Common/Services/CacheService.cs
src/Jackett.Common/Services/Interfaces/ICacheService.cs
src/Jackett.Common/Utils/FilterFunc.cs
src/Jackett.Common/Utils/FilterFuncs/StatusFilterFunc.cs
src/Jackett.Test/Common/Utils/FilterFuncs/IndexerBaseStub.cs
src/Jackett.Test/Common/Utils/FilterFuncs/StatusFuncTests.cs

Draft solution for #3292
The status will be
- `status:healthy`: the last request/test completed successfully. Status expires in 10 minutes.
- `status:failing`: last request/test failed. The status expires in min(1second * 2^retry, 24h)
- `status:unknown`: the status expired
All the reqest than generate an error are counting as failed request (network, parsing, login)

[feature] Indexer status

---

src/Jackett.Common/Definitions/yggcookie.yml
src/Jackett.Common/Definitions/yggtorrent.yml

Hello,
I made a change into the config file of Yggtorrent indexer. When we make a search for example "Boruto Naruto next generations 196", it find nothing but if we search "Boruto Naruto next generations E196", it shows results. So i made simple replace into keywords before searching.

Fix search yggtorrent when anime ending by number without 'e'

---

src/Jackett.Common/Indexers/EraiRaws.cs

Erai-Raws looks to have published the new RSS feed now. This re-adds the URLs for the main site. I've left the beta site as an option for now as it is still working but I'm happy to move to legacy links if preferred.
I also re-added the nocensor site link but was unable to test it due to cloudflare restrictions (I don't have flaresolver set up atm). It seems to be just a proxy though with identical content so should work. It required the `FollowIfRedirect` change but I'm not sure if this is a result of cloudflare or nocensor.

Switch Erai-Raws back to main site

---

src/Jackett.Common/Models/ReleaseInfo.cs

Fixes #12241.
As mentioned in the issue, except for the last instance of dot character, all are removed. 
I didn't go with my replace all commas with dots logic because of the following reason:
1,024 MB should be 1024 MB but with this, it could've become 1.024 MB which would be disastrous.
The first logic is working for the variation of the size mentioned in the issue but needs actual testing with all the indexers.

Better Size Parsing for Cardigann Indexer

---

src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Models/IndexerDefinition.cs

Fixes #12273.
1. I've added a pathselector field in the before block with all the parameters. This fixes the mircrew indexer which I'll create a separate pull. Following is the excerpt taken from it:
```yml
download:
before:
pathselector:
selector: a[id^="lnk_thanks_post"]
attribute: href
selectors:
- selector: a[href^="magnet:?xt="]
attribute: href
filters:
- name: trim
```
2. I've made some appropriate naming changes in the IndexerDefinition.
3. I've fixed a bug where the before block would cause trouble when Inputs field is not present (like in the case of mircrew).

[Cardigann] Add path selector in before block and few fixes

---

src/Jackett.Common/Definitions/anime-free.yml
src/Jackett.Common/Definitions/hellastz.yml
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Models/IndexerDefinition.cs

Adds on to the Fix of #11865.
There is a new option named "testlinktorrent" which is by default true. On setting it to false, it skips the check essentially preventing 2 GET requests to download a torrent file for the indexers which don't like that behaviour.
I've also made the necessary change to hellastz indexer but needs testing since I don't have creds. 
On approval, I'll add it to the wiki and merge changes

[Core] Add option to prevent torrent link check

---

src/Jackett.Common/Indexers/CardigannIndexer.cs

Fixes #12314.
As mentioned in the issue, there are multiple redirects which I also noticed in the network logs. However, traditionally the Cardigann indexer only takes care of one redirect. I've added an option to control it (from c# only, not yml) and have set a maximum of 5 redirects allowed. Again, I don't know how it could've been working earlier because from the start only 1 redirect was handled.

[Core] Enable multiple redirects

---

src/Jackett.Common/Services/CacheService.cs

`Encoding.ASCII` will replace all non ASCII characters with '?'
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.ascii

Fix cache collision for non ASCII characters

---

README.md
src/Jackett.Common/Indexers/Partis.cs

Partis.si indexer was removed in https://github.com/Jackett/Jackett/commit/e86eda9ea3dfee9e078296ca08f9a7ef818566fa because tracker was unavailable since March 2021. Website has now been rebuilt and I have managed to reuse the majority of previous indexer implementation. 
Changes:
- Urls for login, logout, search and torrent download
- Username and password fields in login request
- Json is now returned and HTML parsing is not needed anymore
There are also some issues with the new indexer:
- No way to identify freeleech torrents from a single request. Indexer would have to make another request for each hit in search results
- Number of grabs is currently displayed on a 0-100 scale. I could not find a way to get the total number
This PR fixes https://github.com/Jackett/Jackett/issues/1596

[New Tracker] Fix Partis indexer to work with new website

---

src/Jackett.Common/Indexers/Partis.cs

Partis.si has changed login response which caused ConfigureIfOK() to not detect successful logins. Instead of logout link we now check for udata cookie, which is only returned on successful login. Generic error is returned on failed login - same as on website.
Fixes #12558

Fix Partis login check

---

src/Jackett.Common/Indexers/BJShare.cs

The tracker is now using reCaptcha on every login, so switching to cookie based login will fix it.
Also added "E" prefix to animes episodes with absolute numbering, fix the One Piece episodes > 1000 detection on Sonarr.
Fixes #12756

BJ-Share: use cookie login method. resolves #12756

---

src/Jackett.Common/Indexers/SceneHD.cs

This PR updates the certificate thumbprint used for SceneHD. They updated their cert today at around 2000GMT I believe.

Fix SceneHD certificate thumbprint

---

src/Jackett.Common/Definitions/arabp2p.yml
src/Jackett.Common/Definitions/bigfangroup.yml
src/Jackett.Common/Definitions/bitsexy.yml
src/Jackett.Common/Definitions/bluesbrothers.yml
src/Jackett.Common/Definitions/eniahd.yml
src/Jackett.Common/Definitions/finelite.yml
src/Jackett.Common/Definitions/hqsource.yml
src/Jackett.Common/Definitions/rintor.yml
src/Jackett.Common/Definitions/sktorrent-org.yml
src/Jackett.Common/Definitions/theleachzone.yml
src/Jackett.Common/Definitions/torlook.yml
src/Jackett.Common/Definitions/torrentoyunindir.yml
src/Jackett.Common/Definitions/wdt.yml
src/Jackett.Common/Definitions/zomb.yml

Looking a second pair of eyes because it's a bit of a mix of indexers and solutions, but all for the same problem. See if I've missed a better fix somewhere.
**arabp2p** - Site only uses 'any words' search, no way I can see to force 'all words' - no site setting, prepending words with `+` is ignored, surrounding words or whole phrase with `"` returns no results, replacing whitespaces with `.` is ignored.
**bigfangroup** - Site seems to ignore keywords with 3 characters or fewer, no way I can see to change it - no site setting, prepending words with `+` is ignored, surrounding words with `"` returns no results, surrounding whole phrase with `"` uses 'whole phrase' search, replacing whitespaces with `.` is ignored.
**bitsexy** - Site's 'search help' lies, prepending with `+` does not make a …

assorted: remove unrelated results

---

src/Jackett.Common/Definitions/rintornet.yml

The only other indexer I could find that this will work with (though I didn't look all that hard, just searched for the word `forget`).
Don't know if we want to expand it like this or not, where slight changes to cat names will require an indexer update, but thought I'd make the PR all the same.

rintornet: use fields categorydesc for cat detection

---

src/Jackett.Common/Content/custom.js
src/Jackett.Common/Content/index.html

Hello everyone,
This PR just adds a small _Copy API key to clipboard_ button right next to the API key.
This uses the function copyToClipboard that's already in custom.js and that triggers that nice green success notification.
If for some reason the API key is not set then it wont copy anything to the clipboard.
I also invalidated the cache for custom.js in index.html by putting today's date.
Please find below some screenshots:

[Feature] Copy API key to clipboard button

---

src/Jackett.Server/Controllers/ServerConfigurationController.cs

https://github.com/Jackett/Jackett/pull/12882#issuecomment-1024712443
Tested, but worth a second look.
The original version of #12882 was tested and worked fine, but my last minute change to use `uri.Scheme` wasn't and didn't.

webui: fix baseurloverride

---

src/Jackett.Common/Indexers/IPTorrents.cs
src/Jackett.Common/Models/IndexerConfig/ConfigurationDataCookieCaptcha.cs
src/Jackett.Common/Models/IndexerConfig/ConfigurationDataCookieUA.cs

Recently I noticed that Jackett had stopped working for me.  After some research I noticed that it was simply from a security measure that had been put in place.  This added a field to the cookie and required the user agent to be the same.  Many other sites have been doing the same so I updated the code for IPTorrents to simply do the same.

IPTorrents fixes for Cloudflare

---

src/Jackett.Common/Definitions/tasmanit.yml

Tasmanit.es certificate expired on 24 Jan 2022

Add certificate hash for tasmanit.es

---

src/Jackett.Common/Definitions/opencd.yml

* Some categories are missing in opencd.yml.
* Old torrents don't have album covers and the links are like `details.php?id=xxx&hit=1`.
Without this update, I get 96 results from Jackett. (I've set the page size to 100 on the website.)
With this update, I get 100 results from Jackett.

OpenCD: Update category and title matching

---

src/Jackett.Common/Definitions/rutracker-ru.yml
src/Jackett.Common/Indexers/RuTracker.cs

Hello, today I was surprised by a closure of the registration of rutracker.org, rutracker.nl, etc, and temporarily no new users can be registered, so I change the type of the site from public (semi-private) to private.
All the best.

[RuTracker] Change public (semi-private) to private

---

src/Jackett.Common/Definitions/tasmanit.yml

for some reason my previous change from https://github.com/Jackett/Jackett/pull/12955 was changed in 5584438a949bf8081752467c4d075a96049921fe by @garfield69
The tracker still needs to have custom DNS/host to be accessed, and still has the thumbprint i added in my previous PR.
In order not to break what @garfield69 added, i just re-added the thumbprint that's working for me.

re-Add certificate hash for tasmanit.es

---

src/Jackett.Common/Indexers/MoreThanTV.cs

MoreThanTV's most recent update (04/01/2022) changed the browse URL and the layout. This fixes both issues.

morethantv: update scraper to use torrents/browse endpoint

---

src/Jackett.Common/Definitions/hdspain.yml

Convert some tags to better manage of PROPER edited files, and packs with multiple files.

Transform MEGAPACK and AUDIOEDITADO tags to PROPER

---

src/Jackett.Common/Services/UpdateService.cs
src/Jackett.Server/Jackett.Server.csproj
src/Jackett.Server/Services/FilePermissionService.cs

Avoids problems documented in issue #13080.
It seems like the two libraries are essentially API-compatible, and it certainly didn't cause any problems in this case. Mono.Posix is seeing active development, whereas Mono.Posix.NETStandard is deprecated. Only slight downside is that it is pre-release — but just barely, and should be stable soon.

Use Mono.Posix package instead of Mono.Posix.NETStandard package

---

src/Jackett.Common/Definitions/torrent9.yml

Hello 👋 , thank you for this project, it's really cool!
- Torrent9 slightly modified their markups and added a new table
cell which shifts the rest.
This is the new markup for a result
```html
<tr>
<td>
<i class="fa fa-tv" style="color:#404040"></i>
<a title="Lupin Saison 1 FRENCH HDTV" href="/torrent/76158/lupin-saison-1-french-hdtv" style="color:#000; font-size:12px; font-weight:bold;"><h3><span class="blue">Lupin</span> Saison 1 FRENCH HDTV</h3></a>
</td>
<td style="font-size:12px">14/01/2021</td>
<td style="font-size:12px">1.6Go</td>
<td style="font-size:13px;text-align:right; padding-right:5px">
<span class="seed_ok">2264 <img class="hidden-md" src="/Public/images/up.png"></span>
</td>
<td style="font-size:13px;text-align:right; padding-right:5px">573 <img class="hidden-md" …
```

Fix torrent9 selectors:

---

src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/Meta/BaseMetaIndexer.cs

Not tested!
@cadatoiva I need your knowledge. Take a look at #8531 first. The query object is shared across all indexers. Ideally I want to make that object immutable or readonly so it can't be modified after creation. If one tracker, like BakaBT, tries to change some attribute it must fail (not compile ideally).
I don't know how to do that so in this PR I'm cloning the object before running the tasks. This should work but I'm not comfortable because maybe I forget some usage more.
Update: #8531 was fixed in #8666 but this PR is still need to avoid future problems in other indexers.

core: immutable query. resolves #8531

---

src/Jackett.Common/Definitions/bitturk.yml
src/Jackett.Common/Definitions/btnext.yml
src/Jackett.Common/Definitions/torrent-turk.yml
src/Jackett.Common/Definitions/turktorrent.yml
src/Jackett.Common/Definitions/vizuk.yml

`at` is required for fuzzytime in `Yesterday at 14:22` or `Monday at 14:22`
@garfield69 I only have access to bitturk of these, so if you could check the 3 you have accounts for to make sure there's nothing else needing done for this.

assorted tsue: fuzzytime date fix

---

Installer.iss
azure-pipelines.yml

Currently, Jackett's installer appends a `.0` in Programs and Features Entries in Control Panel. This change fixes it so that it doesn't append a revision version to it.
For example: 
Jackett's version is `0.20.1010`, but in the control panel, it shows `0.20.1010.0`.
From now onwards, both will be the same.

Inno setup: pass MyAppVersion as a parameter

---

.github/workflows/winget.yml

This workflow automatically generates and publishes Jackett's releases to WinGet (windows package manager).

Publish release to winget

---

README.md
src/Jackett.Common/Indexers/Aro.cs

Commits may need to be squashed.

add aro.lol a Serbian/English anime site

---

README.md
src/Jackett.Common/Indexers/MejorTorrent.cs

Updated MejorTorrent so it works with https://mejortorrent.wtf
Improvements:
- Better TV-HD parsing.
- Movies now include year.
- Documentaries included as TV or TV/HD.
- Search in first 25 pages of the indexer instead of only the first one.
Fixes #12559

[Fix] Updated MejorTorrent

---

src/Jackett.Common/Definitions/bitbr.yml

This make sure that all words with \bDUAL\b are replaced by pt-BR/en-US even though en-US may not be the origin language, but this should at least allow sonarr/radarr to find movies dubbed in portuguese.

fix: bitbr rename title in order to try and have better language matchings

---

src/Jackett.Common/Definitions/lemonhd.yml

@Uzibird @horseytr @hoong7 @tuningman9790 @finikium @skygunner @tjxme we want to add searching by Douban ID, but this needs tested as none of the maintainers have an account.
Please download this test build from [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6188/artifacts?artifactName=drop&api-version=7.0&%24format=zip), extract the version for your system, and install over your current install (if you're using Docker, you'll need to test this natively instead, e.g. on a Windows computer, and add LemonHD).
To test that searching by Douban ID is working, use the links below, changing the address if needed, and replace `YOURAPIKEY` with your Jackett API key.
TV search for The Mandalorian: …

lemonhd: add doubanid search

---

yamllint.yml

fixes line ending errors when linting on windows
commit is LF
local repo checked out is CRLF
yamllint default expects LF...this makes it systembased

update yamllint to allow linting on windows

---

src/Jackett.Common/Jackett.Common.csproj

- Fix the error: The cookies provided by FlareSolverr are not valid
- Allow FlareSolverr timeouts > 100 s
- Fix vulnerabilities

Bump FlareSolverrSharp 2.2.5

---

src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
src/Jackett.Common/Utils/CookieUtil.cs
src/Jackett.Test/Common/Utils/CookieUtilTests.cs

- Max number of cookies per domain is just 20 by default -> now 100
- When the indexer domain changes, old cookies where kept in memory

Increase the number of cookies per domain and remove old cookies

---

src/Jackett.Common/Jackett.Common.csproj

- Fixes the error: Unsupported POST Content-Type: application/x-www-form-urlencoded

core: bump FlareSolverrSharp 2.2.6

---

src/Jackett.Common/Definitions/lat-team-api.yml

Solve 'Exception (lat-team-api): Error while parsing field=category, selector=category_id, value=22: Object reference not set to an instance of an object.: Error while parsing field=category, selector=category_id, value=22: Object reference not set to an instance of an object.'

solve Lat-Team (API) exception

---

src/Jackett.Common/Indexers/BakaBT.cs

Closes #13447 
Added XXX versions of all categories, to mirror those listed on website.
This allows distinguishing between content, such as an `OVA` from a `Hentai OVA`.
For categories that start with `Anime`, replaced with `Hentai`:
- Anime Series -> Hentai Series
- Anime Movie -> Hentai Movie

BakaBT: Separate Adult Categories

---

src/Jackett.Common/Definitions/yggcookie.yml
src/Jackett.Common/Definitions/yggtorrent.yml

The yggtorrent configuration quotes every word in order to prevent exact match phrase search (see #11101)
The idea was to add quotes arround each word (ex `Daemon slayer` => `"Daemon" "Slayer")
But the regex wasn´t enough permissive and titles like `Stargate SG-1` was transformed into `"Stargate" "SG"-"1"` which gave an empty result.

[tracker fix] Fix yggtorrent exact match search

---

src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs
src/Jackett.Common/Indexers/AvistaZ.cs
src/Jackett.Common/Indexers/CinemaZ.cs
src/Jackett.Common/Indexers/PrivateHD.cs

Does not provide `tags` in API results.

avistaztracker: add genre search support

---

src/Jackett.Common/Definitions/karagarga.yml

@RoloSoze @cinico-gmail @duramato @dmucli @Norin-Radd @grocovid @fim
We want to bring this indexer up to date with others, but this needs tested as none of the maintainers have an account.
Please download this test build from [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6492/artifacts?artifactName=drop&api-version=7.0&%24format=zip), extract the version for your system, and install over your current install (if you're using Docker, you'll need to test this natively instead, e.g. on a Windows computer, and add Karagarga).
To test that this is working, right-click the `Copy RSS Feed` button for Karagarga in Jackett and open in a new tab. Right-click this page and save it as a text document.
Remove any personal information from the document, …

karagarga: rework genre and description

---

.github/workflows/winget.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

src/Jackett.Common/Indexers/BitHDTV.cs

Fix html table parsing. The table structure changed so no results of any searches.
Removed #needseed since the torrents table can be identified by id.
Fixes: https://github.com/Jackett/Jackett/issues/10097#issuecomment-1157331160

Fix always no results of BitHDTV indexer

---

src/Jackett.Common/Definitions/pterclub.yml

1. If the torrent is a game, the link is `/detailsgame.php?id=`, currently, the title is showing the comment counts
2. remove `font` tag on description due to empty IMDB and DOUBAN, causing `N/AN/A` in description
3. remove `b` tag on description in order to remove the word `[热门]` completely

pterclub: fix title and description on game search

---

src/Jackett.Common/Definitions/polishtracker-api.yml

it looks like there is issue with this param in PTE API, no matter if it is true or false, as long it is present it works the same and once present it affects serch result, most relevant search results are not necessary at the beggining of the reponse often not event at the first page and because of this indexer often do not return valid results at all, when there is no wide param in input but nfo remains sometimes it does not return valid response as well

polishtracker-api removed wide and nfo params from input

---

src/Jackett.Common/Definitions/polishtracker-api.yml

Additional setting for releases with multi-language audio (MULTI in release name). By default Sonarr/Radarr recognize these releases as English, but in truth should be treated as Polish. With this setting checked, at the end of the release title, the POLISH word will be added, so Sonarr/Radarr will know that this release has polish audio. It's a similar setting as in the previous polishtracker definition.

polishtracker-api: added additional setting for polish language (useful with Sonarr/Radarr)

---

src/Jackett.Common/Indexers/ShizaProject.cs

Some torrents only had magnet links. This was causing an error which should be fixed now.
Solves Issue: #13578

Fix: ShizaProject Null File

---

src/Jackett.Common/Indexers/BaseIndexer.cs

While working on Issue #13591, I noticed that magnet links are being generated as a part of redirect when we click on Download button. This is not supported by the base indexer as it tries to follow the redirect and fails when it doesn't recognize the "magnet" scheme.
It will be great if this pull can be tested on all the possible Cardigann indexers to make sure it doesn't break anything.
Once approved, I'll make a pull tor resolve #13591 too based on these changes.

Base Indexer: Recognize Magnet Links in Redirects from Download Link

---

src/Jackett.Common/Definitions/pornotorrent.yml

With this fix, the download links in Jackett should resolve and redirect to a magnet link.
Solves #13591

Fix: Pornotorrent Redirect to Magnet Link

---

src/Jackett.Common/Definitions/dark-shadow.yml
src/Jackett.Common/Definitions/torrent-explosiv.yml

They don't have the same issue as fixed in e891be739f85d3fca599495f6c9706ee565ae8ae, but the trackers are using `_ssl`.

torrent-explosiv & dark-shadow: use ssl download

---

src/Jackett.Common/Definitions/uhdbits.yml

This pull request makes UHDbits search results more conformant to scene standards so that the arr apps can properly parse out fields.
It fixes the ability for arr apps to properly recognize:
- release group names
- Blu-Ray Encodes
- Blu-Ray Disk Rips
- Blue-Ray Remuxes
- The 4k variants of the above

UHDBits Scene Naming Convention Regexes

---

src/Jackett.Common/Content/custom.js
src/Jackett.Common/Content/index.html

Resolves #13619.
The logic is a little different than mentioned in the issue.
Here is the equivalence comparison.
`+(x265 hevc)` = `+x265|hevc` = Filters out the results that contain either HEVC or x265 in the torrent name.
`-(x265 hevc)` = `-x265|hev` = Filters out the results that contain neither HEVC nor x265 in the torrent name.
The pipe operator is less likely to occur in a torrent name and saves some coding time for detecting enclosing bracket and pair and then splitting on the space, hence I thought this was better as well as more native to the Regex Logic.

UI: Add OR Filter in Table Search

---

install_service_macos
uninstall_jackett_macos

Updates some legacy launchctl commands and adds a very short delay before installer checks whether agent was successfully launched

Fixing macOS agent installs

---

README.md

It's the correct version, as seen in OSX/Linux

README: Update Windows .NET SDK version to 6

---

src/Jackett.Common/Indexers/RuTracker.cs

fix for https://github.com/Jackett/Jackett/pull/13661#issuecomment-1286567697

rutracker: no regex replace when SearchTerm is null. #13660

---

src/Jackett.Common/Definitions/lat-team-api.yml

Previously, the S01E01 part of a query would get changed to T01E01 which made it impossible to find TV shows from the tracker.
Searching for Generic Show S01E01 resulted in a API query that included Generic Show T01E01. Consequently, Jackett was not finding any TV show from the tracker.
I tested it locally and now it works as intended.
Other changes include:
- Update the minimum seeding time according to the tracker rules
- Remove minimum ratio as the minimum seeding time is mandatory despite of ratio

Fix Lat-Team Definition to find TV Shows

---

src/Jackett.Common/Definitions/btdigg.yml
src/Jackett.Common/Definitions/demonoid.yml
src/Jackett.Common/Definitions/thepiratebay.yml

.pet is dead and .ws is using an expired cert
added tor2web.to

assorted: update onion proxies

---

src/Jackett.Common/Definitions/anthelion-api.yml

It seems to be a new field `releaseGroup` in the response, so it's useful for CF scores and blocking LQ groups, etc.
Also fixed the media for WEB releases to prevent false positive as scene.

anthelion-api: append release group to title and fix media `WEB`

---

README.md
src/Jackett.Common/Indexers/Libble.cs

Hello,
It seems like adding `keeplogged=1` extends the cookie `session` from session to lifetime of 1 year. 👍

[libble] Extend login cookie TTL

---

src/Jackett.Common/Definitions/digitalcore.yml
src/Jackett.Common/Definitions/hawke-uno.yml

Hi,
Currently these two return a lot of useless results when searching for a single episode, and it can be quite annoying sometimes when searching for a series with a lot of seasons and episodes.
For hawke-uno I moved the params from `path` to `inputs` to be consistent with other UNIT3D based trackers.

digitalcore/hawke-uno: Fix searching by season/episode

---

src/Jackett.Common/Definitions/abtorrents.yml

Remove "[REQUESTED]" from title and avoid redirect for details URL.

abtorrents: Fixes for naming and details link

---

jackett_launcher.sh

Currently, in the launcher script the whoami and updater loop are masking the exit code of Jackett. So even if Jackett errors out, the systemd service sees an exit code of "0", which e.g. breaks the `Restart=on-failure` in the [non-mono service template](https://github.com/Jackett/Jackett/wiki/Systemd-service#not-using-mono).
This commit stores the exit code of Jackett in a variable and exits the script explicitly with this exit code, after the updater has been waited for. This way `Restart=on-failure` again can apply and `systemctl status jackett` reports the correct status if Jackett failed.
_________
Somehow related question. When an update is applied, I see now this:
```
Dec 28 07:41:05 VM-Bullseye Jackett[1478]: 12-28 07:41:05 Info File copying complete
Dec 28 07:41:05 VM-Bullseye …
```

Do not mask Jackett exit code in launcher

---

src/Jackett.Common/Definitions/thesceneplace.yml

I tested a lot of weird names and groups, and seemed to work okay beside this one.

thesceneplace: fix the apostrophe

---

azure-pipelines.yml

The complete pipeline runs 1-2 minutes faster.

ci/cd: speed up unit & integration tests

---

src/Jackett.Common/Jackett.Common.csproj

* Detect Cloudflare blocked pages
* Works better with FlareSolverr 3.0.2

core: update FlareSolverrSharp 3.0.4

---

src/Jackett.Common/Definitions/pier720.yml

A fellow user tried this change and they confirmed it fixed the issue with the cookies being valid only for the first query.

720pier: add user-agent to fix expired session issue

---

src/Jackett.Common/Definitions/sharewood.yml

- moved VOSTFR replacing first to prevent issues when `Replace MULTI by this language` is set to `VOSTFR` in the end becoming `ENGLISH`.
- use word boundary instead of spacing
- use negative lookahead to replace `MULTI` only if isn't followed by `FRENCH`, `ENGLISH` or `VOSTFR`. (this includes `TRUEFRENCH`)

sharewood: improve title

---

src/Jackett.Common/Indexers/MyAnonamouse.cs
src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataMyAnonamouse.cs

I'm porting some of my changes from Prowlarr.
- added selectable search type (default `all`)
- added `Search in narrator` by default to match their default search on the site
- added `Search text in the description` (default `false`)
- added `Search text in the series` (default `false`)
- added `Search text in the filenames` (default `false`)
- added support for multiple authors, maximum 5.
- show filetype in uppercase
- ~~check for freeleech vip only torrents if the user has class `VIP`or `Elite VIP`~~
TODO: 
- ~~cache `HasUserVipAsync` response for at least one hour. Suggestions/example welcome here.~~
- ~~Jackett requires `ToLocalTime()`? Seems fine without in webui.~~

myanonamouse: add selectable search type, show max 5 authors

---

src/Jackett.Common/Indexers/HDSpace.cs
src/Jackett.Common/Indexers/HDTorrents.cs
src/Jackett.Common/Indexers/ImmortalSeed.cs
src/Jackett.Common/Indexers/SceneTime.cs
src/Jackett.Common/Indexers/XSpeeds.cs

- use `ParseUtil.GetArgumentFromQueryString()` instead of `Split` (there a few more, but I can't test or find out what's the name of param)
- use [NameValueCollection.Set()](https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection.set?view=net-6.0#remarks)
- use `WebUtility.HtmlDecode()` for titles taken from download links
- ignore the hardcoded timezone in HDTS
- ST: use the date added before falling back to elapsed time, and change encoding to UTF-8 to match both header and meta `content-type` charset.

assorted: use GetArgumentFromQueryString and other minor fixes

---

src/Jackett.Common/Indexers/FileList.cs
src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataFileList.cs

Added `Freeleech` setting and removed `IncludeRomanianReleases` since it wasn't used anywhere.
One caveat, ATM `freeleech=1` only works with `search-torrents`. I hope they add support to `latest-torrents` in the future.

filelist: add freeleech setting

---

src/Jackett.Common/Definitions/cloudtorrents.yml

Apparently they block Prowlarr's User Agent, but not Jackett's. So it's up to you if you'll like to accept this change, if not I'll push just to `prowlarr/indexers`.
Also the timezone seems off, I'm above minus 300 minutes for the latest release. I couldn't figure it out since they didn't released anything in the last hour.

cloudtorrents: add fake user-agent to bypass blocking

---

src/Jackett.Common/Indexers/SpeedCD.cs
src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataSpeedCD.cs

I didn't get any errors while changing the `configData` implementation. Is there anything special to do when you're changing the implementation of the configuration?
Added also a fix when searching season and only episodes are available by adding wildcard. For testing search `tt0412253 S03` before and after.

speedcd: add freeleech only, exclude archives and fix TZ

---

src/Jackett.Common/Definitions/bitspyder.yml

Add category filtering. It's spamming my Lidarr logs because it can't find eligible audio results.
Also since they give very bad results, I was thinking of adding since they support it:
```yaml
keywordsfilters:
- name: re_replace
args: ["(\\w+)", "+$1"] # prepend + to each word
```

bitspyder: fix category filtering and improve term search

---

src/Jackett.Common/Indexers/RuTracker.cs
src/Jackett.Common/Indexers/Toloka.cs
src/Jackett.Test/Common/Indexers/RuTracker/RuTrackerTests.cs
src/Jackett.Test/Common/Indexers/Toloka/TolokaTests.cs

List of indexers with `Split('=')` usage:

toloka/rutracker: improve parsing and parsing titles

---

src/Jackett.Common/Definitions/ourbits.yml

Hey, I'm sysop for site `ourbits`.
from old commit `3f7f4b0` to current commit `e71117f`, We update our search engines and many searchparams sign changed. 
for example:
- `&cat401=1` (no other category in filter) changed to `&cat=401` (retained from the past) or `&cat[]=401`
- `&cat401=1&cat402=1` (more than two category in filter) changed to `&cat[]=401&cat[]=402`
---
We also introduce our jsonapi (though it's no stable in current time), You can find in [ourbits/docs](https://github.com/ourbits/docs#31-%E7%A7%8D%E5%AD%90%E6%90%9C%E7%B4%A2) (in chinese)
here is example
```bash
curl 'https://xxxxxxx.club/jsonapi.php?action=torrent/search&search=<search_text>&cat[]=401&<other_search_params>' \
-H 'cookie: ourbits_jwt=........' \
```

ourbits: update inputs for category

---

src/Jackett.Common/Indexers/Shazbat.cs
src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataShazbat.cs
src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataSpeedCD.cs

Caveats:
- only the first 5 results will be fetched (`show` returns 39 items for example)
- publish date for torrents isn't present on show page so I'm using a default a month ago.
- using `show_mode` to fix a weird bug when the tab selected is not the torrents list, which is not the complete page thus `ReloginIfNecessary` needed updated.
- setting requestDelay to 5.1s to offer some grace, since they seem strict about their RSS TTL at 15 minutes.
- added `Show Pages Fetch Limit` config to limit the number of pages fetched when searching.

shazbat: refactor search and parsing

---

src/Jackett.Common/Indexers/Shazbat.cs

Fixing a regression from yesterday deleting the whole string when it shouldn't.

shazbat: remove just the year/air date

---

src/Jackett.Common/Definitions/1337x.yml
src/Jackett.Common/Definitions/badasstorrents.yml
src/Jackett.Common/Definitions/bitsearch.yml
src/Jackett.Common/Definitions/bulltorrent.yml
src/Jackett.Common/Definitions/demonoid.yml
src/Jackett.Common/Definitions/extratorrent-st.yml
src/Jackett.Common/Definitions/eztv.yml
src/Jackett.Common/Definitions/filelisting.yml
src/Jackett.Common/Definitions/gktorrent.yml
src/Jackett.Common/Definitions/glodls.yml
src/Jackett.Common/Definitions/ilcorsaronero.yml
src/Jackett.Common/Definitions/limetorrents.yml
src/Jackett.Common/Definitions/nyaasi.yml
src/Jackett.Common/Definitions/rutor.yml
src/Jackett.Common/Definitions/tokyotosho.yml
src/Jackett.Common/Definitions/torlock.yml
src/Jackett.Common/Definitions/torrent9clone.yml
src/Jackett.Common/Definitions/torrentdownload.yml
src/Jackett.Common/Definitions/torrentdownloads.yml
src/Jackett.Common/Definitions/torrentfunk.yml
src/Jackett.Common/Definitions/torrentz2nz.yml
src/Jackett.Common/Definitions/yourbittorrent.yml
src/Jackett.Common/Definitions/yts.yml
src/Jackett.Common/Definitions/zetorrents.yml
src/Jackett.Common/Indexers/EraiRaws.cs
src/Jackett.Common/Indexers/SubsPlease.cs

From the same [overall source](https://unblocksource.nl/torrent-proxy.php), but restores access to those removed in https://github.com/Jackett/Jackett/commit/b6e29968335ce8b56556f854c04819b4dd440d02.

assorted: replace nocensor proxies with mrunblock

---

README.md
src/Jackett.Common/Definitions/ebookbay.yml

This is one very weird wordpress, the divs are not nested one element so some entries don't have descriptions or a download .torrent link (just for checking, magnets are used since the download torrent are sent via some weird redirect site blocked by ublock).

ebookbay: add a public torrent tracker

---

src/Jackett.Common/Definitions/anilibria.yml

Replaces #14020.
Updated to v3 API - fixes posters, adds magnets and description.
Checks if movie, uses the added Movies cat.
@alikhanz given that we're building the title anyway, I think this is a better solution. Give it a test.
@garfield69 / @mynameisbogdan is there a way to make the below (or something like it) work?:
```yml
title_alternative_notru:
selector: ..names.alternative:not(:contains([А-Яа-яЁё]))
optional: true
```

anilibria: update to v3 api, add strip russian & add rus settings

---

src/Jackett.Common/Definitions/losslessclub.yml

Current search results with windows-1251:
Search results in build with UTF-8:
Also i'm writed Dockerfile for local development. I don't know if you need it or not, but for me it's really comfortable.

lossless: change encoding to UTF-8

---

src/Jackett.Common/Definitions/hd4fans.yml
src/Jackett.Common/Definitions/schema.json
src/Jackett.Common/Indexers/BaseIndexer.cs
src/Jackett.Common/Indexers/CardigannIndexer.cs
src/Jackett.Common/Models/IndexerDefinition.cs

Apparently the login part of cardigann doesn't use the custom headers (like User-Agent) from `search.headers`, sending the auth requests with Jackett's User-Agent. 
This PR is trying to allow custom headers in login and download blocks, while inheriting `search.headers` if not set.

cardigann: custom headers in login and download

---

src/Jackett.Common/Extensions/StringExtensions.cs
src/Jackett.Common/Models/TorznabQuery.cs

hellashut is just for practice, even though prepending `+` to Greek words breaks the search.
you can use `το σοι σου` and `ΤΟ ΣΟΙ ΣΟΥ` for testing.
* fixes #7673

torznabquery: allow accents in split regex

---

src/Jackett.Common/Definitions/hellashut.yml

@ilike2burnthing I suggest removing this since their search doesn't work with Greek words with `+` in front anyways.

hellashut: remove prepending + to word

---

src/Jackett.Common/Definitions/kinozal.yml

https://github.com/Prowlarr/Prowlarr/issues/1391
Now it works because Jackett is executing `DoLogin` on setup regardless of `CheckIfLoginIsNeeded`, but this affects Jackett too if the session expires.

kinozal: fix login test

---

src/Jackett.Common/Definitions/1337x.yml

This prevents indexer from failing test when added to Readarr

1337x: Add cat/Other to default paths for ebooks

---

src/Jackett.Common/Indexers/NebulanceAPI.cs

Related #6413
This indexer is built around tvmaze, so let's use it when possible. 
Also replacing everything that's not a word with `%` to include all special chars.
@garfield69 try `t=tvsearch&tvmazeid=11968&season=2020&ep=07/22`
Any objections against adding support for TvmazeId?

nebulance: add tvmaze support

---

src/Jackett.Server/Jackett.Server.csproj

Using Visual Studio 2022 I was getting a lot of wrong/false positive errors like this:
```
Error	NU1201	Project Jackett.Server is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Project Jackett.Server does not support any target frameworks.	Jackett.Test ...\Jackett\src\Jackett.Test\Jackett.Test.csproj	1	
Error	NU1201	Project Jackett.Server is not compatible with net462 (.NETFramework,Version=v4.6.2). Project Jackett.Server does not support any target frameworks.	Jackett.Test	...\Jackett\src\Jackett.Test\Jackett.Test.csproj	1	
Error	NU1201	Project Jackett.Server is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Project Jackett.Server does not support any target frameworks.	Jackett.Test	...\Jackett\src\Jackett.Test\Jackett.Test.csproj	1	
Error	NU1201	Project Jackett.Server is …
```

fix building in Visual Studio 2022

---

src/Jackett.Common/Definitions/hddolby.yml
src/Jackett.Common/Definitions/hdu.yml
src/Jackett.Common/Definitions/nethd.yml
src/Jackett.Common/Definitions/oshenpt.yml
src/Jackett.Common/Definitions/spidertk.yml

I didn't test, since I don't have accounts for these.

assorted: enable ssl/trackerssl for nexusphp-based definitions

---

src/Jackett.Common/Utils/ParseUtil.cs

can I do this here to avoid my VS2022 from flagging a null reference during debugging?

Update ParseUtil.cs to avoid null references

---

src/Jackett.Common/Definitions/amigosshare.yml
src/Jackett.Common/Definitions/anime-free.yml
src/Jackett.Common/Definitions/beyond-hd.yml
src/Jackett.Common/Definitions/bibliotik.yml
src/Jackett.Common/Definitions/byrutor.yml
src/Jackett.Common/Definitions/extremlymtorrents.yml
src/Jackett.Common/Definitions/femdomcult.yml
src/Jackett.Common/Definitions/nipponsei.yml
src/Jackett.Common/Definitions/parnuxi.yml
src/Jackett.Common/Definitions/sktorrent.yml
src/Jackett.Common/Definitions/thefallingangels.yml
src/Jackett.Common/Definitions/torrent9.yml
src/Jackett.Common/Definitions/tribalmixes.yml

A few more. Double-check in case there's a reason not use `default:` with any of them.
Also tidied extremlymtorrents and removed unnecessary optional poster from sktorrent.
Only remaining indexers with `_optional:` fields are:
- 1337x & torrent9 - `title` https://github.com/Jackett/Jackett/commit/0f9f173cc5c691dacb2e633991eee01f856c0cc7
- nyaasi - `download` https://github.com/Jackett/Jackett/commit/80691060ea030e869084209b63285061a3f06da8
- torrenthr - 2 optional `title` fields and a default, all different selectors
puntotorrent has a `title_vose:` field which serves the same function, but different filters are being applied to `_default` and `_vose`.

assorted yml: use default: statement for optional fields

---

src/Jackett.Common/Definitions/hdgalaktik.yml
src/Jackett.Common/Definitions/riperam.yml
src/Jackett.Common/Definitions/torrentland.yml
src/Jackett.Common/Indexers/CardigannIndexer.cs

Follow up to https://github.com/Jackett/Jackett/commit/d762bbd616289d0aa6b2253e0128364f83f4728e.
Do we remove `noappend` from CardigannIndexer and/or the schema?

assorted: change remaining noappend to default

---

src/Jackett.Common/Indexers/AniDUB.cs
src/Jackett.Common/Indexers/LostFilm.cs
src/Jackett.Common/Indexers/TorrentHeaven.cs

Follow up to https://github.com/Jackett/Jackett/pull/14235. Forgot about C# indexers.
Also added another LostFilm mirror. *tv1.site exists too, but fails with parsing errors.

assorted C#: removed old cert exceptions

---

src/Jackett.Common/Definitions/yggcookie.yml
src/Jackett.Common/Definitions/yggtorrent.yml

Addresses https://github.com/Prowlarr/Indexers/issues/55 as much as possible, multi-cat search isn't available.
Selecting a sub-category other than `Tous` will remove category from search to avoid conflict.

yggtorrent: add sub-category setting & tidy

---

src/Jackett.Common/Definitions/yggcookie.yml
src/Jackett.Common/Definitions/yggtorrent.yml

Removes old category setting and the new sub-cat setting from https://github.com/Jackett/Jackett/pull/14248 earlier.
Closest thing to addressing https://github.com/Prowlarr/Indexers/issues/55 other than performing a separate search for every selected sub-category.
See info note:
> To avoid unnecessary additional requests, it's recommended to only use indexer-specific categories (>=100000) when configuring this indexer in Sonarr, Radarr, and Lidarr, or when manually searching in TV, Movies, and Audio categories.

yggtorrent: search by category 

---

src/Jackett.Common/Definitions/torrentleech.yml

ref #13772 
reverts #14046
if the proper 2fa works then lets keep it. The bypass code was an early fix which we did not install in time because C# ;-b
_Originally posted by @garfield69 in https://github.com/Jackett/Jackett/issues/14046#issuecomment-1436133124_
The bypass code is a TL thing, not c#.  2FA works, but provides a poor experience.
Swap to the bypass key given if the creds expire for any reason then the user experience is poor as the user must then go and manually re-configure the tracker with a fresh token.   the bypass key TL provides for all 2FA users should negate this and also meets the original request of #13772.

torrentleech - replace 2FA with alt2FAToken

---

src/Jackett.Common/Indexers/GazelleGamesAPI.cs

Fixes parser error outlined in #13544 
If the result includes games without torrents, the Torrents property on group has value of ```[]``` which is not accepted by the JObject.FromObject on line 248.

Fix GGN API empty result

---

src/Jackett.Common/Definitions/torrentgalaxy.yml

This adds another mirror for Torrent Galaxy, as per https://torrentgalaxy.org/.
The other mirrors listed there are not accessible for me (ISP block) so this extra mirror would be useful for me and others in my position.
N/A
N/A

Add Torrent Galaxy mirror

---

src/Jackett.Common/Indexers/CardigannIndexer.cs

Reopen #14610
Description
Reuse the same cookie during the relogin step to eliminate the necessity for two requests to flaresolverr; a single request will suffice.

Flaresolverr one request needed, not two

---

.github/workflows/winget.yml

Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.

winget: change job runner to `ubuntu-latest`

---

src/Jackett.Common/Indexers/SceneHD.cs

This PR updates the certificate thumbprint used for SceneHD. I believe they updated their cert as a result of a server move that took place in the last couple of days (20-21 August 2023).

Use new certificate thumbprint for SceneHD.

---

.github/workflows/winget.yml

Delay before running winget-releaser action, as discussed in the linked issue.
* Fixes #13948

Delay 5 minutes before running winget-releaser

---

src/Jackett.Common/Definitions/torrentleech-pl.yml

This tracker add [PACK] prefix to all season packs and sonarr can't process it correctly.

Remove [PACK] prefix from season packs

---

src/Jackett.Common/Definitions/torrentmasters.yml

Turns out it wasn't a quick fix...
There's a few guesses here (I thiiiiiink MR and freeleech are gone, ~as well as any kind of dl/ulvf modifiers~ - I'll message staff), but the main issue is that I'm getting a site error page when trying to download in Jackett, but not in browser:
```html
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Ocelot::addUser() must be of the type int, null given, called in /home/torrentmasters/sites/torrentmasters.info/www/download.php on line 34 and defined in /home/torrentmasters/sites/torrentmasters.info/www/include/classes/class_ocelot.php:8
Stack trace:
#0 /home/torrentmasters/sites/torrentmasters.info/www/download.php(34): Ocelot::addUser()
#1 {main}
thrown in <b>/home/torrentmasters/sites/torrentmasters.info/www/include/classes/class_o …
```

torrentmasters: update layout

---

src/Jackett.Common/Definitions/piratbit.yml
src/Jackett.Common/Definitions/piratbitl.yml

Jackett's Linux UA causes Cloudflare challenge and 404 page, so switch to Windows UA. Add requestDelay to hopefully avoid further blocks.
Failed login causes captcha challenge, so switch piratbitl to cookie and UA.
* Fixes #XXXX

piratbit: switch to cookie & UA login, use Windows UA to avoid block

---

README.md
src/Jackett.Common/Definitions/animetorrentsro.yml

`Anime Torrents Romania` took up too much room in the results table.
* Fixes #14781

animetorrentsro: add Romanian private tracker. resolves #14781

---

install_service_systemd.sh

Prevents .NET runtimes from creating debugging fifos/sockets in `/tmp` (which are not necessary for normal operation)
Partial fix for https://github.com/Jackett/Jackett/issues/14774
https://learn.microsoft.com/en-us/dotnet/core/runtime-config/debugging-profiling
https://github.com/dotnet/runtime/issues/7204#issuecomment-723204695

Prevent .NET runtime from creating debugging fifos/sockets in /tmp

---

src/Jackett.Common/Definitions/anilibria.yml
src/Jackett.Common/Definitions/animetime.yml
src/Jackett.Common/Definitions/bangumi-moe.yml
src/Jackett.Common/Definitions/danishbytes-api.yml
src/Jackett.Common/Definitions/digitalcore.yml
src/Jackett.Common/Definitions/hebits.yml
src/Jackett.Common/Definitions/milkie.yml
src/Jackett.Common/Definitions/nipponsei.yml
src/Jackett.Common/Definitions/showrss.yml
src/Jackett.Common/Definitions/superbits.yml
src/Jackett.Common/Definitions/torrentleech.yml
src/Jackett.Common/Definitions/torrentmasters.yml
src/Jackett.Common/Definitions/torrentz2eu.yml
src/Jackett.Common/Definitions/yggcookie.yml
src/Jackett.Common/Definitions/yggtorrent.yml

Assuming this is intentional:
- a leading `/` uses search path domain, e.g. `https://www.example.com/` (i.e. the sitelink, unless search path is different, e.g. `https://api.example.com/`)
- no leading `/` uses full search path, e.g. `https://www.example.com/search/path/`
Remaining uses for `.Config.sitelink` in results fields are API indexers for which the search path differs from sitelink - anilibria, xthor, polishtracker, tpb/apibay.
Confirmed working in Prowlarr too.
* Fixes #XXXX

assorted: simplify use of sitelink for results fields

---

README.md
src/Jackett.Common/Definitions/makingoff.yml

Alternatively, indexer could use title-only search and not have to use andmatch filter, but it loses a lot of information, like many other forum-based indexers.
* Fixes #14834

makingoff: add new Brazilian private tracker. resolves #14834

---

README.md
src/Jackett.Common/Definitions/torrentdd.yml

Only problem is with `{{ range .Categories }}{{.}},{{end}}` as this is leaving a trailing `,` which breaks the search. This also happens with aidoruonline, both before and after 1e310ad09660f0d351a2be8453d72ab0ed1b2822, but the trailing `,` doesn't break the search for that indexer.
Replacing the `,` with `&` resolves the trailing character issue, but obviously still breaks the search.
Not sure what exactly, but I'm assuming it's something to do with:
https://github.com/Jackett/Jackett/blob/1e310ad09660f0d351a2be8453d72ab0ed1b2822/src/Jackett.Common/Indexers/CardigannIndexer.cs#L465-L500
In lieu of an immediate fix, adding `{{ if .Categories }}0{{ else }}{{ end }}` to the end of the `cate` input fixes it, but it's a plaster for the actual issue.
* Fixes #14873

torrentdd: add private Thai tracker. resolves #14873

---

README.md
src/Jackett.Common/Definitions/fsm.yml

API returns `filePath` for the torrent link, but can't get it to work. Have asked on their forum if there's a way to do it, without having to manually build the link and using the passkey as well. Will update indexer if/when I get an answer.
Presumably the method of getting an API token will need to be updated in the future as well.
* Fixes #14887

fsm: add Chinese private tracker. resolves #14887

---

src/Jackett.Common/Indexers/DonTorrent.cs

The new DonTorrent domain is: https://dontorrent.yokohama/
Changed as DonTorrent has a new domain now.
TG snapshot from official channel there.

DonTorrent new domain 23.01.2024

---

src/Jackett.Common/Models/DTO/ApiSearch.cs
src/Jackett.Server/Controllers/ResultsController.cs

As discussed here https://github.com/Jackett/Jackett/issues/15009 the params for json response only works with a few params.
Implemented so IMDBID, TVDBID, TVMAZEID and TMDBID params are supported with the API json response
* Fixes #XXXX
IMDBID -tested with valid, invalid id
TVDBID - tested with valid, invalid id
TMDBID - tested with valid, invalid id
TVMAZEID - uanble to test as the only site i know that uses tvmaze is BIThdtv but its not a supported param for the site. ```http://localhost:9117/api/v2.0/indexers/bithdtv/results/torznab/api?apikey=<API_KEY>&t=caps```
I will add the other params that is supported by torznab once i know know this will be merged. 
Note if the site does not support the search param that the latest torrents are returned but that is the same behavior as …

Use params IMDBID, TVDBID, TVMAZEID and TMDBID with json response

---

src/Jackett.Common/Definitions/torrent-heaven.yml

Torrent Heaven changed the download url.
Before: download.php?id=
Now: downloadv1.php?id=
This wil update the Definition.
* Fixes #XXXX

Update torrent-heaven.yml: new download url

---

src/Jackett.Common/Indexers/IPTorrents.cs

Official mirror list is:
https://ipt.cool
https://ipt.world
https://ipt.lol
https://ip.findnemo.net
https://ip.getcrazy.me
https://ip.venom.global
https://ip.workisboring.net
https://AnyName.octopus.town
Removed any other, as may not be authorized or legitimate, and may expose user credentials. https://ipt.world/topic.php?t=3005848

Corrected IPTorrents mirror list

---

src/Jackett.Common/Definitions/yts.yml

As per the yify status & proxies website, these are the only ones which are correct YTS sites. Though. I have kept the yts.unblockit.dad as it is the only other one which seems to be leading to the same certificates as the other yify sites. Moved rest all to legacy links section.
Also, added a section for status & proxy links for future referencing. Please let me know or place it correctly in the file as needed, but keep those 2 links there (status & proxies).

Yify sites, proxies, status links updated

---

src/Jackett.Common/Indexers/NebulanceAPI.cs

Currently searching nebulance.io by resolution (1080p, 2160p,...) returns no results because resolution should be sent as tags, not as part of name. This PR fixes that.

[enhancement] Move resolution search terms from name to tags in json (nebulance.io)

---

src/Jackett.Common/Jackett.Common.csproj
src/Jackett.Common/Models/Config/ServerConfig.cs
src/Jackett.Common/Utils/Clients/HttpWebClient.cs
src/Jackett.Common/Utils/Clients/HttpWebClient2.cs

Temporarily changed to `FlareSolverrSharp-fork` for sake of testing. Will need to merge https://github.com/FlareSolverr/FlareSolverrSharp/pull/25 first and then revert back to `FlareSolverrSharp` with a version bump.
SOCKS4 doesn't support authentication, and Chromium doesn't support SOCKS5 authentication, so it's just HTTP to test here. If you don't have an HTTP proxy with credentials readily available to test, I just used https://www.webshare.io and registered using https://temp-mail.org
Make edits or suggestions.
* Fixes #15099

flaresolverr: support proxy auth. resolves #15099

---

README.md
src/Jackett.Common/Definitions/azusa.yml
src/Jackett.Common/Definitions/beitai.yml
src/Jackett.Common/Definitions/dajiao.yml
src/Jackett.Common/Definitions/freefarm.yml
src/Jackett.Common/Definitions/gamera.yml
src/Jackett.Common/Definitions/haitang.yml
src/Jackett.Common/Definitions/haresclub.yml
src/Jackett.Common/Definitions/hdc.yml
src/Jackett.Common/Definitions/hdmayi.yml
src/Jackett.Common/Definitions/hdpt.yml
src/Jackett.Common/Definitions/icc2022.yml
src/Jackett.Common/Definitions/kufei.yml
src/Jackett.Common/Definitions/pignetwork.yml
src/Jackett.Common/Definitions/ptcafe.yml
src/Jackett.Common/Definitions/ptchina.yml
src/Jackett.Common/Definitions/pterclub.yml
src/Jackett.Common/Definitions/ptitzmx.yml
src/Jackett.Common/Definitions/ptsbao.yml
src/Jackett.Common/Definitions/putao.yml
src/Jackett.Common/Definitions/redleaves.yml
src/Jackett.Common/Definitions/shadowflow.yml
src/Jackett.Common/Definitions/soulvoice.yml
src/Jackett.Common/Definitions/tjupt.yml
src/Jackett.Common/Definitions/wukong.yml
src/Jackett.Common/Definitions/ydypt.yml

Given most people using the indexers will be Chinese, include Chinese name. However, as Jackett is currently only available in English, use English name first (exception being ptitzmx, as there isn't an English name, itzmx is just taken from the domain).
Some other minor description fixes.
* Fixes #XXXX

assorted nexusphp: add Chinese names

---

src/Jackett.Common/Definitions/schema.json

Can't also require download/infohash/magnet in download block because of [arabtorrents](https://github.com/Jackett/Jackett/blob/2be98aecab78ef02dc6d31122eb1a131556db540/src/Jackett.Common/Definitions/arabtorrents.yml#L143-L148), [hdsky](https://github.com/Jackett/Jackett/blob/2be98aecab78ef02dc6d31122eb1a131556db540/src/Jackett.Common/Definitions/hdsky.yml#L60-L61), and [romanianmetaltorrents](https://github.com/Jackett/Jackett/blob/2be98aecab78ef02dc6d31122eb1a131556db540/src/Jackett.Common/Definitions/romanianmetaltorrents.yml#L98-L104).
Can't require date as audionews and demonoid take it from rows dateheaders instead, and `.Result.dateheaders` is not supported.
Date was missing from [wihd](https://github.com/Jackett/Jackett/commit/e421300dae616620789685dfe106926fc6349527).
* Fixes …

schema: require size, one of category/categorydesc, any of download/infohash/magnet

---

src/Jackett.Common/Indexers/SubsPlease.cs

Some shows on Subsplease have a season numbering in theirs show title,
for exemple
* https://subsplease.org/shows/shin-no-nakama-s2/
* https://subsplease.org/shows/tsuki-ga-michibiku-isekai-douchuu-s2/
for theses releases Subplease indexer struggle to find results,
at least from a sonarr point of view as it request "show_title S0x" instead of "show_title Sx"
Current Behaviour 
```
2024-03-20 14:44:42	Info	Manual search in SubsPlease for the daily life S4 => Found 36 releases [153ms]
2024-03-20 14:44:36	Info	Manual search in SubsPlease for the daily life S04 => Found 0 releases [308ms]
```
New Behaviour 
``` 
2024-03-20 13:53:37 Info Manual search in SubsPlease for the daily life S04 => Found 36 releases [1094ms]
2024-03-20 13:53:43 Info Manual search in SubsPlease for the daily life S4 => …
```

[Subplease] Fix no results for show with season in their show title

---

src/Jackett.Common/Definitions/anilibria.yml

Added the option to enable season number parsing for better compatibility with Sonarr.
Edgecases are taken from dozens of the most problematic titles found at random.
In addition, several problems with non-standard release classifications have been fixed. (Recaps, specials, etc.)
(I have no experience with this Cardigann, so that the approach may be suboptimal. The concept of calling this regex hell a "simple indexer" makes me glee.)
May be related to #10973

[Feature] Option to enable season number parsing for Anilibria

---

src/Jackett.Common/Definitions/0daykiev.yml

Fix category mapping for 0day.kiev tracker.
Fixes:
- Cartoons are mapped to Movies instead of TV
- Documentary is mapped to Movies instead of TV

Fix categories for 0daykiev.yml

---

src/Jackett.Common/Definitions/mazepa.yml

Fix categories for Mazepa torrent tracker
- Cartoons (мультфільми) are now `Movies/QUALITY`
- Cartoon series are now `TV/QUALITY`
Now we use `TV/Anime` only for Anime category, like it should be.

Fix mazepa.yml categories

---

src/Jackett.Common/Definitions/huntorrent.yml

Skip the extra click for downloading the torrent file.
An intermediate page was introduced while downloading torrent file, but that page can be skipped if the URL does not contains the `please_wait=1` argument.
This PR provides a way to remove it from the URL, I know it could be solved with `before` option as well, and likely that is more stable solution (as relies on not URL editing).
Disclaimer I have only tried it with prowlarr (sorry), but that uses the same configuration file.
I haven't opened an issue for this.

huntorrent: skip extra page before torrent file

---

src/Jackett.Common/Indexers/Feeds/BaseNewznabIndexer.cs
src/Jackett.Common/Indexers/Feeds/MoreThanTVAPI.cs

MTV uses the BaseFeedIndexer. So now imdb, tvdb and tvmaze IDs gets added to MTV releases.

Add imdb, tvdb and tvmaze to feed base release

---

src/Jackett.Server/Services/ServerService.cs

Recently, an "external access" warning was introduced, and @garfield69 implemented a button to dismiss the warning. As [pointed out here](https://github.com/Jackett/Jackett/issues/15066#issuecomment-1953129520), it is the user's responsibility to understand and accept the consequences of ignoring said warning.
In the same light, I would like to introduce a way to dismiss the warning about running with root privileges. The user has been warned of the risks and they should be able to dismiss the warning under their responsibility.

Add option to disable root privileges nag

---

src/Jackett.Common/Definitions/pttime.yml

PTTime increased its rate limie, so we need increase requestDelay.
it raised a `System.Exception: Remote server returned TooManyRequests` in logs with current config.

[PTTime]: increase `requestDelay`

---

src/Jackett.Common/Indexers/Wolfmax4K.cs

When searching with multiple word in Wolfmax4K, no results were returned, as it didn't support spaces on the query string.
Changing spaces to `+` fixes the issue, and now multiple words can be used to search with this tracker.

[Fix] Allow to search multiple words in Wolfmax4K

---

src/Jackett.Common/Definitions/exitorrent-org.yml

Few days ago indexer changed all urls to dynamically generated with javascript.

[Indexer fix] exitorrent.org dynamic javacript download urls

---

src/Jackett.Common/Definitions/1337x.yml

Per official .so page:
Domain 1337x.so expired by mistake and is no longer controlled by us. Stop using this domain.
New alternative domain is https://x1337x.cc/

Updated new official homepage for 1337X

---

src/Jackett.Common/Definitions/totheglory.yml
src/Jackett.Common/Definitions/totheglory2fa.yml
src/Jackett.Common/Services/IndexerManagerService.cs
src/Jackett.Updater/Program.cs

2FA now seems to be on a separate page, so short of someone with an account rewriting in C#, change cookie indexer to 2FA. Obviously untested, but there's no `otp` input on the login page, and the log from #15412 shows the redirect to `2fa.php`.
@garfield69 look ok?
@mynameisbogdan a heads up for Prowlarr
Also added some comments to IndexerManagerService.
* Relates to #15412

totheglory: changes for 2fa

---

src/Jackett.Common/Indexers/Wolfmax4K.cs

Improves the parsing of seasons and episodes of series and the integration with sonarr/radarr
If no season/episde info found in guid, fallback to torrentName's "Cap." info
Caps longer than 4 digits are not supported. Anyway, I have not found any cases.
Eg: "091 Alerta Policia [HDTV 720p][Cap.601]" is S06E01
I have also improved the integration with sonarr and radarr, cleaning up redundant information from the title or qualities that do not parse well

wolfmax4k: improves the parsing of seasons and episodes of series

---

src/Jackett.Common/Definitions/postman.yml

Postman was having some issues before because the request it would end up creating was 
`http://tracker2.postman.i2p/?view=Main&search=&category=-1&orderby=1&lastactive=-1&lang=-1`, this caused postman to hang. This fixes it so that it creates a request like 
`http://tracker2.postman.i2p/index.php?view=Main&search=&category=-1&orderby=1&lastactive=-1&lang=-1`, and that makes it work as expected.

Fix postman root path

---

README.md

`install_service_systemd.sh` throws this error:
```
ERROR: The owner of Jackett directory is 'UNKNOWN'.
Please, change the owner with the command 'chown <user>:<user> -R "/opt/Jackett"'
The user <user> will be used to run Jackett.
```
but runing `sudo chown $(whoami):$(id -g) -R "/opt/Jackett"` and then re-running the install command deletes and overwrites the directory making the chown moot.
Is there any reason not to include this in the script? It worked for me

Add chown to linux install script

---

src/Jackett.Common/Definitions/zetorrents.yml

Change the zetorrents yml config to find the download link properly.
* Change download hash selector from selector: `a[href^="/get_torrent/"])` to selector: `a[href^="/download/"]`

[Indexer] Update zetorrents download hash selector for current indexer dom

---

src/Jackett.Common/Definitions/rutor.yml

6tor.org is an up-to-date IPv6-only address for Rutor and shouldn’t be in legacylinks.
See also http://6tor.org/torrent/472 or http://rutor.info/torrent/472.
n/a
n/a

rutor: 6tor.org is an up-to-date address

---

src/Jackett.Common/Definitions/xxxclub.yml

The website changed from using https://xxxclub.to/torrents/browse/all/query to https://xxxclub.to/torrents/search/all/query for searches.
https://xxxclub.to/torrents/browse now returns a "static" list based on categories selected.
* Fixes #15581

xxxclub: fix search path address

---

src/Jackett.Common/Definitions/locadora.yml

This change disables the use of filename as title by default and updates the tracker's description.
In addition to the release name we also add the audio language to the API, which allows our users to make better use of Profiles on Sonarr/Radarr. Showing the file name instead of the API response is not ideal for us.
Thank you

[Feature] Disable use of filename as title

---

src/Jackett.Common/Definitions/superbits.yml

They're currently having issues with their .org domain and recommend using the .cc one instead.

superbits: add alternative link

---

src/Jackett.Common/Definitions/aither-api.yml

Aither changed their timezone to UTC rather than EU/London. DST observation has thrown off release pubDates as a result
A little over a week ago, Aither changed their timezone to UTC rather than EU/London. This results in not observing DST, which was set in [this commit](https://github.com/Prowlarr/Indexers/commit/7f74ae3c20373f5fff75ef909d29872a14501eac)
Tracker statement below.
```We have changed our timezone to UTC a couple of days ago. Previously, we've had Europe/London as PHP timezone, but that includes DST which we actually do not want. Due to the time change, some releases within that 1-hour timeframe, seem to have been release in the future.```

aither: update timezone to utc to not observe dst

---

src/Jackett.Common/Definitions/seedpool-api.yml

Updates the seedpool indexer definition to fix searches.
- Remove unsupported `tvdbid` search parameter
- Remove unsupported `imdbid` search parameter
- Use correct search category for BoxSets (TV Season packs, not Movies)
These fixes have been tested by running jackett locally and performing searches against the seedpool api
I have read the the contributing guide, but this is the first patch I've submitted to Jackett, so I apologize in advance if I missed something. Willing to work or change things as needed to make sure this works :) 
* Fixes #15733

[Fix] remove unsupported search parameters from seedpool definition

---

src/Jackett.Common/Definitions/hdtorrentsit.yml
src/Jackett.Common/Definitions/oldtoonsworld.yml
src/Jackett.Common/Definitions/polishtorrent.yml
src/Jackett.Common/Definitions/tocashare.yml
src/Jackett.Common/Definitions/turkseed-api.yml
src/Jackett.Common/Definitions/uploadcx.yml
src/Jackett.Common/Definitions/utopia.yml
src/Jackett.Common/Definitions/yoinked.yml

Just makes it easier when searching for UNIT3D API indexers. Doesn't affect some older and custom UNIT3D trackers that don't support the API.
* Fixes #XXXX

assorted unit3d: add missing api to names

---

src/Jackett.Common/Definitions/postman.yml

Postman have introduced rate limiting. Can return:
- 503 Service unavailable
- timeout
- 'proceed' check button
PR bypasses the latter.
This fine remaining Public? No account is necessary, but couldn't find a way to do this without using 'login'.
Added a generous request delay to avoid us making the site load worse. Didn't add a login test for the same reason, but also because there's nothing really to check here.
* Fixes #XXXX

postman: bypass proceed page, add generous requestdelay

---

src/Jackett.Common/Definitions/nyaasi.yml

Sonarr is able to parse `[ZeroBuild] Attack on Titan Season 2 (BD 1080p HEVC 10-bit Opus) [Dual Audio] (Shingeki no Kyojin) (Eotena Onslaught)` but not `[ZeroBuild] Attack on Titan Season 2 S2 (BD 1080p HEVC 10-bit Opus) [Dual Audio] (Shingeki no Kyojin) (Eotena Onslaught)` as S2 makes the parser think the series title is `Attack on Titan Season 2`.

nyaasi: avoid double season info

---

src/Jackett.Common/Definitions/hdonly-api.yml
src/Jackett.Updater/Program.cs

Switching to API by using the `apikey` query parameter, generated from Access Settings.

hdonly: switch to API

---

.github/ISSUE_TEMPLATE/bug_report.yml

A lot of our issues are people not actually reading the wiki, despite saying they have, so we just end up linking them back to it.
I've taken this directly from the FlareSolverr repo, where I grew tired of people not reading and just ticking boxes, so I felt making them type `YES` was enough to make some actually go back and check, and allowed me to guilt-free put as much effort into closing and locking their issue, as they had put into opening it. I'm yet to actually have anyone type anything other than `YES`.
I have made the odd exception where someone clearly doesn't have a clue, or they appear not to speak English.
It may be a bit too blunt for here, so feel free to mellow it out a little 😉 (e.g. maybe it's not locked, but we add a new label `User needs to read Wiki` or something)

Add bug report input to weed out timewasters

---

README.md
src/Jackett.Common/Definitions/matrix.yml

This is my first new indexer definition. This tracker has no explicit software type attribution in the footer nor elsewhere in the `/browse.php` page source. The only software type reference I can find is `<script
src="https://matrixworld.info/js/tbdev_hun.js"></script>`, so TBDev is my best guess.  I started with a few of the most recently added and modified definitions tagged with `# TBDev...` at the bottom and copied one.
I modified it as seemed most correct supplemented with [the Prowlarr Cardigann YML Definition docs](https://wiki.servarr.com/en/prowlarr/cardigann-yml-definition) and various `$ git grep ...` searches for relevant bits. For things like the categories and sort fields, I copied the relevant HTML from the indexer web UI and transformed it with editor tools into the …

feat(matrix): Add Matrix Hungarian private tracker

---

src/Jackett.Common/Definitions/krazyzone.yml

KrazyZone does not support these lookups; confirmed in their shoutbox, and discussed at https://krazyzone.net/forums.php?action=viewtopic&topicid=351 and https://krazyzone.net/forums.php?action=viewtopic&topicid=476
* Fixes #16088

Remove IMDB, season, and episode from KrazyZone

---

src/Jackett.Common/Definitions/seedpool-api.yml

Seedpool is reorganizing its categories, this update will match the new category configuration on the tracker. 
Used https://github.com/Jackett/Jackett/wiki/Jackett-Categories as reference for category names
I re-ordered the category list to match the tracker order for easier updates in the future :) 
There are some SP categories that now map to multiple Jackett categories. I believe I have set those correctly, but would appreciate a pair of eyes on that to confirm that the mappings are valid for Jackett. For example, the Music Production category (id 21) is going to have a mix of PC/Audio/Other. I believe I am able to do this mapping, but would like confirmation that its actually valid :) 
Many thanks!

seedpool:  category mapping updates

---

src/Jackett.Common/Definitions/newheaven.yml

Currently the seeders/leechers show up as `0/100` due to incorrect matching.
This PR makes use of the links ending in `#seeders` and `#leechers`.
There's no open issue for that afaik.

fix: match correct seeders and leechers

---

src/Jackett.Common/Definitions/darkpeers.yml

Updates darkpeers definition for compatibility with Unit3D 9.1.6

darkpeers -> 9.1.6 info_hash removed

---

src/Jackett.Common/Definitions/exttorrents.yml

Exttorrents allows keyword search alongside imdbid. Currently the indexer queries either by imdbid or keywords, never both together. This makes it unable to search for specific TV episodes for example.
This PR restores the ability to provide both imdbid and keywords (S01, S01E01, etc) in the search.

exttorrents: Restore keyword search alongside imdbid

---

src/Jackett.Common/Definitions/hhd-api.yml

You must keep a ratio of at least 0.4 otherwise your download privileges will be revoked. Your buffer at the top of the page shows how much you can download without falling below 0.4.
* Fixes #XXXX

[Update] HHD Add minimum ratio

---

src/Jackett.Common/Definitions/rastastugan-api.yml

You are required to seed all torrents to a 1:1 ratio or for at least 2 days (48 hours) before removing them from your client .
* Fixes #XXXX

[Update] Rastastugan minimum seedtime
