Jackett/Jackett

- src/Jackett/Indexers/MoreThanTV.cs
MoreThanTV Decode Response to fix issue
https://github.com/zone117x/Jackett/issues/235
> MoreThanTV Decode Response

- README.md
> Add Ubuntu install instructions

- src/Jackett/Content/index.html
I've got a loading issue yesterday and noticed that this alt tag was missing. Trivial but good for accessibility.
> Trivial update on index.html

- src/Jackett/Indexers/nCore.cs
nCore: Add category capabilities and mapping
Full credit to @gurabli
> nCore: Add category capabilities and mapping

- Installer.iss
Update AppURL to https://github.com/Jackett/Jackett
> Installer Config: Update AppURL

- src/Website/Controllers/AdminController.cs
- src/Website/Controllers/HomeController.cs
> Comment Out Missing Views

- src/Jackett.Console/Jackett.Console.csproj
- src/Jackett.Console/packages.config
- src/Jackett.Distribution/Jackett.Distribution.csproj
- src/Jackett.Distribution/packages.config
- src/Jackett.Service/Jackett.Service.csproj
- src/Jackett.Service/packages.config
- src/Jackett.Test/Jackett.Test.csproj
- src/Jackett.Test/packages.config
- src/Jackett.Tray/Jackett.Tray.csproj
- src/Jackett.Tray/packages.config
- src/Jackett/Jackett.csproj
- src/Jackett/packages.config
- src/Website/Website.csproj
- src/Website/packages.config
> Update NUGET Packages

- src/Jackett/Indexers/BeyondHD.cs
BeyondHD: Add ReCaptcha to fix issue
https://github.com/Jackett/Jackett/issues/35
> BeyondHD: Add ReCaptcha

- src/Jackett.Console/Properties/AssemblyInfo.cs
- src/Jackett.Distribution/Properties/AssemblyInfo.cs
- src/Jackett.Service/Properties/AssemblyInfo.cs
- src/Jackett.Test/Properties/AssemblyInfo.cs
- src/Jackett.Tray/Properties/AssemblyInfo.cs
- src/Jackett/Properties/AssemblyInfo.cs
- src/Website/Properties/AssemblyInfo.cs
Update Assembly Versions: Now using AppVeyor for versioning, so not
required
> Update Assembly Versions

- src/Jackett/Indexers/BlueTigers.cs
> BlueTigers Category Mapping

- src/Jackett/Indexers/BlueTigers.cs
> BlueTigers: GMT Time

- src/Jackett/Indexers/BlueTigers.cs
Blue Tigers: Fix Category URL Parameter
> Blue Tigers: Fix Category URL Parameter

- src/Jackett/Indexers/MoreThanTV.cs
> MoreThanTV: Fix season search

- src/Jackett/Services/UpdateService.cs
> Debug Mono AutoUpdater

- src/Jackett/Services/UpdateService.cs
> MonoDebug2

- src/Jackett/Services/UpdateService.cs
> Revert "MonoDebug2"

- src/Jackett/Services/UpdateService.cs
> Revert "Debug Mono AutoUpdater"

- src/Jackett/Services/UpdateService.cs
> Autoupdater: Mono fix

- src/Jackett.Test/Jackett.Test.csproj
- src/Jackett.Test/Util/TvCategoryParserTests.cs
- src/Jackett/Jackett.csproj
- src/Jackett/Utils/TvCategoryParser.cs
Can Determine Torznab TV show category from title if tracker doesn't
supply a category
> Tv Category Parser

- src/Jackett/Indexers/Freshon.cs
-Add Tv Categories
-Incorrect time was being returned
> FreshOn: Add Tv Categories and Fix Time

- README.md
- src/Jackett.Console/ConsoleOptions.cs
- src/Jackett.Console/Program.cs
- src/Jackett/CurlHelper.cs
- src/Jackett/Startup.cs
Linux: Ignore SSL certificate errors option added
> Linux: Ignore SSL certificate errors option added

- src/Jackett/Indexers/SpeedCD.cs
> SpeedCD- Change login URL

- src/Jackett/Indexers/SpeedCD.cs
Url for speed.cd indexers was'nt working anymore.
> Speed.cd - login url fix

- src/Jackett/Indexers/Hounddawgs.cs
Run with "--IgnoreSslErrors true"
> Hounddawgs working againg

- src/Jackett/Indexers/SpeedCD.cs
> Speed.Cd: Add categories

- src/Jackett/Indexers/IPTorrents.cs
> IPTorrents: Fix Url

- src/Jackett/Indexers/WiHD.cs
- src/Jackett/Models/IndexerConfig/Bespoke/ConfigurationDataWiHD.cs
> WiHD is a French High Private Tracker
Working as well, ready for using in a production environment.
> Changes
> Fixes
> This provider is part of the French Private Tracker's ROADMAP:
* Available at https://github.com/Jackett/Jackett/issues/145
**Enjoy this provider for Jackett,**
JigSaw
> WiHD Provider ~ Improved

- src/Jackett/Content/index.html
- src/Jackett/Content/login.html
This is so the UI will work behind a reverse proxy.
Fixes #146
> Changed resource paths to be relative

- src/Jackett/Indexers/Fnt.cs
> FNT is a French Private Tracker
Working as well, ready for using in a production environment.
> Changes
> Fixes
> Requested from:
* Issue https://github.com/Jackett/Jackett/issues/155
> This provider is part of the French Private Tracker's ROADMAP:
* Available at https://github.com/Jackett/Jackett/issues/145
**Enjoy this provider for Jackett,**
JigSaw
> FNT Provider ~ Download HOTFIX & SSL

- src/Jackett/Indexers/Demonoid.cs
Added movies category to demonoid - simple version, no subcats - all …qualities
> demonoid to support torrentPotato

- src/Jackett/Indexers/BlueTigers.cs
> Enable SSL on Bluetigers

- src/Jackett/Indexers/SpeedCD.cs
SpeedCD API no longer working, changed to parsing
> SpeedCd: Change API to parsing

- src/Jackett/Indexers/TorrentBytes.cs
TorrentBytes: Allow for missing category and fix time
> TorrentBytes: Allow for missing category and fix time

- src/Jackett/Indexers/SpeedCD.cs
> SpeedCd: Fix Query String

- src/Jackett/Content/index.html
- src/Jackett/Content/login.html
Multiple commits because editing on github directly doesn't seem to let you change multiple files at a time?
Fix for issue #217
> Switched favicon to relative URL

- src/Jackett/Services/ServerService.cs
URL Encode file names in proxy link
Issue https://github.com/Jackett/Jackett/issues/222
> URL Encode File Name

- src/Jackett/Content/custom.css
- src/Jackett/Models/IndexerConfig/ConfigurationDataBasicLogin.cs
Allow instructions on the basic indexer
> Allow instructions on the basic indexer

- src/Jackett/Indexers/Freshon.cs
Freshon: Changed parser to AngleSharp
> Freshon: Changed parser to AngleSharp

- src/Jackett/Indexers/Freshon.cs
> Revert "Freshon: Changed parser to AngleSharp"

- src/Jackett/Indexers/SceneTime.cs
Scenetime: Fix parsing as per
https://github.com/Jackett/Jackett/issues/231#issuecomment-180289081
> Scenetime: Fix parsing

- src/Jackett/Indexers/BitMeTV.cs
- src/Jackett/Models/IndexerConfig/ConfigurationDataCaptchaLogin.cs
BitMeTv: Add instructions to turn on SSL
> BitMeTv: Add instructions

- src/Jackett/Indexers/SceneTime.cs
SceneTime: Column numbers seem to be related to user settings, use
column names instead. Add category mapping support
https://github.com/Jackett/Jackett/issues/241
> SceneTime: Fix Column parsing

- src/Jackett/Indexers/SceneTime.cs
SceneTime: Add category mapping and fix search
https://github.com/Jackett/Jackett/issues/241
> SceneTime: Add category mapping and fix search

- src/Jackett/Indexers/ILoveTorrents.cs
Fixed a bug in the download link & added more categories.
> Fixed a bug in the download link.

- README.md
- src/Jackett/Indexers/ILoveTorrents.cs
> ILoveTorrents: Add to readme

- src/Jackett/Indexers/DanishBits.cs
> DanishBits: Fix publish time

- src/Jackett/Indexers/TehConnection.cs
- src/Jackett/Models/IndexerConfig/ConfigurationDataBasicLoginWithFilter.cs
TehConnection: Attempt to fix cookie expiration
https://github.com/Jackett/Jackett/issues/219
> TehConnection: Attempt to fix cookie expiration

- src/Jackett/Indexers/IPTorrents.cs
Fix IPTorrents url encoding
Issue https://github.com/Jackett/Jackett/issues/256
> Fix IPTorrents url encoding

- src/Jackett/Indexers/Freshon.cs
Freshon: Use AngleSharp for parsing
> Freshon: Use AngleSharp for parsing

- src/Jackett/Controllers/PotatoController.cs
- src/Jackett/Indexers/TehConnection.cs
- src/Jackett/Models/TorznabQuery.cs
TehConnection: Fix IMDB ID searches
> TehConnection: Fix IMDB ID searches

- src/Jackett/Indexers/Freshon.cs
Reverts Jackett/Jackett#273
Not working on some versions of mono
> Revert "Freshon: Use AngleSharp for parsing"

- src/Jackett/Indexers/PhxBit.cs
> Wrong TorzNab Category for Manga Anime
Now fixed.
JigSaw
> Fix Manga Anime Category for PhxBit Provider

- src/Jackett/Indexers/TransmitheNet.cs
> TTN: Update search url

- src/Jackett/Indexers/BitSoup.cs
- src/Jackett/Indexers/IPTorrents.cs
- src/Jackett/Jackett.csproj
- src/Jackett/Models/IndexerConfig/ConfigurationDataBasicLoginWithAlternateLink.cs
Added AlternateLink support from BitSoup (Issue #134) to IPTorrents indexer
> Added AlternateLink to IPTorrents

- src/Jackett/Indexers/FrenchADN.cs
> Fixed provider (Refactor due to changes on search engine page)
Fixed ISS. #335 
JigSaw
> Fixed FADN Provider

- src/CurlSharp/SSLFix.cs
- src/Jackett/CurlHelper.cs
- src/Jackett/Utils/Clients/HttpWebClient.cs
- src/Jackett/Utils/Clients/UnixSafeCurlWebClient.cs
> Revert "SSL Fix by default, Now use TLS (1.2, 1.1, 1) by default"

- src/Jackett/Indexers/AlphaRatio.cs
There was a bug in the alpharatio indexer where the username and password were not saved to the json file.
> Fixed saving alphaRatio json

- src/Jackett/Indexers/TorrentDay.cs
> TorrentDay: Add Audio

- src/Jackett/Indexers/SpeedCD.cs
> SpeedCD: Fix Login

- src/Jackett.Console/ConsoleOptions.cs
- src/Jackett.Console/Program.cs
- src/Jackett/Services/ConfigurationService.cs
- src/Jackett/Startup.cs
> Allow Custom Data Folder

- src/Jackett/Indexers/Freshon.cs
> Freshon: Fix Urls

- src/Jackett/Indexers/BeyondHD.cs
Updated BeyondHD to new URL to fix #385.
> Updated BeyondHD URL

- src/Jackett/Indexers/SpeedCD.cs
> SpeedCd: Update URL

- src/Jackett/Indexers/BeyondHD.cs
> BeyondHD; Fix Recaptcha

- src/Jackett/Indexers/TorrentLeech.cs
I'm testing this and seems to work. I've simply done the same modification as commit #354
> TorrentLeech: Fix login (#412)

- src/Jackett/Indexers/AnimeBytes.cs
Added the ability to search for music to the AnimeBytes indexer.
> Add music categories to AnimeBytes indexer

- src/Jackett/Indexers/IPTorrents.cs
> IPT: Update Parsing

- src/Jackett/Indexers/BlueTigers.cs
Bluetigers: Add category
https://github.com/Jackett/Jackett/issues/430
> Bluetigers: Add category

- src/Jackett/Indexers/Demonoid.cs
Demonoid: Fix Parsing
https://github.com/Jackett/Jackett/issues/365
> Demonoid: Fix Parsing

- src/Jackett/Indexers/TransmitheNet.cs
> TTN: Fix Parsing

- src/Jackett/Indexers/AnimeBytes.cs
> Animebytes: Fix warning

- src/Jackett/Indexers/TorrentLeech.cs
> TorrentLeech: Add setup info

- src/Jackett/Indexers/PrivateHD.cs
PrivateHd: Fix parsing
https://github.com/Jackett/Jackett/issues/461
> PrivateHd: Fix parsing

- src/Jackett/Controllers/PotatoController.cs
- src/Jackett/Indexers/TorrentDay.cs
TorrentDay: Add IMDB search
https://github.com/Jackett/Jackett/issues/463
> TorrentDay: Add IMDB search

- src/Jackett/Indexers/PrivateHD.cs
PrivateHD: Date Parsing
https://github.com/Jackett/Jackett/issues/461
> PrivateHD: Date Parsing

- src/Jackett/Indexers/AlphaRatio.cs
> AlphaRatio: Fix Time

- src/Jackett/Indexers/HDSpace.cs
Add category mappings for HDSpace. To help issue #468.
Movie functionality still needs to be introduced for this indexer. These are JUST mappings.
> HDSpace category mappings

- src/Jackett/Jackett.csproj
> PTP: Add logo

- src/Jackett/Indexers/TorrentDay.cs
TorrentDay: Add HEVC category
https://github.com/Jackett/Jackett/issues/481
> TorrentDay: Add HEVC category

- README.md
> Add BakaBT

- src/Jackett/Indexers/BitCityReloaded.cs
> German Time

- src/Jackett/Indexers/Demonoid.cs
Update Demonoid URL. Fix for #522
> Update Demonoid URL

- src/Jackett/Indexers/SceneTime.cs
- src/Jackett/Models/IndexerConfig/ConfigurationDataRecaptchaLogin.cs
> Add SceneTime captcha support

- src/Jackett/Indexers/BaseIndexer.cs
- src/Jackett/Utils/Clients/UnixLibCurlWebClient.cs
> Support CloudFlare challenges with mono/libcurl

- src/Jackett/Utils/Clients/UnixLibCurlWebClient.cs
> Allow CloudFlareUtilities loading to fail

- src/Jackett/Jackett.csproj
Noticed digitalhive wasn't showing up in the Add Trackers list, I'm guessing this change is needed?
> add digitalhive to Jackett.csproj

- src/Jackett/Indexers/ImmortalSeed.cs
> Fix ImmortalSeed login

- src/Jackett/Indexers/TorrentBytes.cs
> Make TorrentBytes row selector more rebust

- src/Jackett/Indexers/TorrentDay.cs
- src/Jackett/Jackett.csproj
- src/Jackett/Models/IndexerConfig/ConfigurationDataRecaptchaLoginWithAlternateLink.cs
> Allow AlternateLink configuration for TorrentDay

- src/Jackett/Indexers/BeyondHD.cs
- src/Jackett/Indexers/DigitalHive.cs
- src/Jackett/Indexers/GFTracker.cs
- src/Jackett/Indexers/SceneTime.cs
- src/Jackett/Indexers/x264.cs
Use the existing/loaded configData instead of using blank instances.
> Fix ConfigurationDataRecaptchaLogin usage

- src/Jackett/Indexers/TorrentLeech.cs
> Fix TorrentLeech

- src/Jackett/Indexers/TorrentShack.cs
> Change TorrentShack to HTTPS

- src/Jackett/Indexers/MoreThanTV.cs
> Fix MTV group_torrent files parsing

- src/Jackett/Indexers/BJShare.cs
> Add support for SXXEXX search

- src/Jackett/Jackett.csproj
- src/Jackett/packages.config
> Update CloudFlareUtilities to version 0.3.3

- src/Jackett/Indexers/XSpeeds.cs
Fix #356
Thank you @Holbert for the updated regex
> Xspeeds fixes

- src/Jackett/Services/IndexerManagerService.cs
> Improve error handling on corrupt indexer config files

- src/Jackett/Indexers/CardigannIndexer.cs
- src/Jackett/Utils/DateTimeUtil.cs
* Cardigann: Fix url parsing for absolut urls
* Cardigann: normalize selector result value
> Cardigann fixes

- src/Jackett/Indexers/TorrentDay.cs
> Fix TorrentDay categories

- README.md
Add more detailed instructions for installing on Windows
> Detailed Windows install help

- src/Jackett/Indexers/IPTorrents.cs
> IPTorrents: Add support for optional captcha

- src/Jackett/Indexers/Demonoid.cs
> Demonoid: Fix login

- src/Jackett/Indexers/TorrentBytes.cs
> TorrentBytes: Login again if the cookies became invalid

- src/Jackett/Indexers/BaseIndexer.cs
> Dump DL response if there's an error

- src/Jackett/Indexers/AnimeTorrents.cs
> AnimeTorrents: Fix DL link for newbie users

- src/Jackett/Services/IndexerManagerService.cs
Should help fixing/finding out occasional config corruption (#668, #617, #631, #554, ...)
> Make the config saving process more robust

- src/Jackett/Services/ConfigurationService.cs
> Fix Cardigann definition loading if HOME is not set

- src/Jackett/Indexers/BB.cs
> bB: add new attributes and login again if necessary 

- src/Jackett/Indexers/TorrentHeaven.cs
> TorrentHeaven: Make captcha optional and fix login detection

- src/Jackett/Indexers/BestFriends.cs
> Best Friends: Fix parsing for users with waiting time

- src/Jackett/Indexers/CardigannIndexer.cs
> Cardigann: make sure GUID get's set

- src/Jackett/Indexers/Hebits.cs
> Hebits: set comments Url

- src/Jackett/Indexers/MoreThanTV.cs
Times are UTC, convert to local time
> MoreThanTv: Fix Times

- src/Jackett/Indexers/FunFile.cs
- src/Jackett/Indexers/ImmortalSeed.cs
> ImmortalSeed & FunFile: login again if necessary

- src/Jackett/Indexers/CardigannIndexer.cs
> Cardigann: login again if necessary

- src/Jackett/Indexers/IPTorrents.cs
> IPTorrents: Add TV/x265 category

- src/Jackett/Indexers/CardigannIndexer.cs
> Cardigann: Prefere details over comments URL

- src/Jackett/Definitions/uhdbits.yml
> UHDBits: Add details URL

- src/Jackett/Indexers/FileList.cs
> FileList: fix download link and some more improvements

- src/Jackett/Indexers/CardigannIndexer.cs
- src/Jackett/Models/IndexerConfig/ConfigurationData.cs
> Cardigann: Add basic support for ReCaptcha V2

- src/Jackett/Indexers/BeyondHD.cs
- src/Jackett/Jackett.csproj
- src/Jackett/Models/IndexerConfig/ConfigurationDataLoginLink.cs
> BeyondHD: Use Login Link

- src/Jackett/Indexers/x264.cs
> x264: Use now as PublishDate

- src/Jackett/Indexers/SceneAccess.cs
> SceneAccess: Fix login

- src/Jackett/Controllers/AdminController.cs
- src/Jackett/Indexers/BaseIndexer.cs
- src/Jackett/Indexers/CardigannIndexer.cs
- src/Jackett/Indexers/IIndexer.cs
> Add language field to indexers

- src/Jackett/Indexers/TehConnection.cs
> TehConnection: fixes and improvments

- src/Jackett/Indexers/MyAnonamouse.cs
> MyAnonamouse: fix and improve search

- src/Jackett/Indexers/DanishBits.cs
> DanishBits: Fix DL link

- src/Jackett/Definitions/uhdbits.yml
> UHDBits: genre tags have been removed

- README.md
- src/Jackett/Definitions/sdbits.yml
- src/Jackett/Jackett.csproj
> Add SDBits tracker

- src/Jackett/Indexers/TorrentLeech.cs
> TorrentLeech: include 0day and music

- README.md
- src/Jackett/Definitions/secretcinema.yml
- src/Jackett/Indexers/CardigannIndexer.cs
- src/Jackett/Jackett.csproj
> Add Secret Cinema tracker

- src/Jackett/Indexers/HDTorrents.cs
> HD-Torrents: fix and improve search

- src/Jackett/Indexers/BitHdtv.cs
> BIT-HDTV: Fix and improve search

- README.md
- src/Jackett/Indexers/Norbits.cs
- src/Jackett/Jackett.csproj
- src/Jackett/Models/IndexerConfig/Bespoke/ConfigurationDataNorbits.cs
> Add Norbits tracker

- README.md
- src/Jackett/Definitions/tenyardtracker.yml
- src/Jackett/Jackett.csproj
This fixes #795.  Add support for TYT (tenyardtracker)
> Add tenyardtracker

- src/Jackett/Indexers/SceneFZ.cs
> SceneFZ: fix and improve search

- README.md
- src/Jackett/Definitions/nethd.yml
- src/Jackett/Jackett.csproj
> Add NetHD tracker

- README.md
- src/Jackett/Definitions/myspleen.yml
- src/Jackett/Jackett.csproj
> Add MySpleen tracker

- src/Jackett/Content/custom.js
- src/Jackett/Content/index.html
> Add total configured/unconfigured indexers counters

- src/Jackett/Indexers/Hounddawgs.cs
I added movies to the HoundDawgs tracker. My own testing seems to be fine but please come with inputs if I am missing something.
> Add movie categories to HoundDawgs

- src/Jackett/Indexers/EliteTracker.cs
- src/Jackett/Jackett.csproj
This will need further work:
- torrent added date is not always provided in releases listing
- sometimes release title is trimmed
- freeleech/download-volume is not handled
> Implement Elite-Tracker

- src/Jackett/Controllers/PotatoController.cs
- src/Jackett/Models/TorrentPotatoResponseItem.cs
> Add PublishDate to Potato feed for Radarr

- src/Jackett/Utils/ParseUtil.cs
> IMDB validation fix for Torznab Movie Queries

- README.md
> Add Docker to readme

- src/Jackett/Indexers/BakaBT.cs
As discussed, simplified code.
> BakaBT: simplified code by using multiple selectors

- src/Jackett/Definitions/torrentproject.yml
- src/Jackett/Jackett.csproj
First pass at torrentproject.
Closes: #897
> added torrentproject

- src/Jackett/Indexers/PirateTheNet.cs
not sure why git thinks I edited lines 206-211
> Update PirateTheNet url

- src/Jackett/Indexers/FileList.cs
The title is not taken correctly.
> Modify FileList parse selectors

- src/Jackett/Indexers/FileList.cs
```
<option value="0">(all)</option>
<option value="24">Anime</option>
<option value="11">Audio</option>
<option value="15">Cartoons</option>
<option value="18">Misc</option>
<option value="16">Docs</option>
<option value="25">Movies 3D</option>
<option value="20">Movies Blu-Ray</option>
<option value="2">Movies DVD</option>
<option value="3">Movies DVD-RO</option>
<option value="4">Movies HD</option>
<option value="19">Movies HD-RO</option>
<option value="1">Movies SD</option>
<option value="10">Games Console</option>
<option value="9">Games PC</option>
<option value="17">Linux</option>
<option value="22">Mobile</option>
<option value="8">Software</option>
<option value="21">Movies  HD</option>
<option value="23">Movies SD</option>
<option value="13">Sport</option>
<option …
```
> Update FileList category mappings

- src/Jackett/Definitions/nyaa.yml
With fallback for non-present leechers and seeders
Time isn't in list, but it's in details page.
> Nyaa.se: Added tracker definition 

- src/Jackett/Indexers/IPTorrents.cs
As per issue #1156 
Please tell me if I did something wrong.
> IPTorrents: Added x265 Movie category mapping

- src/Jackett/Definitions/ilcorsaronero.yml
Switched from the advanced search to the normal one (the admin has replied to me and he's checking what's wrong, until that, normal search). 
Also, I don't know if some golang templating functions are available, so I commented what I added.
And I added the new categorymappings
[First time doing a pull request, sorry if I did something wrong]
> [ilCorsaroNero]

- README.md
- src/Jackett/Definitions/cinematik.yml
- src/Jackett/Jackett.csproj
> Add tracker Cinematik

- README.md
- src/Jackett/Definitions/cinemageddon.yml
- src/Jackett/Definitions/cinematik.yml
- src/Jackett/Jackett.csproj
> Add tracker Cinemageddon

- src/Jackett/Definitions/hdtorrents.yml
- src/Jackett/Jackett.csproj
I don't know about the categories :\
> Added HDTorrents.it italian tracker

- src/Jackett/Indexers/T411.cs
https://api.t411.li -> https://api.t411.ai
> Updated T411 to new domain name

- README.md
- src/Jackett/Definitions/theempire.yml
- src/Jackett/Jackett.csproj
> Add The Empire

- README.md
- src/Jackett/Definitions/bigtorrent.yml
- src/Jackett/Jackett.csproj
> Add tracker BIGTorrent

- src/Jackett/Indexers/T411.cs
Before only TV Series were supported, the T411 indexer should now behave much better for specific content (TV Animation Series, TV Series, Movies, eBook...)
> T411 proper handling of media categories

- README.md
- src/Jackett/Definitions/3dtorrents.yml
- src/Jackett/Definitions/iloveclassics.yml
- src/Jackett/Jackett.csproj
> Add tracker 3dtorrents

- src/Jackett/Indexers/BitHdtv.cs
Table size changed and now there can be more then 1 table (used for
pinned results.)  This will now search all tables, skipping header row.
For all intents and purposes, the changes are really only 4 lines, see https://github.com/Jackett/Jackett/pull/1232/files?w=1
> Fix Bit-HDTV

- src/Jackett/Definitions/bigtorrent.yml
> Add in BIGTorrent categories

- src/Jackett/Content/index.html
> Open links in new tab

- src/Jackett/Indexers/DigitalHive.cs
https://github.com/Jackett/Jackett/issues/1266
> Digitalhive

- src/Jackett/Indexers/Freshon.cs
Fixes https://github.com/Jackett/Jackett/issues/1260
> Freshon: Fix parsing

- src/Jackett/Indexers/MoreThanTV.cs
Fixes https://github.com/Jackett/Jackett/issues/1289
> MoreThanTv: Add Other category

- src/Jackett/Indexers/IPTorrents.cs
> Fix IPT raw category

- src/Jackett/Definitions/tokyotosho.yml
I made this for Cardigann, but heard it might work without changes with Jackett. Can someone with Jackett set up test this?
Closes #1307
> Add tracker definition for Tokyo Toshokan

- src/Jackett/Indexers/ArcheTorrent.cs
Hi,
New tracker : Arche Torrent
Tested.
> Add ArcheTorrent

- src/Jackett/Indexers/BB.cs
> Update bB url

- README.md
- src/Jackett/Definitions/awesomehd.yml
- src/Jackett/Jackett.csproj
Adding AHD.
AHD has a "group" row which I had problems with.  I wasn't able to filter out some of the unnecessary rows and I had to leave the files selector commented out because some rows show it and others don't.  I also couldn't figure out how to get the freeleech percentages.
> Add Awesome-HD

- src/Jackett/Definitions/nyaa-si.yml
- src/Jackett/Jackett.csproj
* HorribleSubs is using Nyaa.si as their official tracker now:
* http://horriblesubs.info/#comment-3267534087
* Site development can be followed here:
* https://github.com/nyaadevs/nyaa
> Add Nyaa.si ("NyaaV2")

- src/Jackett/Indexers/NCore.cs
- Fixes Jackett/Jackett#1357
- Fixes Jackett/Jackett#1360
> Adds additional parsing so that it sets the key parameter as well

- src/Jackett/Definitions/horriblesubs.yml
* Use http link instead of https as the site doesn't load properly over https.
* Fix date parsing.
> HorribleSubs Fixes

- src/Jackett/Definitions/horriblesubs.yml
Add type (public) and encoding (UTF-8) values to the HorribleSubs.yml definition file.
> Add type and encoding values for HorribleSubs

- src/Jackett/Content/custom.css
- src/Jackett/Content/custom.js
- src/Jackett/Content/custom_mobile.css
- src/Jackett/Content/index.html
- src/Jackett/Content/libs/handlebarsextend.js
- src/Jackett/Content/setup_indexer.html
- src/Jackett/Definitions/nyaasi.yml
- src/Jackett/Indexers/CardigannIndexer.cs
- src/Jackett/Jackett.csproj
- src/Jackett/Models/IndexerConfig/ConfigurationData.cs
Title speaks for itself. 
I also modified the "nyaa.si" indexer to show what is possible with this PR. It contains the changes of https://github.com/Jackett/Jackett/pull/1419, but then easier to use.
Let me know what you think.
> Added a "select" input type and "default" value for settings.

- src/Jackett/Definitions/nyaa-pantsu.yml
- src/Jackett/Definitions/nyaasi.yml
This contains the changes of https://github.com/Jackett/Jackett/pull/1426 and all other required changes that https://github.com/Jackett/Jackett/pull/1426 missed.
I've also updated Nyaapantsu to the new selectbox.
> Fix #1425 - Nyaapantsu fixed and nyaasi naming changes

- src/Jackett/Definitions/anirena.yml
Requested by @valantislevas:
https://github.com/Jackett/Jackett/issues/1391#issuecomment-306000772
> Anirena: Provide both torrent and magnet download links

- src/Jackett/Definitions/torrent9.yml
The site has changed domain name.
> [Torrent9] Domain change .biz -> .top

- src/Jackett/Definitions/torrent9.yml
put the date on the right place
> fix torrent9 incorrect naming rules

- src/Jackett/Definitions/kickasstorrent.yml
> KickAssTorrent: Fix date parsing

- src/Jackett/Definitions/nyaasi.yml
> Fix title for elements with comments.

- README.md
- src/Jackett/Definitions/nexttorrent.yml
Add Next Torrent french tracker
> Add NextTorrent tracket

- README.md
- src/Jackett/Definitions/manicomioshare.yml
I made a new definition for this indexer.
Manicomio Share is a general Brazilian tracker.
A few issues (please help out if you know how to solve):
1 - The tracker does not show the "release date" unless i click on another button while searching. The button contains an event like this one: "onclick="expand(584941,event)"".
2 - I wasn't able to configure the "login: post" method, since it's AJAX + JS. I used Cookies instead.
> New definition for indexer "Manicomio Share"

- README.md
- src/Jackett/Definitions/b2s-share.yml
I made a new definition for this indexer.
B2S-Share is a general Brazilian tracker.
This tracker does not support multiple category search, so it's searching all categories.
> New definition for indexer "B2S-Share"

- README.md
- src/Jackett/Definitions/torrentdownloads.yml
Add "Torrent Downloads" tracker as requested on "Issue #1559"
> Add "Torrent Downloads" tracker

- src/Jackett/Indexers/MoreThanTV.cs
https://github.com/Jackett/Jackett/issues/1616
> MoreThanTv: Improve Number parsing

- README.md
- src/Jackett/Definitions/cpabien.yml
- src/Jackett/Definitions/nexttorrent.yml
- src/Jackett/Definitions/zetorrents.yml
- Next Torrent
-- new search path
- Torrent-Mania (now zetorrents).
-- Add new tracker zetorrents
> Fix issue : #1615

- src/Jackett/Indexers/Xthor.cs
- src/Jackett/Models/ReleaseInfo.cs
- src/Jackett/Utils/StringUtil.cs
Fixing bugs found on Xthor Provider...
https://github.com/Jackett/Jackett/issues/145
> [WIP] Fixes for Xthor Indexer

- src/Jackett/Indexers/Abnormal.cs
- src/Jackett/Indexers/Xthor.cs
Fixing bugs found on ABN Provider...
https://github.com/Jackett/Jackett/issues/145
> Fixed Abn Indexer, Added 4K to Xthor

- src/Jackett/Definitions/manicomioshare.yml
Removed cookie and added POST method
> Fixed login in Manicomio Share

- src/Jackett/Definitions/b2s-share.yml
This fixes the search for episodes and movies in general
> Fixes "B2S-Share" search

- src/Jackett/Definitions/manicomioshare.yml
This fixes content search in general
*Since the tracker returns no results when searching with a year on the query, i've also added a workaroud to fix CouchPotato and Radarr search*
> Fixes "Manicomio Share" search

- src/Jackett/Indexers/SceneFZ.cs
- src/Jackett/Jackett.csproj
- src/Jackett/Models/IndexerConfig/Bespoke/ConfigurationDataSceneFZ.cs
> SceneFZ (SFZ) is a Private Tracker
Working as well, ready for using in a production environment.
> Features
- ~~[x] Pagination~~
> Informations on release:
_Striked informations mean they are not available on tracker side or in this indexer version._
> Thanks to @panoramasecret for sponsoring this modification
- See https://github.com/Jackett/Jackett/issues/1679
_Made with love,_
**Enjoy this fixed provider for Jackett,**
JigSaw
> fix(indexers): rewritted scenefz from scratch

- README.md
- src/Jackett/Definitions/torlock.yml
> feat(indexers): added torlock tracker

- README.md
- src/Jackett/Definitions/gay-torrents.yml
🏳️‍🌈
I’m on a roll here! Like #1689, this is a tracker with mostly porn, but also many gay-themed movies, tv-shows, documentaries (that are otherwise hard to find). This is technically a private tracker, but there’s no requirement of ratio. I’ve set it as `semi-private` because there’s no invite needed but you have to log in.
Cheers!
> feat(indexers): added gay-torrents.net

- README.md
- src/Jackett/Definitions/gaytorrentru.yml
🏳️‍🌈
Adding a new tracker, GayTorrent.ru following #1663
Login works correctly, search and download too, free leech identified. I’ll do a little more testing (categories etc.) and I’ll report again.
> feat(indexers): added gaytorrent.ru

- README.md
- src/Jackett/Definitions/kickasstorrent-kathow.yml
kat.how -> thekat.se
fixes #1607
> Fixing the KAT clone tracker

- src/Jackett/Definitions/kickasstorrent.yml
They changed the url for the latest torrents once again… *sigh*
Still works though
> fix(indexers): updated browse page endpoint

- src/Jackett/Definitions/yggtorrent.yml
Hello,
Many peoples are experiencing problems with french release names in which the date is not always right behing the movie titles.
So I added an option (disabled by default), to normalize names :
**[Option disabled]**
**[Option enabled]**
> Added option to normalize release name [Ygg]

- src/Jackett/Definitions/secretcinema.yml
Change Secret Cinema definition to match new site layout
> Change Secret Cinema definition to match new site layout

- src/Jackett/Definitions/karagarga.yml
> Fix KG parsing

- src/Jackett/Definitions/cztorrent.yml
If you have better solution for seasson searching pls tell me
> Fix Date and improve seasson searching for CzTorrent

- src/Jackett/Content/custom.js
- src/Jackett/Content/index.html
When a description is available, display it on the Indexer Setup panel
and when it is not then don't.
> Display a description on Indexer Setup panel

- src/Jackett/Indexers/TransmitheNet.cs
TTN -> NBL as it's called nebulance
> TransmitheNet.cs TTN -> NBL in the note

- src/Jackett/Definitions/kickasstorrent.yml
fix so it passes the Sonarr test.
add description.
Tested on Jackett Dashboard and Sonarr
> kickasstorrent: fix #1852

- README.md
- src/Jackett/Indexers/LostFilm.cs
- src/Jackett/Jackett.csproj
Implementation for #1922.
Tracker Name: LostFilm.tv
Tracker Content: Huge amount of TV Series in Russian language.
Tracker URL : http://www.lostfilm.tv/
Tracker Language : Russian
Privacy: Free registration. Required to fetch torrent files. Not required for search functionality.
Noticed issue: tracker combines separate Episode releases into a single Season release so this indexer returns season releases while asking for episodes.
> Add a new indexer: LostFilm.tv / ru-ru / semi-private

- src/Jackett/Definitions/t411v2.yml
Fixes Greys Anatomy V2 for T411 french keywords
> T411v2: Fix Greys Anatomy search

- src/Jackett/Indexers/Hounddawgs.cs
Both is DK Movies (HD&SD) and _not_ TV-content.
> Wrong category for 89 & 91

- src/Jackett/Definitions/torviet.yml
incldead=0 includes dead when searching torviet
> torviet: fix including dead

- src/Jackett/Definitions/uhdbits.yml
> uhdbits: fix date

- README.md
- src/Jackett/Definitions/speed-share.yml
> Add Speed-Share indexer

- README.md
- src/Jackett/Definitions/bitme.yml
Added BitMe. Categories modeled off of BitSpyder. #1977
> Added BitMe tracker

- src/Jackett/Content/custom.js
- src/Jackett/Content/index.html
- src/Jackett/Controllers/ServerConfigurationController.cs
- src/Jackett/CurlHelper.cs
- src/Jackett/Models/Config/ServerConfig.cs
- src/Jackett/Models/DTO/ServerConfig.cs
- src/Jackett/Utils/Clients/HttpWebClient.cs
- src/Jackett/Utils/Clients/HttpWebClient2.cs
- src/Jackett/Utils/Clients/UnixSafeCurlWebClient.cs
Tested on windows environment. On Linux also should work.
> UI proxy settings

- src/Jackett/Content/index.html
Prevents cache using old version
> Bump Custom.js version number

- src/CurlSharp/CurlSharp.csproj
- src/CurlSharp/NativeMethods.cs
> Use platform detection that works on mono 4.6+

- src/Jackett/Content/index.html
Prevent browser using cached old version
> Bump Custom.js version

- src/Jackett.Common/Indexers/LostFilm.cs
Follow-up for #2012
Fixes `"error":1` during re-login if login happened before and current session is still valid.
> Update LostFilm.tv indexer

- build.cake
> Cake build: Code tidy

- src/Jackett.Common/Definitions/archetorrent.yml
ArcheTorrent - Better search v3
> ArcheTorrent - Better search v3

- src/Jackett.Common/Definitions/b2s-share.yml
- src/Jackett.Common/Definitions/speed-share.yml
Added login selector to make sure we're logged in.
> Login selector on b2s-share & speed-share

- appveyor.yml
- build.cake
Finds hash of the last tag and then uses the commit summary to assist in release note creation
> Assist Release Note Creation

- appveyor.yml
- build.cake
Logic wasn't quite right for which commits to include
> Assist Release Note Creation Attempt 2

- src/Jackett.Common/Indexers/Xthor.cs
update xthor provider new tld.
xthor.bz > xthor.to
> update xthor tld

- src/Jackett.Common/Content/index.html
> add a link to the Jackett project

- src/Jackett.Common/Definitions/oxtorrent.yml
Basically Nextorrent clone. As Nextorrent seems down now.
> New indexer : oxtorrent.yml

- src/Jackett.Common/Indexers/IPTorrents.cs
Updated to add category 101 for movies (4K) for iptorrents.
> Updated iptorrents indexer column to add proper support for 4K(2160p) 

- src/Jackett.Common/Definitions/karagarga.yml
> Karagarga: Fix date

- src/Jackett.Common/Indexers/GimmePeers.cs
This is untested but it should work
> Added missing Gimmepeers categories

- README.md
- src/Jackett.Common/Definitions/hachede.yml
Adding spanish tracker HacheDe requested [here](https://github.com/Jackett/Jackett/issues/1468)
Besides, closes https://github.com/Jackett/Jackett/issues/2396
> Adding spanish tracker HacheDe

- src/Jackett.Common/Definitions/hachede.yml
- src/Jackett.Common/Definitions/puntotorrent.yml
Hi,
with this PR:
- Add details link for HacheDe
- Add spanish tracker Puntotorrent requested [here](https://github.com/Jackett/Jackett/issues/1468)
> Adding puntotorrent and details for HacheDe

- README.md
- src/Jackett.Common/Definitions/hdcity
Adding one more of the spanish trackers requested [here](https://github.com/Jackett/Jackett/issues/1468)
> Add spanish tracker HDCity

- README.md
- src/Jackett.Common/Definitions/Bittorrentfiles.yml
Adding german tracker BitTorrentFiles
> Adding german tracker BitTorrentFiles

- README.md
- src/Jackett.Common/Definitions/tbplus.yml
Add definition for TBPlus Spanish private tracker #2155
> Add definition for TBPlus

- src/Jackett.Common/Definitions/hdcity.yml
- src/Jackett.Common/Definitions/puntotorrent.yml
- Corrected the HDCity login, warned [here](https://github.com/Jackett/Jackett/issues/1468#issuecomment-362304154)
- Corrected Puntotorrent
- Make grabs optional, for new releases of torrents with no grabs
> Corrections in Puntotorrent and HDCity

- README.md
- src/Jackett.Common/Definitions/torrentland.yml
Adding one more of the spanish trackers requested in https://github.com/Jackett/Jackett/issues/1468
> Adding spanish tracker Torrentland

- README.md
- src/Jackett.Common/Definitions/unionfansub.yml
One more spanish tracker requested in https://github.com/Jackett/Jackett/issues/1468 and https://github.com/Jackett/Jackett/issues/1556
> Adding spanish tracker Union Fansub

- src/Jackett.Common/Definitions/hdcity.yml
Fixed for work with both themes.
Commented in https://github.com/Jackett/Jackett/issues/1468#issuecomment-366620611
> Fix HDcity.li

- README.md
- src/Jackett.Common/Definitions/torrentwtf.yml
Hi
This is new CZ/SK private Tracker
> Add Torrent.wtf tracker

- src/Jackett.Common/Definitions/blutopia.yml
- Updated Description
- Updated Search Path
- Added MAL ID
> (Fix) blutopia.yml

- src/Jackett.Common/Definitions/shareisland.yml
Update upload/download modifier
Added a possibility to handle better Stagione instead S0? or Season
> Update shareisland traker

- src/Jackett.Common/Definitions/puntotorrent.yml
Change TV Shows search format for Spanish style and add [spanish] for detected Spanish language in Sonarr/Radarr
> Puntotorrent: TV Shows search and spanish language

- src/Jackett.Common/Definitions/yggtorrent.yml
Test is not working because https://yggtorrent.is/top/day?category=2145 is called in test and this page is making an ajax call (https://yggtorrent.is/engine/ajax_top_query/day) returning JSON response.
I don't know if Jackett can directly query https://yggtorrent.is/engine/ajax_top_query/day and parse JSON response ?
> yggtorrent: change for new website #2852

- .gitignore
- src/Jackett.Common/Definitions/nyaa-pantsu.yml
- src/Jackett.Common/Definitions/nyaasi.yml
- src/Jackett.Common/Definitions/sukebei-pantsu.yml
- src/Jackett.Common/Definitions/sukebeinyaasi.yml
Would also like to include a fix for #2923 before merging.
> Add download/upload factor to nyaa trackers

- src/Jackett.Common/Indexers/TorrentLeech.cs
Fixes https://github.com/Jackett/Jackett/issues/2864
> TorrentLeech: Update DateTime parsing

- README.md
- src/Jackett.Common/Definitions/racing4everyone.yml
-  I have yet to test this. If anyone is willing to please do. Currently is open reg for 3 more days.
> (Create) Racing4Everyone Definition

- src/Jackett.Common/Definitions/manicomioshare.yml
- src/Jackett.Common/Definitions/speed-share.yml
Improved anime search on Manicomio-Share and Speed-Share.
Improved resolution detection on Speed-Share
> Improved anime search and speed-share resolution detection

- src/Jackett.Common/Definitions/xbytes2.yml
Fixes and optimizations suggested by kaso17
> Fixes and optimizations

- README.md
https://github.com/Jackett/Jackett/pull/3082
> Remove TehConnection From README

- README.md
- src/Jackett.Common/Definitions/rgu.yml
Adds RGU Tracker and updated Readme
> add rgu tracker

- src/Jackett.Common/Definitions/ilcorsaroblu.yml
Many tanks to @kaso17 for the infinite patience! I hope one day to make a full file without his help ... I think he hope too :D
> New traker file for Il Corsaro Blu

- README.md
Update file to adding new traker file
> Added Il Corsaro Blu

- src/Jackett.Common/Definitions/downloadville.yml
- src/Jackett.Common/Definitions/yggtorrent.yml
This PR try to better manage replace of multi term for yggtorrent and downloadville 
See discussion in https://github.com/Jackett/Jackett/pull/3130
> Better Yggtorrent and downloadville MULTI replace

- src/Jackett.Common/Definitions/downloadville.yml
Fix typo if MULTI replacement is check
> Fix typo in downloadville yml

- src/Jackett.Common/Indexers/BaseIndexer.cs
- src/Jackett.Common/Jackett.Common.csproj
- src/Jackett.Common/Services/Interfaces/IProtectionService.cs
- src/Jackett/Services/ProtectionService.cs
The DPAPI won't be present, will be using AspNetCore DataProtection
instead
> .NET Core preparation

- src/Jackett.Common/Indexers/EliteTracker.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataEliteTracker.cs
Add option for Elite Tracker (FR) for download torrent using https for tracker URL.
> Add option for Elite Tracker (FR)

- src/Jackett.Common/Definitions/hdspain.yml
Add Spanish Private HD tracker https://www.hd-spain.com/
Based on Albvadi's code from HD-Spain forum all credit to him, I only added some changes for better search, ISO correct and spain flag detection
> Add HD-Spain tracker

- README.md
Add new private tracker HD-Spain
> Update readme (add HD-Spain tracker)

- src/Jackett.Common/Definitions/shareisland.yml
After the "reboot" of the tracker many categories have changed.
I have updated the categories to comply with the new ones.
> Updated categories

- src/Jackett.Common/Indexers/NCore.cs
Hi!
This else is not needed!
We need to recreate the new title even if release.Description.Contains imdb
> Fix for #3263

- src/Jackett.Common/Definitions/tntvillage.yml
This tracker always respect the format
SXXEYY so I cleaned up the code, I only updated the code adding a simple regex, just in case a rel with XXxYY came up!
> Update for better regex expression

- src/Jackett.Common/Definitions/downloadville.yml
> Fix downloadville

- src/Jackett.Common/Indexers/Newpct.cs
A basic rename to newpct indexer so programs like sonarr can parse correctly episodes.
> feat(newpct): rename title to make them more standarized

- src/Jackett.Common/Definitions/xbytes2.yml
Replace Xbytes language tag to language name in English
> File Languages

- src/Jackett.Common/Content/custom.js
- src/Jackett.Common/Content/index.html
- src/Jackett.Common/Models/Config/ServerConfig.cs
- src/Jackett.Common/Models/DTO/ServerConfig.cs
- src/Jackett.Common/Services/ImdbResolver.cs
- src/Jackett.Common/Services/IndexerManagerService.cs
- src/Jackett/Controllers/ServerConfigurationController.cs
OMDB recently added a private.omdbapi.com domain for supporters and this option allows the user to customize it while also allowing that url to change more rapidly in the future
> Allow configuration of omdb url

- src/Jackett.Common/Definitions/blutopia.yml
- added new input field "description" which is used to be able to search into torrent descriptions and media info using keywords
- This doesn't fix #3355 . Im not sure what the issue is. Maybe @kaso17 can check it out. I believe you still have a account there. If not let me know.
> (Update) blutopia.yml

- README.md
Added steps to build from source on OSX.
> Build From Source OSX

- src/Jackett.Common/Definitions/btxpress.yml
> Fix BTXpress

- src/Jackett.Server/Program.cs
This should further reduce startup times (less directories to traverse).
> adjust content root path

- README.md
Added reference to a RHEL and Ubuntu ansible galaxy role for installing via Ansible.
> Updated Readme to include linux Ansible installations

- README.md
- src/Jackett.Common/Indexers/Nordicbits.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataNordicbits.cs
This code adds support for Nordicbits / DK Private Tracker.
Special thanks to the author of Norbits.cs as this code is based on that.
> Add support for Nordicbits.org/nordicb.org

- src/Jackett.Common/Indexers/Nordicbits.cs
I made some copy-paste errors, while building the categoryList.
Because of this - the seach string for Apps & Ebooks won't be builded correctly.
Fixed
> Update nordicb.org - categoryList for search

- README.md
- src/Jackett.Common/Definitions/hqsource.yml
> Added HQSource polish tracker support

- README.md
- src/Jackett.Common/Definitions/btgigs.yml
Polish general tracker support.
> Add BTGigs polish tracker.

- README.md
- src/Jackett.Common/Indexers/720pier.cs
Added 720pier.ru indexer.
Known issue:
- not all queries on querying browse page (only on getting most recent ones) throws errors, but it still works (could be filtered though to remove error)
- pretty slow but I think its just access to api.
> Added 720pier.ru

- README.md
- src/Jackett.Common/Definitions/redstartorrent.yml
Add red start torrent polish general/tv tracker.
> Add red star torrent.

- src/Jackett.Common/Definitions/ilcorsaronero.yml
Advanced search always performed
now works even if no categories are selected into a manual search
> Update il corsaronero

- src/Jackett.Common/Indexers/TorrentSyndikat.cs
A lot of categories got dropped, also there are some new categories.
Additionally I updated the namings.
> Updated categories for TorrentSyndikat

- README.md
- src/Jackett.Common/Definitions/hd4free.yml
> (Add) hd4free.yml

- src/Jackett.Common/Definitions/ethor.yml
- Fix language vfq (French version with voice in Quebec) in sonarr. Sonarr tell episode is in english but episode is in french
- Fix some tv show have space between season number and episode number
> Update ethor.yml 

- src/Jackett.Common/Definitions/zamundanet.yml
I was the one who created both Zamunda.net and Zelka.org tracker YMLs. So far they've had only Movies and TV shows, but now I'm also adding Audio/Music support for this tracker
> Adding Audio/Music support to the tracker Zamunda.net

- src/Jackett.Common/Definitions/redtopia.yml
- add translations
- all credit to @garfield69
> (Update) redtopia.yml

- src/Jackett.Common/Definitions/btxpress.yml
- add Global Double Upload
- add translations
- all credit to @garfield69
> (Update) btxpress.yml

- src/Jackett.Common/Definitions/racing4everyone.yml
- add Global Double Upload
- add translations
- all credit to @garfield69
> (Update) racing4everyone.yml

- src/Jackett.Common/Indexers/NCore.cs
- Add pagination support for ncore #3716 
- Correct handling of Descriptions
- Add hun tag to torrent title if it contains Hungarian audio but not visible in title
> Correction for ncore paganition #3716

- src/Jackett.Common/Indexers/HDTorrents.cs
Adds support for higher user classes like uploader
> hdtorrent-uploader-support

- README.md
- src/Jackett.Common/Definitions/elitetorrent-biz.yml
Add definition for EliteTorrent.biz Spanish public tracker #1293.
Kudos to @garfield69 for the support.
> Add definition for EliteTorrent.biz

- src/Jackett.Common/Indexers/NCore.cs
Second part of correction #3997
- try/catch block for torrent parsing
Sonarr test button was failed because an invalid torrent.
> Second part of correction #3997

- README.md
- src/Jackett.Common/Definitions/dxdhd.yml
> (Add) dxdhd.yml

- src/Jackett.Common/Indexers/HDTorrents.cs
Sets DownloadVolumeFactor based on user rank
> hdtorrents-rank-freeleech

- src/Jackett.Common/Definitions/bigtower.yml
Some rel are request and this tag was appended to the rel name, this mod remove that tag
> BigTower update

- src/Jackett.Common/Indexers/Meta/Fallbacks.cs
- src/Jackett.Common/Indexers/Meta/ResultFilters.cs
Fix #4015
- Managed the case when the IImdbResolver.MovieForId returns a movie without the title
> Fix OMDB Key with request limit reached #4015

- README.md
- src/Jackett.Common/Definitions/scenerush.yml
row needs to have a details link
> update rows for scenerush

- src/Jackett.Common/Definitions/torrenting.yml
https://github.com/Jackett/Jackett/issues/4282
> Issue 4282.

- README.md
- src/Jackett.Common/Definitions/420files.yml
> (Add) 420files Definition

- README.md
- src/Jackett.Common/Indexers/Newpct.cs
- Indexer tries to download from mirrors if provided link fails
> Newpct - Allow download from mirrors

- src/Jackett.Common/Definitions/hdtorrentsit.yml
Update regex to handle better seasons and multiple episode
Freelech torrent support
Minor fix
> HDTorrent.it

- README.md
- src/Jackett.Common/Definitions/desitorrents.yml
Addresses #378 
Response JSON has no id's associated with each value so have to pull out data based on <th> position. No great, but works.
> Add desitorrents to available indexers

- src/Jackett.Common/Indexers/Nordicbits.cs
Better late than never.
All themes are now supported.
> Nordicbits - Add support for christmas theme

- src/Jackett.Common/Definitions/btgigs.yml
- src/Jackett.Common/Definitions/hqsource.yml
- src/Jackett.Common/Definitions/polishsource.yml
- src/Jackett.Common/Definitions/redstartorrent.yml
args should have quotes around them, yaml could parse as object
> few sites - args field as string

- src/Jackett.Common/Definitions/jpopsuki.yml
> fixed an issue with tabulations in title

- README.md
- src/Jackett.Common/Definitions/hush.yml
Add support for HuSh fr-fr tracker.
> Add HuSh tracker

- src/Jackett.Common/Indexers/Xthor.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataXthor.cs
Xthor use EXXX in name of anime episodes while sonarr use XXX, so every queries fetch no results. This option change XXX to EXXX to fix the query.
> Add an option to search for anime on Xthor  (

- src/Jackett.Common/Indexers/EliteTracker.cs
Fix a parse error in elite-tracker.
> fix a parse error for elite-tracker

- src/Jackett.Common/Indexers/Xthor.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataXthor.cs
With an option in xthor indexer config. Leave blank to deactivate.
> issue #3847 |Xthor] replace multi keyword

- src/Jackett.Common/Definitions/yggtorrent.yml
Enhance sonarr compatibility with anime by renaming episode (xxx -> Exxx).
> [ygg] Enhance sonarr compatibility with anime

- src/Jackett.Common/Definitions/torrentland.yml
> Update torrentland.yml. Resolves #3708

- src/Jackett.Common/Definitions/yggtorrent.yml
replace spaces in searched name by quotation marks so that a YGG search engine return results on partial keywords
> replaced " " by """"

- README.md
- src/Jackett.Common/Definitions/vizuk.yml
Added definition yml for https://torrent.vizuk.li
> Added Vizuk private spanish tracker

- src/Jackett.Common/Definitions/yggtorrent.yml
see comment on pr #4677 @xfouloux 
https://github.com/Jackett/Jackett/commit/001ee19752e84493d9df6f0037c0fdfc0e34876b#r32310417
> ygg remove extra quote character

- src/Jackett.Common/Definitions/yggtorrent.yml
Add another category for movies search.
> Alternate search category for movies in yggtorrent

- README.md
- src/Jackett.Common/Definitions/thehorrorcharnel.yml
- src/Jackett.Common/Indexers/TVstore.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataTVstore.cs
Implementation of TVstore Indexer #2590
> Implementation of TVstore Indexer #2590

- src/Jackett.Common/Indexers/NCore.cs
Implementation of request #4778
> add offset support to ncore indexer

- README.md
- src/Jackett.Common/Definitions/totallykids.yml
Utilized much of the great work by @garfield69 in e7edd17 for TK's sister-site, CartoonChaos.
> Add TotallyKids.tv definition. Resolves #4

- src/Jackett.Common/Indexers/Torrentscsv.cs
Bumped search results returned from 100 to 500
> Raised number of search results returned

- src/Jackett.Common/Definitions/hdforever.yml
> Freeleech tag fix & token option

- src/Jackett.Common/Definitions/ilcorsaronero.yml
I just realized that the rss sync was wrong, always the same page was request.
I think 5 pages are enough, so dropped to 5 page request
There's a way to make a rss sync different from a search string?
In this situation the best is to have more pages to scan after a search and less pages to scan for a rss sync
> Update il corsaro nero

- src/Jackett.Common/Definitions/insanetracker.yml
Insane login page changed from takelogin.php to login.php
> Insane new login.php page

- src/Jackett.Common/Indexers/BroadcastTheNet.cs
- If only a season is searched, format it in a way expected by the indexer
> Season Search

- src/Jackett.Common/Definitions/insanetracker.yml
Totally rewritten for the For the UI 2.0
> Totally rewritten for the new UI

- src/Jackett.Common/Definitions/btdb.yml
Little update to go through page 5 during search/sync
> Update for btdb

- src/Jackett.Common/Definitions/hachede.yml
For resolve the same issue that I have opened :)
#5474
> hachede: switch to cookie login.

- README.md
- src/Jackett.Common/Indexers/AniDub.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataAniDub.cs
Implementation of the indexer for AniDUB semi-private anime torrent tracker. Resolves #5399
> Add AniDUB tracker (#5399)

- src/Jackett.Common/Indexers/AnimeBytes.cs
Testable by searching for "Koroshiya 1", for example.
> Animebytes: add Live Action Movies categorization

- README.md
- src/Jackett.Common/Indexers/toloka.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataToloka.cs
Based on rutracker.cs.
Closes #4970
> Add Toloka.to Semi-Private Tracker.

- src/Jackett.Common/Definitions/nyaasi.yml
This allows people to filter on Live Action and Pictures as well.
> Add all category options to Nyaa.si

- src/Jackett.Common/Definitions/vizuk.yml
> Revert to HTTPS

- src/Jackett.Common/Indexers/TVstore.cs
- Added support of parameter offset
- Correct name of torrents (Remove .attribute from it)
- Correct name of season Packs (Previously season packs were showed as
single episodes)
- Add correct Upload Volume factor calculation
- Add preparation for IMDB ID based search
> TvStore update

- README.md
- src/Jackett.Common/Definitions/crazyhd.yml
- src/Jackett.Updater/Program.cs
This was previously closed as needing c#, but I disagree. I salvaged the attempted yml file and modified it with the fix. I did not change anything from the original yml except the search block. The original issue for this tracker was that it didn't support the search query as a get parameter, but it does as a post. Also updated the freeleech text replacement to be less strict.
> Add crazyhd.yml

- src/Jackett.Common/Definitions/hdspain.yml
This way Season Pack results are understood by sonarr.
> HDSpain: Replace Season with english notation: eg. T2 -> S2

- src/Jackett.Common/Definitions/shareisland.yml
Improved the char substitution for the title
Now only the special char are removed
> shareisland update

- src/Jackett.Common/Definitions/ilcorsaroblu.yml
Improved the char substitution for the title
Now only the special char are removed
> il corsaro blu update

- src/Jackett.Common/Definitions/girotorrent.yml
Improved the char substitution for the title
Now only the special char are removed
> girotorrent update

- src/Jackett.Common/Indexers/AnimeBytes.cs
AnimeBytes on Jackett doesn't filter category types. This PR fixes for categories of Anime, Movies, Games and Manga. It does not fix Music at the moment; If Music category is chosen, it returns everything including Music. I will try to fix it when I have time.
Additionally, I have fixed an issue related to #5461. Since Sonarr basically sends episodes (without the prefix of E or S) as it is when the Sonarr type is 'Anime', the regex can be simplified. Furthermore, Animebytes doesn't support Episodes or Season search anyways, it's better to drop as many digits as possible.
> Fixed animebytes category filter and episodes with 3 digits

- src/Jackett.Common/Definitions/demonoid.yml
Based on this:
https://fora.dnoid.to/index.php?topic=316.msg1209#msg1209
Formatting has a bit of a change
> Fixing the formatting for Demonoid.

- src/Jackett.Common/Definitions/btdigg.yml
- src/Jackett.Common/Definitions/puntotorrent.yml
Update puntotorrent.yml to a new domain
> Update puntotorrent.yml to a new domain

- README.md
- src/Jackett.Common/Indexers/Corsarored.cs
> [New Tracker REQ] Corsaro.red

- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataEliteTracker.cs
removed experimental label in ConfigurationDataEliteTracker (again !)
> removed experimental label in ConfigurationDataEliteTracker

- src/Jackett.Common/Definitions/immortuos.yml
> (Update) immortuos.yml

- src/Jackett.Common/Definitions/freetorrent.yml
- update UNIT3D ver
- update login block
- add comments selector
- add ratio block
> (Update) freetorrent.yml

- src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs
- src/Jackett.Common/Indexers/AlphaRatio.cs
> Added IMDb ID support for AlphaRatio

- src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs
Improves on code from #6074.
Sorry for not just including it in the earlier PR.
> Replaced foreach loop with more efficient LINQ

- src/Jackett.Common/Definitions/demonoid.yml
- Fixed order by default which is `added`.
- Reverted category mapping to first commit.
Some of the things need to be updated to make it work again probably @garfield69
> Fix the multiple category select & stacking

- src/Jackett.Common/Definitions/nyaa-pantsu.yml
This is the new domain for nyaa pantsu.
> Add a new domain for nyaa-pantsu

- src/Jackett.Server/Controllers/ServerConfigurationController.cs
> Restart webhost if the user changes proxy settings

- src/Jackett.Common/Indexers/Xthor.cs
This is a future fix for the xthor domain name.
The current domain name expires in one month and will no longer be accessible.
I will mention @garfield69 once the change is made.
> [xthor] Future fix: New domain name for xthor

- install_service_systemd.sh
@garfield69 This should fix the systemd update issue. #5208
The users with this problem will have to reinstall the systemd service.
> updater: fix systemd auto-update

- README.md
- src/Jackett.Common/Definitions/baibako.yml
- src/Jackett.Common/Definitions/booktracker.yml
- src/Jackett.Common/Definitions/casstudiotv.yml
- src/Jackett.Common/Definitions/hamsterstudio.yml
- src/Jackett.Common/Definitions/piratbit.yml
Also piratbit.top, booktracker.org and hamsterstudio.org.
> BaibaKo and CasStudio are currently Semi-Private

- src/Jackett.Common/Definitions/demonoid.yml
Didn't test this locally but just saw that they changed domain along with some changes on url probably several days ago as search is not working properly.
PS: seeded should be 2, not 3.
> Changes to demonoid

- src/Jackett.Common/Indexers/digitalcore.cs
> Added/updated Categories

- src/Jackett.Common/Definitions/hdcity.yml
Search for complete seasons with other names than "T1"
> [HDCity] Optimize search for Complete Season 

- src/Jackett.Common/Definitions/dxp.yml
https://github.com/Jackett/Jackett/issues/6382
> dxp: mark VIP categories as 'Other/Misc'

- src/Jackett.Common/Definitions/channelx.yml
> (Update) ChannelX

- src/Jackett.Common/Definitions/beyond-hd-oneurl.yml
- src/Jackett.Common/Indexers/CardigannIndexer.cs
Quick fix for the recaptcha/2FA woes of the current method
> Add support for Beyond-HD OneURL login

- README.md
- src/Jackett.Common/Indexers/Partis.cs
Added new private Slovenian tracker Partis.si
> Added new tracker Partis.si

- README.md
- src/Jackett.Common/Definitions/pornbay.yml
Added support for [Pornbay](https://pornbay.org/).
Not too familiar with this project yet, so if I missed anything, please let me know.
I've tested all the features I'm familiar with (searching, filtering by category, downloading based on search and using the `Test` button) and those seem to work fine.
> Added support for tracker: Pornbay

- src/Jackett.Common/Indexers/rutracker.cs
#6638 Added regexp to cut director names from rutracker title
> fix rutracker movies naming ( directors name cut)

- src/Jackett.Common/Indexers/BJShare.cs
Added few more Animes and Series to the mapping to make it work with the naming expected by Sonarr.
> BJShare: Improve search result compatibility with Sonarr on few more TV Shows / Animes

- src/Jackett.Common/Indexers/digitalcore.cs
dc added a captcha system.. cookie workaround!
> Digitalcore - Cookie workaround because captcha

- src/Jackett.Common/Indexers/MejorTorrent.cs
The current implementation is making hundreds of requests. I have to resolve that...
> mejortorrent: fix download urls and grabs. resolves #6449

- README.md
- src/Jackett.Common/Definitions/legacyhd.yml
> (Add) legacyhd.yml

- src/Jackett.Common/Indexers/FileList.cs
-fixed issue when trying to add FileList Indexer
> Issue: #6782 - [filelist] Can't add filelist (Config) 

- src/Jackett.Common/Indexers/Corsarored.cs
Fixes #6307 
This pull request cleans up the corsaro.red tracker file, bringing everything in line with C# style guides. I've improved on the perform query code to make it much more readable. And ultimately I fixed the bug in the API call to search by scanning the categories being searched and returning the best fit search API category, which was different than the results categories already in the tracker.
> [corsaro.red] fix bug in category searches

- src/Jackett.Common/Indexers/PassThePopcorn.cs
- src/Jackett.Common/Models/IndexerConfig/ConfigurationDataAPILoginWithUserAndPasskeyAndFilter.cs
Modifies the PassthePopcorn login format to use the new API key format instead of the deprecated user/password system that does not work with 2FA.
> Add PassThePopcorn API login

- src/Jackett.Common/Definitions/legacyhd.yml
> (Fix) legacyhd.yml

- src/Jackett.Common/Definitions/soundpark.yml
- src/Jackett.Common/Indexers/CardigannIndexer.cs
> Extended template language to allow some nesting in if/else and fix sound park search using lidarr.

- README.md
- appveyor.yml
- build.cake
- src/Jackett.Common/Jackett.Common.csproj
- src/Jackett.Server/Jackett.Server.csproj
- src/Jackett.Test/Jackett.Test.csproj
- src/Jackett.Tray/Jackett.Tray.csproj
- src/Jackett.Updater/Jackett.Updater.csproj
Minor update from .NET Core 3.0. .NET Core 3.1 is the LTS version
> Update to .NET Core 3.1

- src/Jackett.Common/Indexers/BaseIndexer.cs
- src/Jackett.Common/Indexers/TVstore.cs
- src/Jackett.Common/Models/TorznabCapabilities.cs
- src/Jackett.Server/Controllers/ResultsController.cs
- Add support for IMDB based search for TV.
- Add support of imdb search to TVStore
@kaso17 or @flightlevel  can you review it before merge?
> ImdbTVSearchSupport added for c# based indexers

- src/DateTimeRoutines/DateTimeRoutines.csproj
- src/Jackett.Common/Jackett.Common.csproj
- src/Jackett.Test/Jackett.Test.csproj
csproj conversion tool picked these up
> Minor csproj tidy up

- src/Jackett.Common/Definitions/crazyscorner.yml
> Crazyscorner: Fix error when starting Jackett

- src/Jackett.Common/Definitions/hachede.yml
Site adds new torrents categories
> Update categories from Hachede

- src/Jackett.Common/Indexers/DivxTotal.cs
Most of the changes are cosmetic.
> divxtotal: fix search with 0 results

- src/Jackett.Common/Indexers/DivxTotal.cs
Merge after => #6908
Tested in Jackett, Sonarr and Radarr
> divxtotal: add support for sonarr / radarr. resolves #6869

- src/Jackett.Common/Definitions/nitro.yml
We should add trackers like in https://github.com/Jackett/Jackett/blob/ab2e41df75b9a06e6e84e2a5c84eddaa27ac2246/src/Jackett.Common/Definitions/ibit.yml#L54
> nitro: fix download link. resolves #6926

- src/Jackett.Server/Jackett.Server.csproj
- src/Jackett.Tray/Jackett.Tray.csproj
- src/Jackett.Tray/Main.cs
- src/Jackett.Updater/Jackett.Updater.csproj
Removing only COM reference to get closer to having Jackett to run on .NET Core for Windows
> Remove COM reference for .NET Core

- build.cake
- src/Jackett.Test/Jackett.Test.csproj
- src/Jackett.Test/WebUtilityHelpersTests.cs
Update Test project so that tests can run on both full framework and .net core
> Make tests run on .NET Core as well

- src/Jackett.Common/Indexers/AnimeBytes.cs
> Fix synonym setting AB

- src/Jackett.Common/Content/custom.css
- src/Jackett.Common/Content/custom.js
- src/Jackett.Common/Content/custom_mobile.css
- src/Jackett.Common/Content/index.html
> webui: improve search filter and pagination style

- src/Jackett.IntegrationTests/DashboardTests.cs
- src/Jackett.IntegrationTests/Jackett.IntegrationTests.csproj
- src/Jackett.IntegrationTests/WebDriverFactory.cs
- src/Jackett.sln
Add some basic integration tests for Jackett
> Add Integration Tests

- src/Jackett.Common/Indexers/DivxTotal.cs
> divxtotal: fix error when the search has exactly 15 results

- .editorconfig
- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- src/Jackett.sln
This pull request creates a .editorconfig file to enforce a consistent code style solution wide as well as updating the documentation to reflect this change for code contributors. There are updates to the Issue template and added details for contributors filing bug reports on the issues tab.
I've also cleaned up the README a bit while I was working on this. I found that GitHub supports turn down menus in Markdown files and used that to collapse supported trackers in order to make the whole file easier to read.
Please review the proposed code style to approve or modify before merging this request. Once the code style is finalized, I'll run `dotnet format` and submit the Pull Request that formats the existing solution code appropriately.
> Add code style guide and update documentation to reflect changes

- src/Jackett.Common/Indexers/InternetArchive.cs
> internetarchive: fix array title

- README.md
- src/Jackett.Common/Definitions/theresurrection.yml
Added support for german private tracker The Resurrection.
> [New Tracker] The Resurrection

- src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs
- src/Jackett.Common/Indexers/Avistaz.cs
Reverts https://github.com/Jackett/Jackett/commit/b9b5b3a442b09a5ab1c1b7815f0d3a81aaef1f38 per request in #2520
Fixes #7167
> Remove string sanitizing from search query

- src/Jackett.Common/Definitions/theresurrection.yml
Add upload factor, download factor and minimum seedtime for results from The Resurrection
> theresurrection: add additional tracker information

- src/Jackett.Common/Indexers/NewRealWorld.cs
> Fix parsing for NRW tracker

- src/Jackett.Common/Services/UpdateService.cs
- src/Jackett.Tray/Main.cs
Using the url shortcut wasn't reliable
> Use ComImport to create shortcut

- src/Jackett.Server/Services/ServerService.cs
> Don't check cert store on Mono 6

- azure-pipelines.yml
ChromeDriver is now already present on Azure Linux VM's
> No longer manually install ChromeDriver

- src/Jackett.Common/Definitions/btschool.yml
Got all kinds of error using username and password
> btschool: use cookie

- src/Jackett.Common/Models/IndexerConfig/ConfigurationDataCookie.cs
> core: improve cookie configuration help

- src/Jackett.Common/Content/custom.css
- src/Jackett.Common/Content/custom_mobile.css
- src/Jackett.Common/Content/index.html
- src/Jackett.Common/Content/libs/handlebarsmoment.js
- src/Jackett.Common/Content/login.html
> webui: improve server logs modal

- src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs
> Convert Abract/AvistazTracker to AngleSharp

- src/Jackett.Common/Indexers/AnimeTorrents.cs
> Convert AnimeTorrents to AngleSharp

- src/Jackett.Common/Indexers/BakaBT.cs
> Convert BakaBT to AngleSharp

- src/Jackett.Common/Indexers/BitCityReloaded.cs
> Convert BitCityReloaded to AngleSharp

- src/Jackett.Common/Indexers/FileList.cs
> Convert FileList to Angle Sharp

- src/Jackett.Common/Indexers/DigitalHive.cs
> Convert DigitalHive to AngleSharp

- src/Jackett.Common/Indexers/BitHdtv.cs
> Convert BitHdtv to AngleSharp

- src/Jackett.Common/Indexers/HDSpace.cs
Tested and working on my account. I left in the old csQuery Code as hints for the other trackers we're trying to convert to remove csQuery. There's almost a 1-to-1 relationship in functions that should make the process fairly easy.
> Convert HD-Space from csQuery to AngleSharp

- src/Jackett.Common/Indexers/BB.cs
> Convert BB to AngleSharp

- src/Jackett.Common/Indexers/IPTorrents.cs
> Convert IPTorrents to AngleSharp

- src/Jackett.Common/Indexers/FunFile.cs
> Convert FunFile to AngleSharp

- src/Jackett.Common/Indexers/Fuzer.cs
> Convert Fuzer to AngleSharp

- src/Jackett.Common/Indexers/GimmePeers.cs
> Convert GimmePeers to AngleSharp

- src/Jackett.Common/Indexers/HDOlimpo.cs
> Convert HDOlimpo to AngleSharp

- src/Jackett.Common/Indexers/HDTorrents.cs
> Convert HDTorrents to AngleSharp

- src/Jackett.Common/Indexers/Hebits.cs
> Convert Hebits to AngleSharp

- src/Jackett.Common/Indexers/ImmortalSeed.cs
> Convert ImmortalSeed to AngleSharp

- src/Jackett.Common/Indexers/MoreThanTV.cs
> Convert MoreThanTV to AngleSharp

- src/Jackett.Common/Indexers/myAmity.cs
> Convert myAmity to AngleSharp

- src/Jackett.Common/Indexers/NCore.cs
> Convert NCore to AngleSharp

- src/Jackett.Common/Indexers/PirateTheNet.cs
Tested #7292
Note: The categories didn't work before this PR. I created another issue for that => #7381
> Convert PirateTheNet to AngleSharp

- src/Jackett.Common/Indexers/TorrentDay.cs
> Convert TorrentDay to AngleSharp

- src/Jackett.Common/Indexers/TorrentLeech.cs
> Convert TorrentLeech to AngleSharp

- src/Jackett.Common/Indexers/TVstore.cs
> Convert TVStore to AngleSharp

- src/Jackett.Common/Indexers/TorrentHeaven.cs
> Convert TorrentHaven to AngleSharp

- src/Jackett.Common/Indexers/TorrentSyndikat.cs
> Convert TorrentSyndikat to AngleSharp

- src/Jackett.Common/Indexers/TorrentBytes.cs
> Convert TorrentBytes to AngleSharp

- src/Jackett.Common/Indexers/SpeedCD.cs
> Convert SpeedCD to AngleSharp

- src/Jackett.Common/Indexers/Partis.cs
> Convert Partis to AngleSharp

- src/Jackett.Common/Indexers/RevolutionTT.cs
> Convert RevolutionTT to AngleSharp

- src/Jackett.Common/Indexers/Pretome.cs
> Convert Pretome to AngleSharp

- src/Jackett.Common/Indexers/NewRealWorld.cs
> Convert NewRealWorld to AngleSharp

- src/Jackett.Common/Indexers/SceneTime.cs
> Convert SceneTime to AngleSharp

- src/Jackett.Common/Indexers/XSpeeds.cs
> Convert XSpeeds to AngleSharp

- src/Jackett.Common/Indexers/Shazbat.cs
> Convert Shazbat to AngleSharp

- src/Jackett.Common/Definitions/btsow.yml
https://github.com/Jackett/Jackett/issues/7280
https://btsow.club/
> BTSOW - New Domain

- src/Jackett.Common/Indexers/Abnormal.cs
Untested #7292
@garfield69 please, test this one.
> Convert Abnormal to AngleSharp

- src/Jackett.Common/Jackett.Common.csproj
- src/Jackett.IntegrationTests/Jackett.IntegrationTests.csproj
- src/Jackett.Server/Jackett.Server.csproj
- src/Jackett.Test/Jackett.Test.csproj
All packages except Automapper are now on latest versions
> Package update

- src/Jackett.Common/Indexers/Norbits.cs
Untested #7292
@garfield69 please, test this one. I think we are removing the first row/torrent. Could you check?
> Convert Nordbits to AngleSharp

- src/Jackett.Common/Indexers/Nordicbits.cs
Untested #7292
@garfield69 please, test this one
UPDATE: I think we are removing the first row/torrent. Could you check?
> Convert Nordicbits to AngleSharp

- src/Jackett.Common/Jackett.Common.csproj
- src/Jackett.Server/Jackett.Server.csproj
- src/Jackett.Service/Jackett.Service.csproj
- src/Jackett.Test/Jackett.Test.csproj
- src/Jackett.Tray/Jackett.Tray.csproj
- src/Jackett.Updater/Jackett.Updater.csproj
- src/Jackett.Updater/Program.cs
This is the last PR. It will pass checks after other PRs are merged.
@cadatoiva I can't find the option to remove unused dependencies in Rider. I think this is ok but take a look.
> Remove CsQuery and use AngleSharp instead. Closes #7292

- src/Jackett.Common/Indexers/NCore.cs
@cadatoiva Do you think this is going to work?
> ncore: fix error caused by #7378 Resolves #7430

- src/Jackett.Common/Indexers/BJShare.cs
Add details to release when its from the last 24h list; Setted category 4 to TorznabCatType.PCGames; Changed category parsing on 24h list; Added parsing from 4K to 2160p.
Signed-off-by: Christian Franchin <christianfranchin@gmail.com>
> Add details to release when its from the last 24h list

- src/Jackett.Common/Indexers/IPTorrents.cs
> Fix null reference after conversion to AngleSharp

- src/Jackett.Common/Indexers/NCore.cs
> Fix parse errors in NCore

- src/Jackett.Common/Indexers/HDTorrents.cs
Tested with the provided HTML.
> HD-Torrents: fix error caused by #7373 Resolves #7426

- README.md
- src/Jackett.Common/Definitions/fantasticheaven.yml
> Add Fantastic Heaven

- src/Jackett.Common/Indexers/GimmePeers.cs
> Fix invalid CSS selector

- src/Jackett.Common/Indexers/NCore.cs
Bugs found:
* Wrong regex `Regex.Match(lastPageLink, @"(?<=[\?,&]oldal=)(\d+)(?=&)")`
* Banner is optional `var banner = row.QuerySelector("img.infobar_ico")?.GetAttribute("onmouseover")`
* Wrong date replacement `row.QuerySelector(".box_feltoltve2").InnerHtml.Replace("<br>", " ")`
> Ncore: fix error caused by #7378 Resolves #7444

- src/Jackett.Common/Indexers/ImmortalSeed.cs
> ImmortalSeed: fix error caused by #7375 Resolves #7461

- src/Jackett.Common/Indexers/BitCityReloaded.cs
> Bit-City: fix error caused by #7357 Resolves #7459

- src/Jackett.Common/Indexers/FileList.cs
* Fix description parsing
* Fix grabs value
> Filelist: fix error caused by #7360 and added grabs. Resolves #7474

- src/Jackett.Common/Indexers/SceneTime.cs
Fix exception when the results table is empty.
> SceneTime: fix error caused by #7394 Resolves #7475

- src/Jackett.Common/Indexers/Shazbat.cs
> Fix parse errors with Shazbat

- src/Jackett.Common/Indexers/Fuzer.cs
- src/Jackett.Common/Indexers/Hebits.cs
> Fix parse errors in Fuzer and Hebits

- src/Jackett.Common/Definitions/speedtorrentreloaded.yml
Speedtorrent Reloaded updated its source.
Unfortunately haven't found a solution to prevent the trackers session check other than doing a cookie login.
#7517
> Speedtorrent Reloaded: Update to new tracker source

- src/Jackett.Common/Indexers/PassThePopcorn.cs
> Fix Freeleech check in PassThePopcorn

- src/Jackett.Common/Indexers/TorrentBytes.cs
> TorrentBytes: fix title bug

- azure-pipelines.yml
Hopefully will help with github publish failures, quite a few debug statements there...
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/GitHubReleaseV0/operations/Action.ts
> Pipeline: Add debug logging

- src/Jackett.Common/Indexers/MoreThanTV.cs
* Add Others category
Part of #4859
> morethantv: add imdb search and others category

- src/Jackett.Common/Indexers/PirateTheNet.cs
* Add IMDB search #4859
* Fix categories #7381
> piratethenet: add imdb search and fix categories. resolves #7381

- src/Jackett.Common/Indexers/BitHdtv.cs
* Fix exception when editing configuration
* Add notice to increase torrents per page
Part of #4859
> bithdtv: add imdb search

- src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs
* Add banner / poster
Tested in privatehd only.
Part of #4859
> avistaz, cinemaz, privatehd: add imdb search and banner

- src/Jackett.Common/Indexers/SolidTorrents.cs
This site experiences downtimes frequently and the retries make it worse.
> solidtorrents: remove retries

- src/Jackett.Common/Definitions/vizuk.yml
Add new category "BDRip 1080p x265"
> Update categories for Vizuk

- src/Jackett.Common/Definitions/downloadville.yml
No more result if no referer
Should fix #7514
I don't know if we can build from variable ( url , etc ) , It could be better.
> [Downloadville] add a fake referer in search

- src/Jackett.Common/Indexers/MoreThanTV.cs
> morethantv: add banner and description. resolves #7594

- src/Jackett.Common/Indexers/Shazbat.cs
> shazbat: fix parser. resolves #7604

- src/Jackett.Common/Indexers/Torrentseeds.cs
Fix recognisition of required relogin.
> TorrentSeeds: Fix Re-Login

- src/Jackett.Common/Indexers/FunFile.cs
The user will see this message instead of the null pointer => `Download links not found. Make sure you can download from the website.`
> funfile: handle disabled download links. resolves #7436

- src/Jackett.Common/Indexers/BitHdtv.cs
> bithdtv: improve imdb search. resolves #7596

- src/Jackett.Common/Utils/Clients/HttpWebClient.cs
- src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
- src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
- src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
Also implements "Don't Repeat Yourself" (DRY) principles by moving duplicated proxy related static functions/vars into parent class.
Fixes #7411
> core: remove proxy when cleared in all cases. resolves #7411

- src/Jackett.Common/Indexers/EliteTracker.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataEliteTracker.cs
Tested
* Add missing categories
* Code clean up
Related #4859
> elitetracker: add imdb search and fix categories

- src/Jackett.Common/Definitions/bitturk.yml
- src/Jackett.Common/Definitions/blutopia.yml
- src/Jackett.Common/Definitions/datascene.yml
- src/Jackett.Common/Definitions/spiritofrevolution.yml
- src/Jackett.Common/Definitions/torrentland.yml
- src/Jackett.Common/Definitions/torrentlt.yml
- src/Jackett.Common/Indexers/BitHdtv.cs
- src/Jackett.Common/Indexers/EliteTracker.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataEliteTracker.cs
- src/Jackett.Common/Utils/Clients/HttpWebClient.cs
- src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
- src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
- src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
Makes sure the feature branch doesn't fall too far behind the master branch.
> Merge master into web-client feature

- src/Jackett.Common/Indexers/HDSpace.cs
> HdSpace: Add IMDB support.

- src/Jackett.Common/Indexers/EliteTracker.cs
> elitetracker: fix parsing error. resolves #7675

- src/Jackett.Common/Indexers/GimmePeers.cs
This should do it. Did some of the safer refactorings while I was at it.
> gimme-peers: fix parse error on zero results resolves #7678

- src/Jackett.Common/Indexers/EpubLibre.cs
> epublibre: add server overloaded message

- src/Jackett.Common/Indexers/Norbits.cs
- src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataNorbits.cs
Adds an option for searching in torrents description.
> [FEATURE] Add fullsearch option for norbits

- src/Jackett.Common/Indexers/EpubLibre.cs
- src/Jackett.Common/Utils/Clients/WebClient.cs
- src/Jackett.Common/Utils/Clients/WebClientResult.cs
- src/Jackett.Server/Helper.cs
Not all commits made it into the rebase for some reason, this is just re-adding those missed commits to the feature branch so the changes aren't lost
> Replay Remove automapper commit after rebase.

- src/Jackett.Common/Utils/Clients/HttpWebClient.cs
- src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
- src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs
- src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs
- src/Jackett.Common/Utils/Clients/WebClient.cs
- src/Jackett.Test/Jackett.Test.csproj
Lost commit 2 of 2 after rebase of feature branch
> core: move identical functions up to base WebClient instance. Replay #7691

- src/Jackett.Common/Indexers/HDTorrents.cs
I've also refactored the remaining code. Tested and working.
> hd-torrents: Add global freeleech check. resolves #7734

- src/Jackett.Common/Indexers/DigitalHive.cs
I was able to source the error from the Trace in #7755. It would still be helpful to get the full html or an invite to allow us to revamp the rest of the code.
> DigitalHive: Fix error in configure script. Resolves #7755

- src/Jackett.Common/Indexers/720pier.cs
- src/Jackett.Common/Indexers/AniDub.cs
- src/Jackett.Common/Indexers/Feeds/AnimeTosho.cs
- src/Jackett.Common/Indexers/Feeds/BaseFeedIndexer.cs
- src/Jackett.Common/Indexers/Feeds/BaseNewznabIndexer.cs
- src/Jackett.Common/Indexers/TorrentNetwork.cs
- src/Jackett.Common/Models/DTO/TorznabRequest.cs
- src/Jackett.Common/Services/IndexerManagerService.cs
- src/Jackett.Common/Utils/Extensions.cs
- src/Jackett.Server/Controllers/IndexerApiController.cs
- src/Jackett.Server/Controllers/ResultsController.cs
This removes the string extensions class in favor of inlining the code it extracted.
> Remove string extensions in favor of explicit conversion

- src/Jackett.Common/Indexers/Pretome.cs
> pretome: add imdb search and code clean up

- src/Jackett.Common/Indexers/PolishTracker.cs
> polishtracker: add imdb search and code clean up

- src/Jackett.Common/Indexers/720pier.cs
This completely revamps the 720 pier search engine to handle searches much better. It should resolve all existing issues as outlined in the two linked issues.
Tested and working
> 720-pier: Update parsing. Resolves #7877 resolves #7190

- src/Jackett.Common/Definitions/badasstorrents.yml
> BadassTorrents: fix error while parsing row. Resolves #7919

- src/Jackett.Common/Indexers/FunFile.cs
> funfile: add imdb search and code clean up

- src/Jackett.Common/Indexers/Newpct.cs
* Fixed brute force approach, we were doing tens of useless requests (the same request to the same domain or to the alternative domain).
* Fixed alternative links, now the user can chose (added one more mirror)
* Removed cache, not working and using memory
* Removed 250 lines of code
Tested.
@cadatoiva the code of this trackers is s**t, please just focus in bugs or missing code, not in the code style. The purpose of this PR is to fix important issues, not all the issues. I will open more PRs in the future with more code improvements.
> newpct: huge refactor, fix brute force, alternative links, remove cache

- src/Jackett.Common/Indexers/TorrentBytes.cs
> torrentbytes: add imdb search

- src/Jackett.Common/Indexers/AwesomeHD.cs
Fix https://github.com/Jackett/Jackett/pull/7827#issuecomment-605625125
> awesomehd: fix series search and audio track

- src/Jackett.Common/Indexers/SpeedCD.cs
- src/Jackett.Common/Models/IndexerConfig/ConfigurationDataCookie.cs
* Fix search with categories
* Add alternative domain https://speed.click/
* Code clean up
Tested
> speedcd: fix category search and add alternative domain

- src/Jackett.Common/Definitions/piratbit.yml
- src/Jackett.Common/Definitions/piratbitl.yml
Tested without login, but I don't see it making a difference
> piratbit: category fix. Resolves #7965

- src/Jackett.Common/Indexers/TVstore.cs
I kept the current multi-page processing code relatively intact. Some of the offsets were incorrect though, and so I've updated them. I also tried to make the code much easier to follow, as I had a really hard time understanding what exactly every part was doing at first. These changes make the code look and feel more like our other C# trackers. Tested and working thanks to @garfield69 for letting me use your account to update this. Once the PR is merged you can change your credentials accordingly.
> TvStore: refactor and update

- src/Jackett.Common/Indexers/Abnormal.cs
- src/Jackett.Common/Indexers/Abstract/CouchPotatoTracker.cs
- src/Jackett.Common/Indexers/AwesomeHD.cs
- src/Jackett.Common/Indexers/BitHdtv.cs
- src/Jackett.Common/Indexers/EliteTracker.cs
- src/Jackett.Common/Indexers/FunFile.cs
- src/Jackett.Common/Indexers/Fuzer.cs
- src/Jackett.Common/Indexers/HDBitsApi.cs
- src/Jackett.Common/Indexers/HDTorrents.cs
- src/Jackett.Common/Indexers/IPTorrents.cs
- src/Jackett.Common/Indexers/Norbits.cs
- src/Jackett.Common/Indexers/Nordicbits.cs
- src/Jackett.Common/Indexers/PassThePopcorn.cs
- src/Jackett.Common/Indexers/PiXELHD.cs
- src/Jackett.Common/Indexers/PirateTheNet.cs
- src/Jackett.Common/Indexers/PolishTracker.cs
- src/Jackett.Common/Indexers/Rarbg.cs
- src/Jackett.Common/Indexers/SceneHD.cs
- src/Jackett.Common/Indexers/SpeedCD.cs
- src/Jackett.Common/Indexers/Superbits.cs
- src/Jackett.Common/Indexers/TorrentSyndikat.cs
- src/Jackett.Common/Indexers/Torrentscsv.cs
- src/Jackett.Common/Indexers/Xthor.cs
- src/Jackett.Common/Indexers/digitalcore.cs
- src/Jackett.Common/Indexers/pornolab.cs
- src/Jackett.Common/Indexers/yts.cs
This PR doesn't change current features, just code clean up.
> core: remove virtual member calls (part 1)

- src/Jackett.Common/Definitions/ilcorsaronero.yml
Resolves #8013
Also removed wrong proxy (whoops...).
> Il Corsaro Nero: domain change. Resolves #8013

- src/Jackett.Common/Definitions/cpasbienclone.yml
My fork wasn't up to date, hence the other 'changes'. Hope that's the right way to do things. Will update when this and the other PR are closed.
> cpasbienclone: change search. Resolves #8016

- src/Jackett.Common/Indexers/IPTorrents.cs
* Add SupportsImdbTVSearch
* Fix 4k category
* Remove files code, not available in the website
* Add description
* Add configuration advice
* Code cleanup
Tested
> iptorrents: some fixes and code cleanup
