Jackett/Jackett

src/Jackett.Common/Indexers/TorrentDay.cs
* Add SupportsImdbTVSearch
* Code cleanup
Tested
=> torrentday: some fixes and code cleanup

src/Jackett.Common/Indexers/TorrentLeech.cs
=> torrentleech: code cleanup

src/Jackett.Common/Definitions/exttorrents.yml
Passes test, searches complete, magnets download.
Straight mirror; no popups or other nasties.
=> exttorrents: add proxy

src/Jackett.Common/Indexers/NewRealWorld.cs
detail link was missing quotes and some td's moved
Fixes issue #7314
=> newrealworld: some fixes. resolves #7314

src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/index.html
=> webui: add negative filtering in search results. resolves #7660

src/Jackett.Common/Definitions/torrenting.yml
Fix login handling for torrenting tracker
=> Fix login handling for torrenting tracker

src/Jackett.Common/Indexers/TorrentHeaven.cs
no They added an uploader line into the same element, no good way to remove it without search and remove.
=> TorrentHaven: Fix date parsing. Resolves #7983

src/Jackett.Common/Indexers/TorrentDay.cs
I can't test this very well because I always get the callenge in all domains.
With this fix the configuration dialog will open at least.
=> torrentday: fix login without recaptcha. resolves #8057

src/Jackett.Common/Definitions/btgigs.yml
Added new functions;
- Error when important news waiting for read
- Read all important news after loggin
- New option to add POLISH to title when is use polish category
=> Btgigs improve

src/Jackett.Common/Indexers/AwesomeHD.cs, src/Jackett.Common/Indexers/BitHdtv.cs, src/Jackett.Common/Indexers/EliteTracker.cs, src/Jackett.Common/Indexers/FunFile.cs, src/Jackett.Common/Indexers/HDSpace.cs, src/Jackett.Common/Indexers/HDTorrents.cs, src/Jackett.Common/Indexers/IPTorrents.cs, src/Jackett.Common/Indexers/PolishTracker.cs, src/Jackett.Common/Indexers/Pretome.cs, src/Jackett.Common/Indexers/SpeedCD.cs, src/Jackett.Common/Indexers/TVstore.cs, src/Jackett.Common/Indexers/TorrentBytes.cs, src/Jackett.Common/Indexers/TorrentDay.cs, src/Jackett.Common/Indexers/TorrentLeech.cs
=> core: disable SupportsImdbTVSearch in all trackers due to #8107

src/Jackett.Common/Indexers/HDTorrents.cs
=> hdtorrents: add banner and code cleanup

src/Jackett.Common/Indexers/Anidex.cs
=> anidex: fix ddos protection bypass. resolves #8095

src/Jackett.Common/Indexers/CardigannIndexer.cs, src/Jackett.Common/Models/TorznabQuery.cs
=> CardigannIndexer: fix andmatch filter to respect keywordsfilters (#7988)

src/Jackett.Common/Definitions/casatorrent.yml, src/Jackett.Common/Indexers/CardigannIndexer.cs, src/Jackett.Common/Models/IndexerDefinition.cs
=> Add query url separator option for Cardigann indexer

src/Jackett.Common/Indexers/BaseIndexer.cs
The cookie parsing regex was wrong.
Example: `_xsrf=QmE=|158660536933979824054536a1607a318e`
Old code key = `_xsrf=QmE`
New code key = `_xsrf`
This change will remove old cookies in the next search request.
=> core: fix cookie storage. resolves #8126

src/Jackett.Common/Indexers/SpeedCD.cs
=> speedcd: fix login. resolves #8151

src/Jackett.Common/Definitions/piratbit.yml
Fix TV shows & movies search in Sonarr and Radarr.
=> PiratBit: fix TV shows search, add "strip russian letters" option

src/Jackett.Common/Definitions/rutor.yml, src/Jackett.Common/Definitions/thepiratebay.yml
tpb.root.yt and rutor.root.yt both down at the moment
=> tpb, rutor: remove down root.yt proxies

src/Jackett.Common/Definitions/monova.yml
Also upped it to using 4 pages instead of 1
Thanks to @garfield69 for all the help
=> monova: improve search - andmatch & keywordfilters. Resolves #8183

src/Jackett.Common/Definitions/torrentkitty.yml
=> torrentkitty: add .vip official proxy

src/Jackett.Common/Indexers/InternetArchive.cs
=> internetarchive: fix torrents without title

src/Jackett.Common/Indexers/FileList.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataFileList.cs
-implemented logic for calling filelist api
=> FileList: Add API functionality. Resolves #7004 Resolves #5190

src/Jackett.Common/Definitions/hdcity.yml
Add support for global freeleech flag
=> Support freeleech flag on hdcity

src/Jackett.Common/Definitions/topnow.yml
=> topnow: torrent URL change

src/Jackett.Common/Definitions/torrentgalaxyorg.yml
Official proxies, tested and working - https://proxygalaxy.pw/
=> torrentgalaxyorg: restore official proxies

README.md, src/Jackett.Common/Indexers/Milkie.cs, src/Jackett.Common/Indexers/milkie.cs
=> milkie: initial implementation

src/Jackett.Common/Models/IndexerConfig/ConfigurationData.cs
This reverts commit e83ed96194914536068a9ab51da0ac5a45abf8cb.
=> Revert "Core: remove ItemType enum in favor of pattern matching (#8277)"

src/Jackett.Common/Indexers/Milkie.cs
Requested changes in #8289
I can change other parts of the code because I can't test it.
=> milkie: cosmetic changes

src/Jackett.Common/Jackett.Common.csproj
@garfield69 this should fix most issues related to `Clearance failed after 30 attempt(s)`
=> core: fix cloudflare challenge

src/Jackett.Common/Indexers/AwesomeHD.cs
=> awesomehd: remove the year from the search

src/Jackett.Common/Indexers/Nordicbits.cs
=> nordicbits: fix title, imdb search and dead torrents. resolves #8178

src/Jackett.Common/Indexers/Newpct.cs
Tested.
Only the new code follows the code style. There is still work to do.
=> newpct: huge refactor. resolves #5618 resolves #7928 resolves #8193

src/Jackett.Common/Indexers/SpeedCD.cs
They changed the login form again. Now it's more complex to solve because they have several steps, reCaptcha and Google cookie.
Tested
=> speedcd: cookie login. resolves #8366

src/Jackett.Common/Definitions/32pages.yml
Fixes pain of 2fa + dynamic IP
=> 32p: add option to not lock session to IP address

src/Jackett.Common/Indexers/SceneTime.cs
=> scenetime: check expired cookie. resolves #8359

src/Jackett.Common/Indexers/DivxTotal.cs
=> divxtotal: fix download link

src/Jackett.Common/Indexers/MejorTorrent.cs
=> mejortorrent: fix download link and code clean up

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/btdb.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/extratorrent-ag.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/ilcorsaronero.yml, src/Jackett.Common/Definitions/itorrent.yml, src/Jackett.Common/Definitions/kickasstorrent-kathow.yml, src/Jackett.Common/Definitions/kickasstorrent.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/magnetdl.yml, src/Jackett.Common/Definitions/monova.yml, src/Jackett.Common/Definitions/pirateiro.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxyorg.yml, src/Jackett.Common/Definitions/torrentz2.yml, src/Jackett.Common/Definitions/zooqle.yml
also added pirateiro official proxy *.eu listed on their site - untested due to continuing site issue
=> assorted: update unblockit proxies to *.me

src/Jackett.Common/Definitions/ebooks-shares.yml
=> ebooks-shares: add auto relogin

src/Jackett.Common/Definitions/32pages.yml
https://github.com/Jackett/Jackett/pull/8491#issuecomment-623000672
=> 32p: fix typo preventing remember login

src/Jackett.Common/Definitions/cinemageddon.yml
#4859
fix categories
tried to support dl/ul bonuses, but processing all of them correctly probably needs C#
=> cinemageddon: support imdbid

src/Jackett.Common/Indexers/HorribleSubs.cs
=> horriblesubs: fix torrents without download link

src/Jackett.Common/Definitions/anirena.yml, src/Jackett.Common/Definitions/anisource.yml, src/Jackett.Common/Definitions/btnext.yml, src/Jackett.Common/Definitions/datascene.yml, src/Jackett.Common/Definitions/ehentai.yml, src/Jackett.Common/Definitions/frozenlayer.yml, src/Jackett.Common/Definitions/gay-torrents.yml, src/Jackett.Common/Definitions/hdcity.yml, src/Jackett.Common/Definitions/hdme.yml, src/Jackett.Common/Definitions/hdspain.yml, src/Jackett.Common/Definitions/kickasstorrent-kathow.yml, src/Jackett.Common/Definitions/nnm-club.yml, src/Jackett.Common/Definitions/nyaasi.yml, src/Jackett.Common/Definitions/p2pbg.yml, src/Jackett.Common/Definitions/rutracker-ru.yml, src/Jackett.Common/Definitions/sukebei-pantsu.yml, src/Jackett.Common/Definitions/sukebeinyaasi.yml, src/Jackett.Common/Definitions/torrentfactory.yml, src/Jackett.Common/Definitions/torrentgalaxyorg.yml, src/Jackett.Common/Definitions/unionfansub.yml, src/Jackett.Common/Definitions/xfsub.yml, src/Jackett.Common/Definitions/zelkaorg.yml, src/Jackett.Common/Definitions/ztracker.yml
error    too many spaces before comma  (commas)
error    too many spaces after comma  (commas)
Rebase after part 1 #8581
=> core: validate yaml definitions (yamllint part 2 #8575)

src/Jackett.Common/Definitions/32pages.yml, src/Jackett.Common/Definitions/academictorrents.yml, src/Jackett.Common/Definitions/anirena.yml, src/Jackett.Common/Definitions/beyond-hd-oneurl.yml, src/Jackett.Common/Definitions/bibliotik.yml, src/Jackett.Common/Definitions/concen.yml, src/Jackett.Common/Definitions/crazyhd.yml, src/Jackett.Common/Definitions/eniahd.yml, src/Jackett.Common/Definitions/losslessclub.yml, src/Jackett.Common/Definitions/metal-iplay-ro.yml, src/Jackett.Common/Definitions/mvgroupforum.yml, src/Jackett.Common/Definitions/mvgroupmain.yml, src/Jackett.Common/Definitions/myspleen.yml, src/Jackett.Common/Definitions/onlineselfeducation.yml, src/Jackett.Common/Definitions/p2pelite.yml, src/Jackett.Common/Definitions/shellife.yml, src/Jackett.Common/Definitions/snowpt.yml, src/Jackett.Common/Definitions/sukebeinyaasi.yml, src/Jackett.Common/Definitions/tasmanit.yml, src/Jackett.Common/Definitions/tekno3d.yml, src/Jackett.Common/Definitions/theplace.yml, src/Jackett.Common/Definitions/tribalmixes.yml, src/Jackett.Common/Definitions/twilightszoom.yml, src/Jackett.Common/Definitions/wihd.yml
error    trailing spaces  (trailing-spaces)
=> core: validate yaml definitions (yamllint part 4 #8575)

src/Jackett.Common/Definitions/cpasbienclone.yml, src/Jackett.Common/Definitions/cztorrent.yml, src/Jackett.Common/Definitions/galeriens.yml, src/Jackett.Common/Definitions/ilcorsaronero.yml, src/Jackett.Common/Definitions/nyaa-pantsu.yml, src/Jackett.Common/Definitions/nyaasi.yml, src/Jackett.Common/Definitions/sktorrent.yml, src/Jackett.Common/Definitions/sukebei-pantsu.yml, src/Jackett.Common/Definitions/sukebeinyaasi.yml, src/Jackett.Common/Definitions/thepiratebay.yml, src/Jackett.Common/Definitions/tokyotosho.yml, src/Jackett.Common/Definitions/uniongang.yml, src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
error    too many spaces inside brackets  (brackets)
=> core: validate yaml definitions (yamllint part 5 #8575)

src/Jackett.Common/Definitions/btdb.yml, src/Jackett.Common/Definitions/itorrent.yml, src/Jackett.Common/Definitions/kickasstorrent.yml, src/Jackett.Common/Definitions/monova.yml, src/Jackett.Common/Definitions/pirateiro.yml
can't test pirateiro in Jackett
=> unblockit.me proxies: updates

src/Jackett.Common/Definitions/ilcorsaronero.yml
Issues resolved on their end, so thank you to them - https://github.com/unblocked-pw/unblocked-pw.github.io/issues/10#issuecomment-626828637
Tested with Jackett, working fine.
=> ilcorsaronero: unblockit.me proxy fixed

src/Jackett.Common/Definitions/rutor.yml
http://rutor.info/torrent/472
Tested
=> rutor: add official domain *.is

src/Jackett.Common/Definitions/torrentgalaxyorg.yml
=> torrentgalaxyorg: add root.yt proxy

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/32pages.yml, src/Jackett.Common/Definitions/Bittorrentfiles.yml, src/Jackett.Common/Definitions/bigfangroup.yml, src/Jackett.Common/Definitions/bit-titan.yml, src/Jackett.Common/Definitions/btgigs.yml, src/Jackett.Common/Definitions/casstudiotv.yml, src/Jackett.Common/Definitions/crazyhd.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/extratorrent-ag.yml, src/Jackett.Common/Definitions/extratorrent-cd.yml, src/Jackett.Common/Definitions/frozenlayer.yml, src/Jackett.Common/Definitions/funkytorrents.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/hdtorrentsit.yml, src/Jackett.Common/Definitions/kinonavse100.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/parnuxi.yml, src/Jackett.Common/Definitions/pctorrent.yml, src/Jackett.Common/Definitions/pornorip.yml, src/Jackett.Common/Definitions/rutracker-ru.yml, src/Jackett.Common/Definitions/tenyardtracker.yml, src/Jackett.Common/Definitions/thepiratebay.yml, src/Jackett.Common/Definitions/torrentland.yml, src/Jackett.Common/Definitions/twilight.yml, src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml, yamllint.yml
This is the last change related to yamllint
=> assorted: cosmetic for yamllint part7

src/Jackett.Common/Indexers/NCore.cs
=> [Ncore]Correct link visible in name

src/Jackett.Common/Indexers/RuTracker.cs
=> rutracker: fix seeders. resolves #8629

src/Jackett.Common/Definitions/springsunday.yml
=> springsunday: fix row processing. resolves #8697

src/Jackett.Common/Indexers/Xthor.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataXthor.cs
For the issue #8759
Modele:
Without the option checked:
With the option:
=> [Xthor] Feature xthor replace vostfr english

src/Jackett.Common/Definitions/torrent9.yml
=> torrent9: restore *.me domain

src/Jackett.Common/Definitions/thefallingangels.yml
TFA changed their login page. Small adjustment to yml fixes login issue.
=> Fix login for thefallingangels. Resolves #8830

src/Jackett.Common/Definitions/xfsub.yml
=> xfsub: restore .org domain. Resolves #8351

src/Jackett.Common/Definitions/btdb.yml
https://btdb.io/ - ERR_NAME_NOT_RESOLVED
tested, working
=> btdb: change domain from .io to .eu

src/Jackett.Common/Indexers/TorrentDay.cs
We can't bypass Cloudflare by now.
=> torrentday: use cookie login method. resolves #8912

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/btdb.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/extratorrent-ag.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/ilcorsaronero.yml, src/Jackett.Common/Definitions/kickasstorrent-kathow.yml, src/Jackett.Common/Definitions/kickasstorrent.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/magnetdl.yml, src/Jackett.Common/Definitions/monova.yml, src/Jackett.Common/Definitions/pirateiro.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxyorg.yml, src/Jackett.Common/Definitions/torrentz2.yml, src/Jackett.Common/Definitions/zooqle.yml
pirateiro untested as per
btdb unblocked.bar et al restored as they're working again
ilcorsaronero unblockit isn't working, will likely be removed according to maintainers, and so has been legacy'd
limetorrents unblockninja fails at search and so has been legacy'd
torrentz2 unblockninja restored as working again
=> assorted: update unblockit proxies *.me to*.pw

src/Jackett.Common/Definitions/btsow.yml
=> btsow: new domain btsow.fun

src/Jackett.Common/Indexers/TVVault.cs
=> tv-vault: add imdb search and improve season search. #8508

src/Jackett.Common/Definitions/oxtorrent.yml
Untested due to - https://github.com/Jackett/Jackett/issues/5465#issuecomment-643699264
=> oxtorrent: new domain *.com to *.pw

install_service_macos
Various improvements to the macOS install script, currently focusing on adding debug info and better testing.
=> Improve macOS install with better debug

src/Jackett.Common/Definitions/torrentview.yml
tested, working
Also, happy #9000
=> torrentview: new domain *14.net

install_service_macos, src/Jackett.Common/Indexers/TorrentDay.cs, uninstall_jackett_macos
Creates a rather basic uninstall script for macOS users. Some tests have already been performed, yet I'd like some input as to the options of the script.
Should fix #8577
=> Create uninstall script for macOS

src/Jackett.Common/Indexers/RuTracker.cs
I think this is not going to resolve the problem entirely.
=> rutracker: catch exception in configuration loading. resolves #8998

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/btdb.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/kickasstorrent-kathow.yml, src/Jackett.Common/Definitions/kickasstorrent.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/magnetdl.yml, src/Jackett.Common/Definitions/monova.yml, src/Jackett.Common/Definitions/pirateiro.yml, src/Jackett.Common/Definitions/rutor.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxyorg.yml, src/Jackett.Common/Definitions/torrentz2.yml, src/Jackett.Common/Definitions/zooqle.yml
pirateiro untested
https://rutor.root.yt/ also re-added
=> assorted: update unblockit proxies *.pw to *.id

src/Jackett.Common/Definitions/btsow.yml
=> btsow: new domain *.space

src/Jackett.Common/Indexers/BJShare.cs
=> [Fix] BJShare re-login on every redirect

src/Jackett.Common/Definitions/btsow.yml
=> btsow: change domain *.site

src/Jackett.Common/Definitions/bitru.yml
http://bitru.org/browse.php?s=&rek=yes&sort= redirects to https://yandex.ru/
Tested, working
=> bitru: fix advertising setting

src/Jackett.Common/Definitions/btsow.yml
=> btsow: change domain *.cyou

src/Jackett.Common/Definitions/xbytes2.yml
=> xbytes2: auto re-login. resolves #9200

src/Jackett.Common/Definitions/btsow.yml
=> btsow: change domain *.monster

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/btdb.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/kickasstorrent-kathow.yml, src/Jackett.Common/Definitions/kickasstorrent.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/magnetdl.yml, src/Jackett.Common/Definitions/nyaasi.yml, src/Jackett.Common/Definitions/pirateiro.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxyorg.yml, src/Jackett.Common/Definitions/torrentz2.yml, src/Jackett.Common/Definitions/zooqle.yml
restored some other working proxies
=> assorted: update unblockit proxies *.id to *.win

src/Jackett.Common/Indexers/BakaBT.cs
Attempt to partially resolve #5664 regarding categories not being correctly set on results.
=> [BakaBT] Added categories for tracker

src/Jackett.Common/Definitions/oxtorrent.yml
No legacylink missed this time ;)
=> oxtorrent: change domain *.cc

src/Jackett.Common/Definitions/ethor.yml
Hi,
After update of ethor, title for almost of all release is empty.
=> Fix title for ethor don't working anymore

src/Jackett.Common/Definitions/bibliotik.yml, src/Jackett.Common/Indexers/BaseIndexer.cs, src/Jackett.Common/Indexers/CardigannIndexer.cs, src/Jackett.Common/Models/DTO/TorznabRequest.cs, src/Jackett.Common/Models/ReleaseInfo.cs, src/Jackett.Common/Models/ResultPage.cs, src/Jackett.Common/Models/TorznabCapabilities.cs, src/Jackett.Common/Models/TorznabQuery.cs
1. Adds backend support for the book-search newznab function.
1. Adds book-search support for bibliotek
1. Some more minor fixes for bibliotek - clean up login and extra attributes
=> Add support for book-search

src/Jackett.Common/Definitions/btsow.yml
=>  btsow: change domain *.casa

src/Jackett.Common/Definitions/scenerush.yml
Untested due to lack of account, but presumably there's no difference
=> scenerush: add *.com domain

src/Jackett.Common/Indexers/NewPCT.cs
=> newpct: add pctmix.com

src/Jackett.Common/Definitions/btsow.yml
=> btsow: change domain *.website

src/Jackett.Common/Definitions/sexypics.yml
keywordless search constantly redirected between http and https
/mp4/ has changed to /browse/
=> Sexy-Pics: fix keywordless search

src/Jackett.Common/Definitions/torrentgalaxyorg.yml
=> TorrentGalaxy.org: add official proxies

src/Jackett.Common/Indexers/PassThePopcorn.cs
This PR addresses an issue raised by https://github.com/Jackett/Jackett/issues/8927 on Permanent Link.
=> [Fix][Passthepopcorn] Fixed PTP's permanent link for each torrent

README.md, src/Jackett.Common/Indexers/Libble.cs
This is my first stab at adding a Jackett tracker.  Apologies in advance for the code crimes.
=> [Libble] Added initial Libble.me tracker support #3897

src/Jackett.Server/Services/ServerService.cs
https://github.com/linuxserver/docker-jackett/pull/105
=> core: show docker image version in the startup traces

src/Jackett.Common/Indexers/RevolutionTT.cs
* fix search with term
* add imdb search
* update categories
* simplify code
=> revolutiontt: rewrite from scratch. resolves #8972

src/Jackett.Common/Indexers/AlphaRatio.cs
https://github.com/Jackett/Jackett/issues/9689
=> [Feature][Alpharatio] Added minratio and minseedtime to alpharatio

src/Jackett.Common/Indexers/BroadcasTheNet.cs
This PR should improve the return results from BTN, solving https://github.com/Jackett/Jackett/issues/9086.
=> [Fix] Improved BTN's search

src/Jackett.Common/Indexers/BakaBT.cs
This PR resolves https://github.com/Jackett/Jackett/issues/9240
=> [Fix][BakaBT] Fixed BakaBT login

src/Jackett.Common/Definitions/elitetorrent-biz.yml
Improve scheme approach to a _Scene Style_ format. This improves the parse in *arr software.
**Previous:**
- Superman: Man of Tomorrow 1080p Spanish Latino
- Superman: Man of Tomorrow 720p English Subtitled VOSE
- Fringe S02E01 720p Spanish Castellano
- Fringe S02E01 720p English Subtitled VOSE
- Bill & Ted Face the Music BRS Spanish Latino
**Pull Request proposal:**
- Superman: Man of Tomorrow LATiN SPANiSH 1080p
- Superman: Man of Tomorrow English SPASUBS 720p
- Fringe S02E01 SPANiSH 720p
- Fringe S02E01 English SPASUBS 720p
- Bill & Ted Face the Music LATiN SPANiSH BRS
=> [EliteTorrent.Biz] Improve result scheme

src/Jackett.Common/Definitions/moviesdvdr.yml
**MoviesDVDR** always have the same quality, so I change the category to Movies/DVD and fix the quality in title always.
Improve scheme approach to a Scene Style format. This improves the parse in *arr software.
**Previous:**
- Power Rangers
- Spring
- Vientos De La Habana
- Vivir De Noche
- Vuelta A Casa De Mi Madre
- ¿Tenía Que Ser Él?
**Pull Request proposal:**
- Power Rangers SPANiSH DVDRiP XViD
- Spring MULTi English SPANiSH DVDRiP XViD
- Vientos De La Habana SPANiSH DVDRiP XViD
- Vivir De Noche MULTi English SPANiSH DVDRiP XViD
- Vuelta A Casa De Mi Madre MULTi SPANiSH FRENCH DVDRiP XViD
- ¿Tenía Que Ser Él? MULTi English SPANiSH DVDRiP XViD
=> [MoviesDVDR] Improve result scheme. Change category.

src/Jackett.Common/Indexers/BroadcasTheNet.cs
Resolves https://github.com/Jackett/Jackett/issues/9710.
@garfield69 Sorry, this time I've tested one of my changes.
=> [Broadcasthenet] Fixed an empty search bug

src/Jackett.Common/Indexers/GazelleGames.cs
Resolves https://github.com/Jackett/Jackett/issues/5790
=> [GazelleGames] Added option to search for groupnames only

src/Jackett.Common/Definitions/dariustracker.yml
@garfield69 I found a typo in the category type.
=> [Dariustracker] fixed category typo

src/Jackett.Common/Indexers/NewPCT.cs
This is a workaround. For complete solution see #9785
=> newpct: fix rss search. resolves #9778

README.md, src/Jackett.Common/Indexers/Animedia.cs
=> Added AniMedia public indexer

src/Jackett.Common/Indexers/ShizaProject.cs
Find that I forgot to remove some debug logging in previous MR. 🤦
=> [ShizaProject] Removed debugging logging

src/Jackett.Common/Definitions/7torrents.yml, src/Jackett.Common/Definitions/brasiltracker.yml, src/Jackett.Common/Definitions/btdigg.yml, src/Jackett.Common/Definitions/btsow.yml, src/Jackett.Common/Definitions/cpabien.yml, src/Jackett.Common/Definitions/cpasbienclone.yml, src/Jackett.Common/Definitions/extratorrent-cd.yml, src/Jackett.Common/Definitions/magnet4you.yml, src/Jackett.Common/Definitions/movcr.yml, src/Jackett.Common/Definitions/mvgroupforum.yml, src/Jackett.Common/Definitions/mvgroupmain.yml, src/Jackett.Common/Definitions/torrent4you.yml, src/Jackett.Common/Definitions/torrentkitty.yml, src/Jackett.Common/Definitions/torrentproject2.yml, src/Jackett.Common/Definitions/zetorrents.yml, src/Jackett.Common/Models/TorznabCatType.generated.cs, src/Jackett.Common/Models/TorznabCatType.tt, src/Jackett.Test/Torznab/TorznabTests.cs
and update any indexers affected
as documented in https://newznab.readthedocs.io/en/latest/misc/api/#predefined-categories
=> Core: correct Other as 8000 and Books as 7000

src/Jackett.Common/Definitions/speedtorrentreloaded.yml
Posting this in lieu of there being a better method
=> speedtorrentreloaded: fix login, skip sessioncheck. resolves #10026

src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs
The category hack is not required after #10031
Related: #10049
=> avistaz: improve category parsing

src/Jackett.Common/Indexers/IPTorrents.cs
* files column removed
* fix date parsing
* include first results
* add uploader into description
=> iptorrents: fix new layout. resolves #10050

src/Jackett.Common/Indexers/IPTorrents.cs
* files column can be disabled by the user
Fix previous PR #10054
=> iptorrents: fix new layout. resolves #10040

src/Jackett.Common/Models/TorznabCapabilitiesCategories.cs
=> core: fix custom categories sorting.

src/Jackett.Common/Indexers/PreToMe.cs
=> pretome: remove category hack and add custom categories

src/Jackett.Common/Definitions/linuxtracker.yml, src/Jackett.Common/Indexers/CardigannIndexer.cs
=> core: add infohash parameter in cardigann definition

src/Jackett.Common/Indexers/AnimeBytes.cs
=> animebytes: code clean up

src/Jackett.Common/Models/ResultPage.cs, src/Jackett.Test/Common/Models/ResultPageTests.cs
* add coverurl
* rename tvdb and tmdb
=> core: add missing torznab attributes. resolves #10118

README.md, src/Jackett.Common/Indexers/Magnetico.cs
https://github.com/boramalper/magnetico
=> magnetico: add new local dht tracker. #2684

src/Jackett.Common/Indexers/SuperBits.cs
Added two categories of TV missing
=> Add TV NO and TV FI categories missing on Superbits

src/Jackett.Common/Indexers/AniDUB.cs
=> Fix unrelated results in AniDUB output

src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/monova.yml, src/Jackett.Common/Definitions/torrent9.yml, src/Jackett.Common/Definitions/torrent9clone.yml
Also added size filter to replace `Ko` with `KB`, etc. in Torrent9 proxies
=> assorted: update unblockninja proxies

README.md, src/Jackett.Common/Definitions/torrentproject.yml
Not sure if this is the original TorrentProject, but its Advanced Search actually works, and it isn't broken by ads, unlike TP2.
Based this off torrentproject2.yml but much of it has been changed, so a second set of eyes would be appreciated.
=> torrentproject: add indexer

src/Jackett.Common/Indexers/TorrentHeaven.cs
Removed not existent column "grabs"
Added new Category TV 4k
=> Reviewed Indexer TorrentHeaven

src/Jackett.Common/Definitions/hdturk.yml
`1 month (30 days = 720 hours) after downloading the presentation, you must stay in the seed for a total of 90 hours or capture a ratio value of 0.8.`
https://hdturk.de/rules.php
=> hdturk: add MST and MR

README.md, src/Jackett.Common/Definitions/cinemamovies.yml
I'm assuming there's no need to change the file name and ID over it
=> cinemamovies: correct name

README.md, src/Jackett.Common/Definitions/btgigs.yml, src/Jackett.Updater/Program.cs
=> Revert "btgigs: removed, dead"

src/Jackett.Common/Definitions/dmhy.yml, src/Jackett.Common/Definitions/u2.yml
Anime is not necessarily TV series
Implemented per https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/nyaasi.yml.
=> dmhy, u2: add movies categories

src/Jackett.Common/Indexers/ShizaProject.cs
Fixes https://github.com/Jackett/Jackett/pull/10166#issuecomment-739589464
Fixes https://github.com/Jackett/Jackett/issues/10160
=> [ShizaProject] Implement auto re-auth on cookie expire

README.md, src/Jackett.Common/Definitions/pttime.yml
Support a new PT site: https://www.pttime.org
=> Add pttime.org support

src/Jackett.Common/Indexers/BaseIndexer.cs, src/Jackett.Common/Indexers/DivxTotal.cs, src/Jackett.Common/Indexers/EliteTracker.cs, src/Jackett.Common/Indexers/MejorTorrent.cs, src/Jackett.Common/Indexers/PixelHD.cs, src/Jackett.Common/Indexers/ShowRSS.cs, src/Jackett.Common/Indexers/TorrentSyndikat.cs, src/Jackett.Common/Indexers/TorrentsCSV.cs, src/Jackett.Common/Indexers/YTS.cs, src/Jackett.Common/Models/IndexerConfig/ConfigurationData.cs
=> assorted c#: fix configuration of several indexers

src/Jackett.Common/Indexers/BaseIndexer.cs, src/Jackett.Common/Services/Interfaces/IProtectionService.cs, src/Jackett.Server/Services/ProtectionService.cs
Legacy code was deprecated on May 30, 2018
e73ae99e388bdc4e1ae349e24fed48ebe59d3140
=> core: remove legacy cryptographic code. #10433

README.md, src/Jackett.Common/Definitions/omgwtftrackr.yml, src/Jackett.Updater/Program.cs
=> Revert "omgwtftrackr: remove, down for 30 days. resolves #8970"

src/Jackett.Common/Definitions/mesevilag.yml
workaround for their new layout hiding the details link behind a javascript drop down panel
=> mesevilag: site change. resolves #10201

src/Jackett.Common/Definitions/hdolimpo.yml
- Add 50% Freeleech tag
- Add Minimum Seed Time
=> [HDOlimpo] Fix Freeleech tags

src/Jackett.Common/Definitions/epizod.yml
Technically, I don't think this is so much a site change as just me finding exceptions upon exceptions. There doesn't seem to be a consistent way of identifying categories, it's a mess, and this is my attempt of making at least some sense of it.
One thing I couldn't figure out was how/if I can translate the multiple `category:` selectors to the `cat:` section, to get vague sizes. I tried adding them all, but that didn't work.
=> epizod: site change

src/Jackett.Common/Indexers/Cinecalidad.cs
_cinecalidad.is_ and _cinecalidad.eu_ are down for more than a week.
=> [Cinecalidad] Update Links to cinecalidad.im

src/Jackett.Common/Jackett.Common.csproj, src/Jackett.Common/Utils/Clients/HttpWebClient.cs, src/Jackett.Common/Utils/Clients/HttpWebClient2.cs
=> core: allow to set user-agent header per indexer

src/Jackett.Common/Definitions/xbytes2.yml
- Add tracker Name to the end of filename
- Improve WebDL detection
- Improve French language detection
- Option to search only Freeleench downloads.
=> xbytes2: Improve Tracker Name, WEBDL Detection, Languages. Freeleench only option

src/Jackett.Common/Definitions/divteam.yml
divteam: Add Multi to languages. DivTeam usually have Original + Spanish at least.
=> divteam: Add Multi to languages

src/Jackett.Common/Definitions/DasUnerwartete.yml
A pin was added to the login page
I did also send an invite just in case.
=> dasunerwartete: fix login handling, add PIN

src/Jackett.Common/Indexers/SubsPlease.cs
=> Fix NRE on empty API response & hardcode size

README.md, src/Jackett.Common/Definitions/montorrent.yml
=> montorrent: add public indexer

src/Jackett.Common/Definitions/theempire.yml, src/Jackett.Common/Definitions/thegeeks.yml, src/Jackett.Common/Definitions/theoccult.yml, src/Jackett.Common/Definitions/theplace.yml, src/Jackett.Common/Definitions/theshow.yml, src/Jackett.Common/Definitions/thevault.yml
big thanks to @adamwinn for all their help testing
=> click trackers: exact title only search. resolves #10887

README.md, src/Jackett.Common/Definitions/hdatmos.yml
=> hdatmos: add new private tracker. resolves #10909

src/Jackett.Common/Definitions/sharewood.yml
Similar as commit 6e59cc4 (Solving Jackett#3553 on yggtorrent.yml)
=> Sharewood : update animation category mapping

src/Jackett.Common/Indexers/AniDUB.cs
Try to make search not return unrelated results and not broke search without punctuation things and e.t.c
#8962
#10931
=> Fix AniDub search

src/Jackett.Common/Definitions/torrentland.yml
Adds new Movies/HD category for music HD concerts
That fix latest errors in log when search in Torrentland
=> [Torrentland] Update categories

src/Jackett.Common/Indexers/NorBits.cs
=> Added UHD categorymapping in NorBits.cs

README.md, src/Jackett.Common/Definitions/acrossthetasman.yml
=> Adding indexer for acrossthetasman.com

src/Jackett.Common/Indexers/YTS.cs
=> Return empty result when YTS api gives malformed response. Resolves #11040

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
They seem to have moved to the new search.
Site currently has issue showing seeds.
=> yggtorrent: change domain www4.*.li, remove beta search. resolves #11069

src/Jackett.Common/Indexers/Hebits.cs
- Fix #11149 
- Replaced HeBits indexer u/n & p/w configuration with cookie header authentication.
=> [Bugfix] HeBits indexer authentication fix

src/Jackett.Common/Indexers/RuTracker.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataRutracker.cs
=> Add config option to RuTracker to move tags to end of release title. Resolves #11109

README.md, src/Jackett.Common/Definitions/casstudiotv.yml, src/Jackett.Updater/Program.cs
Back up
Reverts Jackett/Jackett#11181
=> Revert "casstudiotv: removed, down for 30 days. resolves #3285"

src/Jackett.Common/Definitions/torrentlt.yml
add audiobooks category to torrent.lt
=> add audiobooks category to torrent.lt (torrentlt.yml)

src/Jackett.Common/Definitions/xbytes2.yml
- [WIP] Improve Language parse
- Fix unrelated info
- Fixes for Radarr & Sonarr in Video + Audio detection
- Minor fixes
- [WIP] Replace "Temporada X" for SXX
- [WIP] Replace SXX for "Temporada X" in search
=> [XBytesV2] Improvements

src/Jackett.Common/Indexers/Sharewood.cs
resolve methods with new PR #11104 
add sharewood indexer in C#
=> add sharewood api with C#

src/Jackett.Common/Indexers/CardigannIndexer.cs
#11328 
Tested with 7torrents, anirena, limetorrents, magnet4you, skytorrents.to, zetorrents
Some indexers still fail, but I'm not sure if those errors are related to the #11328 issue.
- FlareResolver not set up correctly.
- Indexer actively refusing connection.
=> Add all configuration item types to GetBaseTemplateVariables

README.md, src/Jackett.Common/aussierules.yml
=> Adding indexer for Aussierul.es

README.md, src/Jackett.Common/Definitions/comicat.yml
=> comicat: add public indexer

README.md, src/Jackett.Common/Definitions/redbits.yml
Resolves https://github.com/Jackett/Jackett/issues/11540
This PR adds support to redbits private tracker. This tracker is based in UNIT3D so I copy and paste (and update) from another cardigan indexer.
I am not sure if I did good because this is my first addition so please review my changes. I can update my PR if you find any problem :)
=> [New Tracker] RedBits

src/Jackett.Common/Definitions/redbits.yml
Sonnar its showing torrent language as English:
=> Add Spanish to avoid Sonarr missmatch

src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/index.html
Add the ability to filter the Add Indexer datatable by language based the value selected by a drop down
=> Add the ability to filter the Add Indexer datatable 

src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/index.html
Add dropdown filters for Categories and Type; cleaned up the on load to clear previous filters when the modal was closed.
=> Add dropdown filters for Categories and Type

src/Jackett.Common/Utils/DateTimeUtil.cs, src/Jackett.Test/Common/Utils/DateTimeUtilTests.cs
- Solve #11219
- Add "relative from" optional parameter to make the unit test of relative date parsing constant in time
=> [enhancement] Date parser handle dates without a year

src/Jackett.Common/Indexers/CardigannIndexer.cs
In the optional fields parsing, it is no exceptional case that the selector finds nothing.
Return null value instead throwing exception increase the performance.
=> [enhancement] Handle optional field without exceptions

src/Jackett.Common/Indexers/NorBits.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataNorbits.cs
Cleaned as requested by @ilike2burnthing.
Removed legacy development mode too.
But can't test as I don't have account.
I assume it works.
=> norbits: cleaning, removed legacy dev tools.

src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/toros.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/yourbittorrent.yml, src/Jackett.Common/Indexers/SubsPlease.cs
Follow up to https://github.com/Jackett/Jackett/pull/11578
=> assorted: add new nocensor proxies

README.md
Small documentation about the filter indexer syntax
=> [enhancement] Filter Indexers documentation

src/Jackett.Common/Indexers/RarBG.cs
Dynamic method this time, lets see how that goes.
=> rarbg: user configurable api url. resolves #11723

src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/index.html
Give the possibility to apply the predefined filters to the main list
=> [feature] Configured Indexers filter UI

src/Jackett.Common/Indexers/Fuzer.cs
https://github.com/Jackett/Jackett/issues/11731
=> [Fuzer] Add new category for TV UHD

src/Jackett.Common/Definitions/sktorrent.yml
added user cp selector, index.php is public hence not checking login correctly
=> Login Check

src/Jackett.Common/Indexers/EraiRaws.cs, src/Jackett.Test/Common/Indexers/EraiRawsTests.cs
=> Implement calculation of details link for erai-raws

README.md, src/Jackett.Common/Definitions/hdcztorrent.yml
My first fully create definiton. based on general template. I didn't find any mention of framework used on the site and the site itself is a mess ... 
for some reason there is some giant <if_is_displayed_2> code with <else_is_displayed_2> inside. no idea how that is supposed to work i don't work with html or javascript ...
every torrent is doubled on the site due the the fact written above but it was not possible to add "after" in rows definiton as the torrent is doubled as whole table not as a row...
Tested downloading and searching looks fine
=> Added HD-CzTorrent definition

src/Jackett.Common/Indexers/ShizaProject.cs
Here's attempt of rewriting ShizaProject indexer to use graphql api of site.
/closes https://github.com/Jackett/Jackett/issues/11712
=> ShizaProject graphql indexer

README.md, src/Jackett.Common/Indexers/OppaiTime.cs
Resolves https://github.com/Jackett/Jackett/issues/1477
=> oppaitime: added indexer

README.md, src/Jackett.Common/Definitions/badasstorrents.yml, src/Jackett.Updater/Program.cs
site no longer uses intermediate `Just a moment...` page
=> badasstorrents: restore indexer. resolves #8709

src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs, src/Jackett.Common/Indexers/DesiTorrents.cs
https://github.com/Jackett/Jackett/commit/e347d38fc031a4ed3bb72063d31a0c3ccc155978#r52162683
=> gazelletracker: add sitelink to poster if needed

src/Jackett.Common/Indexers/TorrentSyndikat.cs
This adds a custom config for the Torrent-Syndikat tracker, providing a help text for the api key and additional filter options to limit search to product-links and specific release types.
Resolves #11934.
=> Torrent-Syndikat: Add filter-options to config

src/Jackett.Common/Indexers/Animedia.cs
During work on https://github.com/Prowlarr/Prowlarr/pull/360 I realised that Jackett Animedia indexer wrong handles multiple releases on same page.
This MR fixes found issues
=> Fix animedia indexer errors

src/Jackett.Common/Indexers/Animedia.cs
Related https://github.com/Jackett/Jackett/pull/12049
Found one more place (torrent download link) with such problem.
=> Fix animedia problems2

src/Jackett.Common/Indexers/DanishBytes.cs
Resolves https://github.com/Jackett/Jackett/issues/12039
This rewrites Danishbytes so that only minimum information is extracted from the JSON. 
This similar problem from happening from https://github.com/Jackett/Jackett/issues/12039
=> danishbytes: rewrote to support minimum info

src/Jackett.Common/Indexers/EraiRaws.cs
=> Fix parsing errors caused by tag name change

src/Jackett.Common/Indexers/RarBG.cs, src/Jackett.Common/Models/TorznabCapabilities.cs
Fixes #12127.
Had to modify TorznabCapabilities.cs to allow overriding from RARBG. If anyone knows a better way to do so, let me know.
=> Add IMDB support for tvsearch in RARBG

README.md, src/Jackett.Common/Indexers/BaseIndexer.cs, src/Jackett.Common/Models/DTO/TorznabRequest.cs, src/Jackett.Common/Models/TorznabQuery.cs, src/Jackett.Common/Services/CacheService.cs
Fixes #11737.
It needs more testing so if anyone can volunteer, please give feedback.
=> Add cache option for individual indexers

src/Jackett.Common/Definitions/kinozal.yml
Fixes #11585.
Would only work after #12258 is merged.
=> [kinozal] Infohash extraction for magnet links

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/badasstorrents.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/elitetorrent-biz.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/gamestorrents.yml, src/Jackett.Common/Definitions/gktorrent.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/ilcorsaronero.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/nyaa-pantsu.yml, src/Jackett.Common/Definitions/oxtorrent.yml, src/Jackett.Common/Definitions/rutor.yml, src/Jackett.Common/Definitions/tokyotosho.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/toros.yml, src/Jackett.Common/Definitions/torrent9clone.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxy.yml, src/Jackett.Common/Definitions/yourbittorrent.yml, src/Jackett.Common/Definitions/zooqle.yml, src/Jackett.Common/Indexers/EraiRaws.cs, src/Jackett.Common/Indexers/MejorTorrent.cs, src/Jackett.Common/Indexers/SubsPlease.cs, src/Jackett.Common/Indexers/YTS.cs
added badasstorrents and elitetorrent-biz
=> assorted: change nocensor proxy domain *.work

src/Jackett.Common/Definitions/mircrew.yml
=> [mircrew] Fix according to pull #12276

src/Jackett.Common/Indexers/CardigannIndexer.cs
=> [Cardigann] Fix empty selector values

src/Jackett.Common/Indexers/CardigannIndexer.cs
Handles #12281.
It's a WIP and I'll constantly push commits. Reviewers whenever you get time, try to test if all indexers are working with the new commits.
=> [Cardigann] Code Quality Enhancement

src/Jackett.Common/Indexers/RuTracker.cs
Fix 4k quality in the naming of TV series for Sonarr parsing
=> 4K quality Fix for Rutracker serials Title

src/Jackett.Common/Indexers/Seals.cs
Same as bB:
https://github.com/Jackett/Jackett/blob/673123d4a12d7f859226cea5a9f18630498b3315/src/Jackett.Common/Indexers/BB.cs#L41
=> seals: remove plain text link

src/Jackett.Common/Indexers/EraiRaws.cs
=> Fix handling of Erai-raws RSS items without links

src/Jackett.Common/Definitions/mteamtp2fa.yml
=> mteamtp2fa: add user agent to fix redirection

README.md, src/Jackett.Common/Definitions/punkshorror.yml
Adding new Hungarian private tracker.
I'm kinda new to GitHub, sorry if I messed something up.
At the time of submitting this the site has open registration, so you can test the indexer.
=> Add new tracker punkshorror

README.md, src/Jackett.Common/Definitions/moviesite.yml
Hungarian general private tracker with open registration at the moment.
Login doesn't work for some reason and I couldn't figure out how to parse the date, but the rest is hopefully ok.
=> Add new indexer moviesite

src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs, src/Jackett.Common/Indexers/Orpheus.cs
Resolves https://github.com/Jackett/Jackett/issues/12525
=> fixed Orpheus downloading issue with token

src/Jackett.Common/Definitions/desitorrents-api.yml, src/Jackett.Common/Definitions/desitorrents.yml
The new minimum seed time is 7 days.
=> update: Minimumseedtime

README.md, src/Jackett.Common/Definitions/ilcorsaroverde.yml
=> ilcorsaroverde: add new indexer. resolves #3189

src/Jackett.Common/Indexers/BrokenStones.cs
=> brokenstones: add 2FA option. resolves #12547

azure-pipelines.yml, src/Jackett.Test/Jackett.Test.csproj
* Update NUnit dependencies
* Remove ARM Unit Tests (they never worked)
=> Update NUnit dependencies and remove ARM Unit Tests

src/Jackett.Common/Definitions/blutopia-api.yml
https://github.com/Prowlarr/Prowlarr/issues/608#issuecomment-970990330
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/3d913291366af79016f8c7e3b21e8d4393b5b36a/app/Http/Controllers/API/TorrentController.php#L354-L360
likely needed for various other converted unit3d as well
=> Fixed: Bad Blutopia API Input Names

src/Jackett.Common/Definitions/aither-api.yml, src/Jackett.Common/Definitions/animeworld-api.yml, src/Jackett.Common/Definitions/brsociety-api.yml, src/Jackett.Common/Definitions/datascene-api.yml, src/Jackett.Common/Definitions/desitorrents-api.yml, src/Jackett.Common/Definitions/reelflix-api.yml, src/Jackett.Common/Definitions/reelflix.yml, src/Jackett.Common/Definitions/shareisland-api.yml, src/Jackett.Common/Definitions/skipthecommercials-api.yml, src/Jackett.Common/Definitions/tellytorrent-api.yml
Follow up to #12574
@garfield69 need you to check brsociety and reelflix please, as I don't have accounts for them. None of us have an account for animeworld, but every other tracker has changed.
=> assorted: unit3d api update

src/Jackett.Common/Indexers/BeyondHDAPI.cs
=> Updated BeyondHDAPI to use smarter search string

README.md, src/Jackett.Common/Definitions/torrentby.yml
=> torrentby: add new belarusian tracker. resolves #12639

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/audiobookbay.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/extratorrent-st.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/oxtorrent.yml, src/Jackett.Common/Definitions/pirateiro.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxy.yml, src/Jackett.Common/Definitions/yts.yml, src/Jackett.Common/Definitions/zooqle.yml, src/Jackett.Common/Indexers/EpubLibre.cs, src/Jackett.Common/Indexers/NewPCT.cs
=>  assorted: change unblockit proxy domain *.tv. resolves #12659

src/Jackett.Common/Indexers/HDTorrents.cs
=> hdtorrents: remove . from keywords. resolves #12654

src/Jackett.Common/Indexers/AlphaRatio.cs
=> alpharatio: re-enable searching by season only. resolves #12693

README.md, src/Jackett.Common/Definitions/bluesbrothers.yml
=> bluesbrothers: add new private tracker. resolves #12633

src/Jackett.Common/Definitions/skipthecommercials-api.yml, src/Jackett.Common/Definitions/skipthecommercials.yml
=> skipthecommercials: remove . from keywords. #12689

src/Jackett.Common/Indexers/BB.cs
=> bb: remove . from keywords. #12689

src/Jackett.Common/Definitions/blutopia-api.yml, src/Jackett.Common/Definitions/blutopia.yml, src/Jackett.Common/Definitions/crazyhd.yml, src/Jackett.Common/Definitions/potuk.yml, src/Jackett.Common/Definitions/uhdbits.yml
=> assorted: remove . from keywords. #12689

src/Jackett.Common/Definitions/noname-club.yml, src/Jackett.Common/Definitions/noname-clubl.yml, src/Jackett.Common/Definitions/rutor.yml
resolves #12710
@garfield69 is there a more elegant or targeted way of doing this?
=> assorted: optionally add russian tag to titles. resolves #12710

README.md, src/Jackett.Common/Definitions/spidertk.yml
=> spidertk: add private french tracker. resolves #12718

src/Jackett.Common/Definitions/pornbay.yml
This is what the settings are actually named on the site so the info should reflect that.
=> pornbay.org; Strings from site

src/Jackett.Common/Definitions/ilcorsaronero.yml
Links and mirrors got fixed so Im restoring their actual servers. ✌️
=> Updating links

src/Jackett.Common/Definitions/piratbit.yml, src/Jackett.Common/Definitions/piratbitl.yml
=> piratbit: change domain pb.wtf & top.*.fun. resolves #4537

src/Jackett.Common/Content/custom.css, src/Jackett.Common/Content/custom_mobile.css, src/Jackett.Common/Content/index.html
Resolves #11748
Simply remove too specific selector for "Show" select element so all selects can have the same style.
Before (Mozilla Firefox 96)
After
=> Make select style applied to all

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/audiobookbay.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/ettv.yml, src/Jackett.Common/Definitions/extratorrent-st.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/oxtorrent.yml, src/Jackett.Common/Definitions/pirateiro.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxy.yml, src/Jackett.Common/Definitions/yts.yml, src/Jackett.Common/Definitions/zooqle.yml, src/Jackett.Common/Indexers/EpubLibre.cs, src/Jackett.Common/Indexers/MejorTorrent.cs, src/Jackett.Common/Indexers/NewPCT.cs
also trim legacy links to 20, keeping old official domains and mirrors rather than unofficial proxies (unless recent)
=> assorted: change unblockit proxy domain *.how

src/Jackett.Server/Controllers/HealthcheckController.cs
=> core: Implement /health endpoint (healthcheck). Resolves #12784

README.md, src/Jackett.Common/Definitions/alleenretail.yml, src/Jackett.Updater/Program.cs
=> alleenretail: restore indexer, site back up. #12557

README.md, src/Jackett.Common/Indexers/TodoTorrents.cs
Caps: TV, Movies, Music
Based on MejorTorrent's .cs
=> Todotorrents: new Spanish indexer

src/Jackett.Common/Definitions/torrentlt.yml
old login method through cookies stoped working. added login through user/password. old one left commented.
=> fixed torrent.lt login

src/Jackett.Common/Definitions/torrentlt.yml
- added user/password to settings
- removed cookie
=> fixed torrent.lt login, added user/password to settings

src/Jackett.Common/Services/UpdateService.cs, src/Jackett.Common/Utils/Clients/HttpWebClient.cs, src/Jackett.Common/Utils/Clients/HttpWebClient2.cs, src/Jackett.Common/Utils/Clients/WebClient.cs
* Update download timeout => 100s => 300 s
=> core: increate httpclient timeout for update download. resolves #12711

src/Jackett.Common/Definitions/hdolimpo-api.yml, src/Jackett.Common/Indexers/CardigannIndexer.cs
=> core: implement category_desc parser for cardigann indexers (fix)

Installer.iss
=> installer: kill active instances of jackett. resolves #12780

README.md, src/Jackett.Common/Indexers/DonTorrent.cs, src/Jackett.Common/Services/IndexerManagerService.cs
=> dontorrent: convert from todotorrents. resolves #6214

src/Jackett.Common/Indexers/IPTorrents.cs
=> iptorrents: add sort setting. resolves #12853

src/Jackett.Common/Definitions/opencd.yml
https://github.com/Prowlarr/Prowlarr/issues/792
=> opencd https => http

Installer.iss
resolves #12864
credit: @klepp0906
=> installer: apply modify permissions for everyone group. resolves #12864

src/Jackett.Common/Indexers/BroadcasTheNet.cs
=> broadcasthenet: remove name and category parameters. resolves #12814

src/Jackett.Common/Definitions/linkomanija.yml
~~Not ready jet!~~
Edit: This can be merged now
=> [Feature] Linkomanija option to search in description

README.md, src/Jackett.Common/Definitions/xbit.yml
=> xbit: add public tracker. resolves #1774

src/Jackett.Common/Models/ResultPage.cs, src/Jackett.Common/Resources/test.xml
=> core: rename comments field to details, pt2 #10092

src/Jackett.Common/Models/ResultPage.cs, src/Jackett.Common/Resources/test.xml
undo me not reading things
8cc85a92539f56497750b9f421e8b80742b898e3
82ebbbc8f29d2ad7106b61342d92d1c6a7437f84
=> revert comments > details commits

src/Jackett.Common/Indexers/DonTorrent.cs
=> Dontorrent: fix tv show download link

src/Jackett.Common/Indexers/LostFilm.cs
=> lostfilm: use referer for new page. resolves #13028

README.md, src/Jackett.Common/Definitions/rudub.yml, src/Jackett.Common/Services/IndexerManagerService.cs
=> baibako: change to rudub. resolves #5673

src/Jackett.Common/Definitions/fenyarnyek-tracker.yml
perhaps add some CI linting to the yml like we've done on the Prowlarr Indexer Repo?
=> fix fenyarnyek-tracker lint

README.md, src/Jackett.Common/Definitions/thenewfun.yml
=> thenewfun: add new private tracker. resolves #13060

README.md, src/Jackett.Common/Definitions/kisssub.yml, src/Jackett.Common/Services/IndexerManagerService.cs, src/Jackett.Updater/Program.cs
=> kisssub: change to miobt. resolves #13125

src/Jackett.Common/Indexers/Anidex.cs, src/Jackett.Common/Jackett.Common.csproj
Required FlareSolverr >= 2.2.4
=> anidex: fix ddos-guard challenge with flaresolverr. closes #1335

src/Jackett.Common/Content/index.html
https://handlebarsjs.com/guide/expressions.html#html-escaping
=> webui: escape form fields. closes #12883

src/Jackett.Common/Content/custom.css, src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/custom_mobile.css, src/Jackett.Common/Content/index.html, src/Jackett.Common/Content/login.html
Visual Studio was playing up for me, so testing it here.
Follow up to https://github.com/Jackett/Jackett/pull/13196
=> webui: include tvdb link in search results

README.md, src/Jackett.Common/Definitions/seedoff.yml
=> seedoff: add new public tracker. resolves #13146

README.md, src/Jackett.Common/Definitions/kufirc.yml
=> kufirc: add new private hungarian 3x tracker. resolves #13191

README.md, src/Jackett.Common/Definitions/dreamtracker.yml
=> dreamtracker: add new private greek tracker. resolves #13206

src/Jackett.Common/Definitions/bitsexy.yml, src/Jackett.Common/Definitions/empornium.yml, src/Jackett.Common/Definitions/empornium2fa.yml, src/Jackett.Common/Definitions/femdomcult.yml, src/Jackett.Common/Definitions/gay-torrents.yml, src/Jackett.Common/Definitions/happyfappy.yml, src/Jackett.Common/Definitions/kinorun.yml, src/Jackett.Common/Definitions/kufirc.yml, src/Jackett.Common/Definitions/lepornoinfo.yml, src/Jackett.Common/Definitions/mteamtp.yml, src/Jackett.Common/Definitions/mypornclub.yml, src/Jackett.Common/Definitions/pornbits.yml, src/Jackett.Common/Definitions/rintor.yml, src/Jackett.Common/Definitions/sukebeinyaasi.yml, src/Jackett.Common/Definitions/x-ite.me.yml, src/Jackett.Common/Definitions/ydypt.yml, src/Jackett.Common/Indexers/ExoticaZ.cs
=> assorted 3x: tidy modes & descriptions. #13191

README.md, src/Jackett.Common/Indexers/BB.cs
=> Revert "bb: removed, dead. resolves #13211"

README.md, src/Jackett.Common/Definitions/knaben.yml
=> knaben: add public meta-search engine. resolves #13258

src/Jackett.Common/Definitions/mteamtp.yml, src/Jackett.Common/Definitions/mteamtp2fa.yml
https://github.com/Jackett/Jackett/issues/13261#issuecomment-1140278143 - workaround for tracker issue
=> mteamtp: fix download selector. #13261

src/Jackett.Common/Definitions/pixelados.yml
Updated language of Indexer to es-ES
Reg replace keywordsfilters to change nomenclature of Season (Sxx) to tracker format (Txx)
=> pixelados: optimize spanish season nomenclature search

src/Jackett.Common/Definitions/blutopia-api.yml
Short and sweet. See title :)
Reference: [UNIT3D API source](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/c9ff27dbe8acf4ddcbe35d6ef62b40eea46df091/app/Http/Controllers/API/TorrentController.php#L109)
=> [Feature] Add infohash field to blutopia-api yaml definition

src/Jackett.Common/Definitions/pixelados.yml
Optimized code for UNIT3D search style with Season and Episode number in Query.
Added conversion of tracker tags that refer to PROPER version.
=> Pixelados: Optimized code for UNIT3D search

src/Jackett.Common/Definitions/pixelados.yml
An example of how will be show:
=> pixelados: Added VOSE or NOT VOSE detection

README.md, src/Jackett.Common/Definitions/oncesearch.yml, src/Jackett.Updater/Program.cs
=> oncesearch: restore. resolves #10539

README.md, src/Jackett.Common/Definitions/tellytorrent-api.yml, src/Jackett.Updater/Program.cs
=> tellytorrent: restore. resolves #5635

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
=> yggtorrent: setting to extend anime compat to 4 digits. resolves #13370

src/Jackett.Common/Content/custom.css, src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/custom_mobile.css, src/Jackett.Common/Content/index.html, src/Jackett.Common/Content/login.html, src/Jackett.Common/Indexers/CardigannIndexer.cs, src/Jackett.Common/Models/ReleaseInfo.cs, src/Jackett.Common/Models/ResultPage.cs
Related to, but kept separate from, https://github.com/Jackett/Jackett/pull/13384
=> cardigann: add trakt support

src/Jackett.Common/Indexers/CardigannIndexer.cs, src/Jackett.Common/Models/DTO/TorznabRequest.cs, src/Jackett.Common/Models/TorznabCapabilities.cs, src/Jackett.Common/Models/TorznabQuery.cs, src/Jackett.Test/Common/Models/TorznabCapabilitiesTests.cs
=> core: enable trakt and douban queries

src/Jackett.Common/Content/custom.css, src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/custom_mobile.css, src/Jackett.Common/Content/index.html, src/Jackett.Common/Content/login.html, src/Jackett.Common/Indexers/CardigannIndexer.cs, src/Jackett.Common/Models/DTO/TorznabRequest.cs, src/Jackett.Common/Models/ReleaseInfo.cs, src/Jackett.Common/Models/ResultPage.cs, src/Jackett.Common/Models/TorznabCapabilities.cs, src/Jackett.Common/Models/TorznabQuery.cs, src/Jackett.Test/Common/Models/TorznabCapabilitiesTests.cs
Follow up to:
https://github.com/Jackett/Jackett/pull/13385
https://github.com/Jackett/Jackett/pull/13387
Includes a couple of fixes for the latter.
=> cardigann: add tvmaze support

README.md, src/Jackett.Common/Definitions/trupornolabs.yml, src/Jackett.Updater/Program.cs
=> Revert "trupornolabs: removed. resolves #9390"

src/Jackett.Common/Definitions/haitang.yml, src/Jackett.Common/Definitions/korsar.yml, src/Jackett.Common/Definitions/oshenpt.yml, src/Jackett.Common/Definitions/putao.yml, src/Jackett.Common/Definitions/pwtorrents.yml, src/Jackett.Common/Definitions/rustorka.yml, src/Jackett.Common/Definitions/uniongang.yml, yamllint.yml
also remove assorted duplicate keys
=> yamllint: enable key-duplicates check

src/Jackett.Common/Indexers/DonTorrent.cs
Solves #13440  and add new download link cdn fixing 404 error while downloading files
=> Dontorrent: fix tv show hd category identify

README.md, src/Jackett.Common/Definitions/hdfans.yml
=> HDFans:add new Private Tracker resolves #13272

README.md, src/Jackett.Common/Definitions/byrbt.yml, src/Jackett.Updater/Program.cs
=> Revert "byrbt: down for 30 days, removed. resolves #12540"

src/Jackett.Common/Definitions/Bittorrentfiles.yml, src/Jackett.Common/Definitions/bithorlo.yml, src/Jackett.Common/Definitions/boxingtorrents.yml, src/Jackett.Common/Definitions/byrbt.yml, src/Jackett.Common/Definitions/diablotorrent.yml, src/Jackett.Common/Definitions/hdcztorrent.yml, src/Jackett.Common/Definitions/insanetracker.yml, src/Jackett.Common/Definitions/itorrent.yml, src/Jackett.Common/Definitions/rapidzona.yml, src/Jackett.Common/Definitions/tmghub.yml, yamllint.yml
plus testing a few additions that we should already be adhering to
=> yamllint: disable comments-indentation

azure-pipelines.yml, src/Jackett.Common/Definitions/0daykiev.yml
=> pipelines: improve yaml schema validation

src/Jackett.Common/Definitions/kinozal.yml, src/Jackett.Common/Indexers/RuTracker.cs
=> kinozal, rutracker: add keywordsfilters. resolves #13496

README.md, src/Jackett.Common/Definitions/fantasticheaven.yml
=> fantasticheaven: tracker update. resolves #13521

src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs, src/Jackett.Common/Indexers/ExoticaZ.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataAvistazTracker.cs
https://github.com/Prowlarr/Prowlarr/issues/1108
=> avistaztracker: add search freeleech only setting

src/Jackett.Common/Indexers/BJShare.cs
=> bjshare: add useragent. resolves #13564

src/Jackett.Common/Definitions/spidertk.yml
Fix : Exception (spidertk): Relogin failed: Parse error
=> Fix : Exception (spidertk): Relogin failed: Parse error

src/Jackett.Common/Indexers/AnimeBytes.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataAnimeBytes.cs
https://github.com/Jackett/Jackett/issues/13631#issuecomment-1270836655
=> AnimeBytes Add option to add a release based on filename

src/Jackett.Common/Indexers/RuTracker.cs
=> rutracker: fix search by season, add search by episode. resolves #13660

src/Jackett.Common/Definitions/lat-team-api.yml
Lat-Team recently updated its categories. The definition file should match what is currently configured in the site.
=> Update Lat-Team categories

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/badasstorrents.yml, src/Jackett.Common/Definitions/bitsearch.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/elitetorrent-biz.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/filelisting.yml, src/Jackett.Common/Definitions/gamestorrents.yml, src/Jackett.Common/Definitions/gktorrent.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/ilcorsaronero.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/nyaasi.yml, src/Jackett.Common/Definitions/rutor.yml, src/Jackett.Common/Definitions/tokyotosho.yml, src/Jackett.Common/Definitions/torlock.yml, src/Jackett.Common/Definitions/torlook.yml, src/Jackett.Common/Definitions/torrent9clone.yml, src/Jackett.Common/Definitions/torrentdownload.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentz2nz.yml, src/Jackett.Common/Definitions/yourbittorrent.yml, src/Jackett.Common/Definitions/yts.yml, src/Jackett.Common/Definitions/zetorrents.yml, src/Jackett.Common/Indexers/EraiRaws.cs, src/Jackett.Common/Indexers/SubsPlease.cs
=> assorted: update nocensor proxy domain *.lol

src/Jackett.Common/Indexers/MejorTorrent.cs
=> mejortorrent: remove non-english alphanumeric characters. resolves #13716

src/Jackett.Common/Content/index.html, src/Jackett.Common/Content/login.html
This change makes sense to me but maybe you'll see reasons not to
=> [RFC] Prevent search engines indexing with meta tag

src/Jackett.Common/Definitions/blutopia-api.yml
- fixes filtering for 100% freeleech torrents
- this should be applied to all core UNIT3D based indexers running v6.5.0 once released.
=> update: blutopia-api.yml

src/Jackett.Common/Definitions/3evils.yml, src/Jackett.Common/Definitions/bitsexy.yml, src/Jackett.Common/Definitions/dimeadozen.yml, src/Jackett.Common/Definitions/eniahd.yml, src/Jackett.Common/Definitions/extremlymtorrents.yml, src/Jackett.Common/Definitions/gay-torrents.yml, src/Jackett.Common/Definitions/hellashut.yml, src/Jackett.Common/Definitions/krazyzone.yml, src/Jackett.Common/Definitions/leech24.yml, src/Jackett.Common/Definitions/mazepa.yml, src/Jackett.Common/Definitions/megapeer.yml, src/Jackett.Common/Definitions/mircrew.yml, src/Jackett.Common/Definitions/moviesite.yml, src/Jackett.Common/Definitions/rintor.yml, src/Jackett.Common/Definitions/sktorrent-org.yml, src/Jackett.Common/Definitions/tekno3d.yml, src/Jackett.Common/Definitions/theleachzone.yml, src/Jackett.Common/Definitions/torrentslocal.yml, src/Jackett.Common/Definitions/wdt.yml
=> asssorted: fix prepend keywordsfilters. resolves #13747

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
https://github.com/Prowlarr/Indexers/pull/211
https://github.com/Prowlarr/Indexers/pull/184
https://github.com/Prowlarr/Indexers/commit/cf5bab7a7dde8fd87a637f561e3d042455af47f3
=> yggtorrent: add keywordsfilters fixes

src/Jackett.Common/Indexers/BroadcasTheNet.cs
=> broadcasthenet: season regex replace. resolves #13786

src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/index.html
https://github.com/FlareSolverr/FlareSolverr/pull/631
=> ui: direct flaresolverr errors to flaresolverr bug issue template

src/Jackett.Common/Definitions/torrentleech.yml
2.1 was not long enough in testing.
=> requestdelay 3.1s resolves #13796

src/Jackett.Common/Definitions/thesceneplace.yml
Workaround for `ReleaseGroup`.
=> thesceneplace: Use filename from download link when possible

src/Jackett.Common/Definitions/cartoonchaos.yml
=> cartoonchaos: fix title

src/Jackett.Common/Definitions/gktorrent.yml, src/Jackett.Common/Definitions/torrent9.yml, src/Jackett.Common/Definitions/torrent911.yml, src/Jackett.Common/Definitions/torrent9clone.yml, src/Jackett.Common/Definitions/zetorrents.yml
https://github.com/Prowlarr/Indexers/pull/295
=> assorted french indexers: enable allowrawsearch

src/Jackett.Common/Services/ConfigurationService.cs
=> core: use programdata for windows cardigann folder. #13860

README.md, src/Jackett.Common/Definitions/xtorrenty.yml
resolves #13864
`showposts=1` shows time but size, seeders, and leechers are broken, e.g.:
> Data Dodania:
5-01-2023, 10:05
Rozmiar:{rozmiar}
Seedów:{seed}
Peerów:{peer}
=> add xTorrenty a Polish semi-private site. resolves #13864

src/Jackett.Common/Indexers/ImmortalSeed.cs
=> immortalseed: fix login detection. resolves #13884

src/Jackett.Common/Indexers/RarBG.cs
I read #13663 and I reviewed all the code related to requestDelay.
requestDelay works as expected in all cases. There is no need to have ugly hacks
=> rarbg: cleanup all sleeps #13663

src/Jackett.Common/Definitions/cathoderaytube.yml, src/Jackett.Common/Definitions/crt2fa.yml
They should be `S01`, `S01-S05`, `S01-S10`
Also fix for `Complete Series` since `Incomplete Series` results in `In`.
=> cathoderaytube: fix seasons naming

README.md, src/Jackett.Common/Definitions/hqmusic.yml
resolves #13896
Used jpopsuki as a base, not sure if anything here can be used for it.
Annoyingly, what is shown on the site and what is returned to Jackett are different, so we're missing actual download links and tags:
<details>
<summary>Site:</summary>
```html
<tr class="torrent">
<td class="center cats_col">
<div title="Pop" class="tooltip cats_music tags_pop"></div>
</td>
<td class="big_info">
<div class="group_image float_left clear">
</div>
<div class="group_info clear">
<span>
[ <a href="torrents.php?action=download&amp;id=265&amp;authkey=REMOVED&amp;torrent_pass=REMOVED" class="tooltip" title="Download">DL</a>
| <a href="reportsv2.php?action=report&amp;id=265" class="tooltip" title="Report">RP</a> ]
</span>
<a href="artist.php?id=154" dir="ltr">Tong Li</a> - <a …
```
=> add hqmusic a Vietnamese private site. resolves #13896

README.md, src/Jackett.Common/Definitions/unleashthecartoons.yml
=> unleashthecartoons: add private site

src/Jackett.Common/Content/index.html
Added title for publish date for tooltip on hover.
=> webui: add align center/right to table results, add title for publish date

azure-pipelines.yml
=> Revert "ci/cd: fix .net sdk to 6.0.403 #13857"

src/Jackett.Common/Indexers/FunFile.cs
=> funfile: refactor parsing and multi-category filtering

src/Jackett.Common/Indexers/NorBits.cs
=> norbits: refactor parsing

src/Jackett.Common/Indexers/PornoLab.cs
=> pornolab: refactor parsing

src/Jackett.Common/Indexers/PreToMe.cs
=> pretome: refactor parsing and login error message

src/Jackett.Common/Definitions/bitsexy.yml
Can someone check if the login works? Someone complained the login doesn't work even if with the correct credentials that in the browser works.
I suspect either the extra input fields or the user-agent.
=> bitsexy: remove unused login inputs

README.md, src/Jackett.Common/Definitions/nicept.yml
=> nicept: add private chinese 3x tracker. resolves #9075

src/Jackett.Common/Indexers/NebulanceAPI.cs
- Use single wildcard in search: Currently `Three - Body` is transformed into `%Three%%%Body%`, with this change it would be `%Three%Body%`
- Improve search by using `"Age": ">0"` to prevent using wildcard in name
- Updated MST according to their rules
- Use `DateTimeStyles.AssumeUniversal` for publish dates
- Added `Files`
=> nebulanceapi: improve search query and release info data

src/Jackett.Common/Indexers/ImmortalSeed.cs, src/Jackett.Common/Indexers/XSpeeds.cs
Also check for `Sitewide Free Torrent`.
=> immortalseed: category filtering and add sorting to skip sticky results

src/Jackett.Common/Models/TorznabQuery.cs
- standardize dashes from this [list](https://www.fileformat.info/info/unicode/category/Pd/list.htm)
- standardize this list of single quotes: [GRAVE ACCENT](https://www.fileformat.info/info/unicode/char/0060/index.htm), [ACUTE ACCENT](https://www.fileformat.info/info/unicode/char/00B4/index.htm), [LEFT SINGLE QUOTATION MARK](https://www.fileformat.info/info/unicode/char/2018/index.htm) & [RIGHT SINGLE QUOTATION MARK](https://www.fileformat.info/info/unicode/char/2019/index.htm)
Useful for queries like `Hey Ho, Let’s Go!` that currently are sanitized as `Hey Ho Lets Go`, instead of `Hey Ho Let's Go`.
More info: https://musicbrainz.org/doc/Style/Miscellaneous
=> standardize dashes/single quotes in search term

src/Jackett.Common/Indexers/IPTorrents.cs
- change search to use their boolean operators and grouping
- tvsearch support for searching by imdbid and season/episode
- clean title for weird unicode chars and any form of `REQUEST`.
=> iptorrents: add support for tvsearch by imdbid

src/Jackett.Common/Indexers/LostFilm.cs
It's not exactly a fix for the issue in #14008 since I can't replicate it, but at least it stops it from getting an exception at parsing.
=> lostfilm: use DateTime.TryParse

src/Jackett.Common/Indexers/RuTracker.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataRutracker.cs
=> rutracker: add option to use magnet links

src/Jackett.Common/Definitions/polishsource.yml
=> polishsource: add requestDelay and fake user-agent to bypass blocking

src/Jackett.Common/Definitions/torrentleech.yml
I wanted to mix imdbid + keywords (season/ep) but it's not supported. :)
=> torrentleech: add exclude scene

README.md, src/Jackett.Common/Indexers/DICMusic.cs
=> dicmusic: restore indexer. resolves #14039

src/Jackett.Common/Definitions/torrentleech.yml
=> torrentleech: add 2fa support

src/Jackett.Common/Definitions/noname-club.yml, src/Jackett.Common/Definitions/noname-clubl.yml
https://github.com/Jackett/Jackett/issues/14038
=> [nnm] Replace RUSSIAN postfix for non-russian cat

src/Jackett.Common/Indexers/RarBG.cs
https://github.com/Jackett/Jackett/pull/14000#issuecomment-1437339463
=> rarbg: set request delay based on query mode

src/Jackett.Common/Definitions/cloudtorrents.yml, src/Jackett.Common/Definitions/polishsource.yml
resolves #14065
More accurate comment. Make only slight change to UA.
=> cloudtorrents & polishsource: change user-agent. resolves #14065

src/Jackett.Common/Definitions/exttorrents.yml
Fix for second page when searching.
=> exttorrents: fix second page url generation

README.md, src/Jackett.Common/Definitions/kamept.yml
=> kamept: add Chinese 3X tracker. resolves #14145

src/Jackett.Common/Indexers/BrokenStones.cs
Updating tracker link for BrokenStones.
=> Update BrokenStones link.

README.md, src/Jackett.Common/Definitions/helltorrents.yml
resolves #14164
Opinion on download selector including paid and unpaid result? Will fail if trying to download, but at least the search/test will be successful. Add comment? Add info note?
=> helltorrents: add semi-private polish tracker. resolves #14164

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
update yggtorrent & yggcookie domain
=> update ygg domains

src/Jackett.Common/Definitions/superbits.yml
same thing as d60ae9f408561031429859b442a7add2db869d1a
no account to test.
=> superbits: fix searching by episode in combo with imdbid

src/Jackett.Common/Indexers/HDTorrents.cs
c&p - https://github.com/Jackett/Jackett/commit/a8083062ad51d5ff6a238471902c673b76f19cd2
Nothing really to test, given there are no freeleech torrents at the moment, but might as well get a second pair of eyes to give it a look.
=> hdtorrents: add freeleech search. #9456

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
Sonarr send date at format yyyy.mm.dd, so we need to index with the correct date format
=> Update to replace French date dd-mm-yyyy to yyyy.mm.dd

src/Jackett.Common/Definitions/sportscult.yml
ignore the login form from the header and improve error selection
=> sportscult: specify the login form and improve error selection

src/Jackett.Common/Definitions/btdigg.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Definitions/thepiratebay.yml
onion.ly and tor2web.to all return 504 - Gateway Time-out no matter the address used
=> assorted: change onion proxies *.tor2web.link

src/Jackett.Common/Definitions/nyaasi.yml
Follow up to https://github.com/Jackett/Jackett/pull/14261 and https://github.com/Prowlarr/Prowlarr/issues/1052.
=> nyaasi: improve season and episode parsing

src/Jackett.Common/Definitions/mvgroupforum.yml, src/Jackett.Common/Definitions/mvgroupmain.yml
They seem to have changed the style of the tracker.
The form selector is different for Jackett than in browser.
Changed test path and removed selector as it was causing a relogin on every search.
=> mvgroup: update login. resolves #14256

README.md, src/Jackett.Common/Definitions/ultrahd.yml
=> ultrahd: add new private Chinese tracker. resolves #14286

README.md, src/Jackett.Common/Definitions/uploads.yml
=> uploads: add private Chinese tracker. resolves #14291

README.md, src/Jackett.Common/Definitions/hdvideo.yml
=> hdvideo: add private Chinese tracker. resolves #14294

src/Jackett.Common/Definitions/learnbits.yml, src/Jackett.Common/Definitions/ztracker.yml
required for https://github.com/Jackett/Jackett/pull/14338
=> learnbits & ztracker: update login inputs

src/Jackett.Common/Definitions/chilebt.yml
per spec lang must be on http://www.lingoes.net/en/translator/langcode.htm
=> Update chilebt.yml - fix invalid language code

README.md, src/Jackett.Common/Definitions/trezzor.yml, src/Jackett.Common/Definitions/trezzorcookie.yml
=> trezzor: update, add separate cookie indexer. resolves #14376

README.md, src/Jackett.Common/Definitions/vstorrent.yml
vstorrent: add public VST site
* Fixes #14385
=> vstorrent: add public VST site. resolves #14385

src/Jackett.Common/Indexers/CardigannIndexer.cs
I know almost nothing about csharp, so please don't ask me to write test for this... I can't
* Fixes #XXXX
=> fix: parse result with template is not rendered

src/Jackett.Common/Definitions/u2.yml
fix custom dlvf & ulvf for U2
* Fixes #14457
* Closes #14460
=> u2: fix custom dlvf & ulvf. resolves #14457

README.md, src/Jackett.Common/Definitions/dimeadozen.yml
=> dimeadozen: type=private. resolves #14475

src/Jackett.Common/Definitions/ultrahd.yml, src/Jackett.Common/Definitions/x-ite.me.yml, src/Jackett.Common/Definitions/zamundanet.yml, src/Jackett.Common/Definitions/zelkaorg.yml
=> assorted: c&p fix. #14537

src/Jackett.Common/Definitions/mvgroupforum.yml, src/Jackett.Common/Definitions/mvgroupmain.yml
=> mvgroup: add login.test.selector. #14537

src/Jackett.Common/Definitions/centraltorrent.yml, src/Jackett.Common/Indexers/BaseIndexer.cs, src/Jackett.Common/Indexers/CardigannIndexer.cs
So if there's a redirect without a domain change, let's follow that redirect.
=> cardigann: follow login redirect if domain doesn't change

README.md, src/Jackett.Common/Definitions/dariustracker.yml, src/Jackett.Updater/Program.cs
=> dariustracker: restore indexer, add freeleech filter. #9768

README.md, src/Jackett.Common/Definitions/le-cinephile.yml
=> le-cinephile: add French private tracker. resolves #14553

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
=> ygg: strip season as site does not support partial matches. resolves #14565

README.md, src/Jackett.Common/Definitions/wukong.yml
=> wukong: add Chinese private tracker. resolves #14595

README.md, src/Jackett.Common/Definitions/hellashut.yml, src/Jackett.Updater/Program.cs
=> hellashut: restore indexer. resolves #13706

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
=> yggtorrent: make strip season optional. resolves #14565

README.md, src/Jackett.Common/Definitions/futuretorrent.yml
=> futuretorrent: add Italian private tracker. resolves #4205

README.md, src/Jackett.Common/Definitions/r3vwtf.yml
=> r3vwtf: update cats and vf selectors, add freeleech search and sort

README.md, src/Jackett.Common/Definitions/ptlsp.yml
=> ptlsp: add private Chinese tracker. resolves #14651

README.md, src/Jackett.Common/Definitions/ptcafe.yml
=> ptcafe: add private Chinese tracker. resolves #14652

src/Jackett.Common/Definitions/ptcafe.yml, src/Jackett.Common/Definitions/ptlsp.yml, src/Jackett.Common/Definitions/redleaves.yml
=> assorted: fix cst tz typo

src/Jackett.Common/Definitions/carpt.yml, src/Jackett.Common/Definitions/hhanclub.yml
=> carpt & hhanclub: remove wrong Chinese name. resolves #14686

src/Jackett.Common/Definitions/theempire.yml, src/Jackett.Common/Definitions/thegeeks.yml, src/Jackett.Common/Definitions/theoccult.yml, src/Jackett.Common/Definitions/theplace.yml, src/Jackett.Common/Definitions/theshow.yml, src/Jackett.Common/Definitions/thevault.yml
by request of TCG staff
* Fixes #XXXX
=> assorted tcg: remove freeleech and exclusive results

README.md, src/Jackett.Common/Indexers/PassThePopcorn.cs
=> PTP: Added back

src/Jackett.Common/Definitions/theempire.yml, src/Jackett.Common/Definitions/thegeeks.yml, src/Jackett.Common/Definitions/theoccult.yml, src/Jackett.Common/Definitions/theplace.yml, src/Jackett.Common/Definitions/theshow.yml, src/Jackett.Common/Definitions/thevault.yml
follow up to #14692 after further discussions with TCG staff
* Fixes #XXXX
=> assorted tcg: restore neutral results

README.md, src/Jackett.Common/Definitions/ildragonero.yml
=> ildragonero: add Italian semi-private tracker. #8148

README.md, src/Jackett.Common/Definitions/ildragonero.yml, src/Jackett.Common/Definitions/mircrew.yml
=> mircrew & ildragonero: update indexers with similarities

src/Jackett.Common/Definitions/ildragonero.yml, src/Jackett.Common/Definitions/mircrew.yml
=> mircrew & ildragonero: always freeleech

README.md, src/Jackett.Common/Indexers/ShizaProject.cs
and capitalise description
* Fixes #XXXX
=> Revert "shizaproject: removed: resolves #13762"

src/Jackett.Common/Indexers/ShizaProject.cs
https://github.com/Jackett/Jackett/pull/14131 & https://github.com/Jackett/Jackett/pull/14147
* Fixes https://github.com/Jackett/Jackett/commit/71fc08c6bc0f9374f49519996fd8473fab2d1bb3
=> shizaproject: update indexer for core Jackett changes 

src/Jackett.Common/Definitions/piratbit.yml, src/Jackett.Common/Definitions/piratbitl.yml
=> piratbit: update search path

README.md, src/Jackett.Common/Definitions/therarbg.yml
=> therarbg: add new public site. resolves #14685

README.md, src/Jackett.Common/Definitions/btarg.yml
=> btarg: add private Argentinian tracker

README.md, src/Jackett.Common/Definitions/uploadcx.yml
=> Add tracker support upload.cx

src/Jackett.Common/Definitions/exitorrent-org.yml
@PrzemekSkw please check this is working for you. Have you changed any layout/style/appearance account settings?
@relains can you confirm that the current indexer isn't working, and that the changes in this PR resolves it?
Provide any changes as needed.
* Fixes #14755
=> exitorrent-org: update layout. resolves #14755

README.md, src/Jackett.Common/Definitions/emmidtracker.yml
=> emmidtracker: add Brazilian private tracker. resolves #14758

README.md, src/Jackett.Common/Definitions/fearnopeer.yml
=> fearnopeer: add new private tracker. resolves #14770

src/Jackett.Common/Definitions/shareisland-api.yml, src/Jackett.Common/Definitions/torrenteros-api.yml, src/Jackett.Common/Definitions/uploadcx.yml
=> assorted unit3d: update 7.0.0 comment

src/Jackett.Common/Definitions/noname-club.yml, src/Jackett.Common/Definitions/noname-clubl.yml
=> noname-club: update cats

README.md, src/Jackett.Common/Definitions/dreamingtree.yml
=> dreamingtree: add semi-private tracker. resolves #14789

README.md, src/Jackett.Common/Definitions/linkomanija.yml
=> linkomanija: update indexer

src/Jackett.Common/Definitions/aither-api.yml, src/Jackett.Common/Definitions/blutopia-api.yml, src/Jackett.Common/Definitions/datascene-api.yml, src/Jackett.Common/Definitions/fearnopeer.yml, src/Jackett.Common/Definitions/ntelogo.yml, src/Jackett.Common/Definitions/onlyencodes-api.yml, src/Jackett.Common/Definitions/shareisland-api.yml, src/Jackett.Common/Definitions/skipthecommercials-api.yml, src/Jackett.Common/Definitions/torrenteros-api.yml, src/Jackett.Common/Definitions/ultra-hd.yml, src/Jackett.Common/Definitions/uploadcx.yml
=> assorted unit3d: update api key info for 7.0.0

src/Jackett.Common/Definitions/lst.yml
Updated category list and required seedtime
=> update: lst.yml

CONTRIBUTING.md
=> fixed typo error in CONTRIBUTING.md

README.md, src/Jackett.Common/Definitions/diablotorrent.yml
=> diablotorrent: update indexer

README.md, src/Jackett.Common/Definitions/beload.yml
=> beload: add Hungarian private tracker. resolves #14804

README.md
there were grammatical mistakes in the readme.md file
=> grammatical mistake in the README.md

README.md, src/Jackett.Common/Definitions/torrenttrader.yml
=> torrenttrader: add new German private tracker. resolves #14811

src/Jackett.Common/Definitions/cpasbienclone.yml, src/Jackett.Common/Definitions/torrent9.yml
=> cpasbienclone & torrent9: simplify French size filters

README.md, src/Jackett.Common/Definitions/biatch.yml
Add French tracker.
Couldn't keep it from removing apostrophes (without replacing them with a space) though... if anybody has an idea... It should either keep them or replace them with a space.
=> BiatchTorrents: Add French public tracker

README.md, src/Jackett.Common/Definitions/postman.yml
=> postman: add public i2p site. resolves #12541

README.md, src/Jackett.Common/Definitions/tvroad.yml, src/Jackett.Updater/Program.cs
=> Revert "tvroad: removed. resolves #12760"

src/Jackett.Common/Definitions/kinozal-magnet.yml, src/Jackett.Common/Definitions/kinozal.yml
=> kinozal: add separate magnet indexer. resolves #14835

src/Jackett.Common/Definitions/newretro.yml, src/Jackett.Common/Definitions/torrentsectorcrew.yml, src/Jackett.Common/Definitions/torrenttrader.yml
=> assorted german: use correct charset

README.md, src/Jackett.Common/Definitions/romanianmetaltorrents.yml
=> romanianmetaltorrents: update indexer

README.md, src/Jackett.Common/Definitions/anitoons.yml
=> anitoons: add Brazilian private tracker. resolves #14846

README.md, src/Jackett.Common/Definitions/enthralled.yml
=> enthralled: add 3X tracker. resolves #14897

src/Jackett.Common/Definitions/discfan.yml, src/Jackett.Common/Definitions/extremebits.yml, src/Jackett.Common/Definitions/linuxtracker.yml, src/Jackett.Common/Definitions/majomparade.yml, src/Jackett.Common/Definitions/onejav.yml, src/Jackett.Common/Definitions/torrentview.yml
=> assorted: fix field names format

src/Jackett.Common/Definitions/freefarm.yml, src/Jackett.Common/Definitions/hdfans.yml, src/Jackett.Common/Definitions/hdmayi.yml, src/Jackett.Common/Definitions/hdvbits.yml, src/Jackett.Common/Definitions/hdvideo.yml, src/Jackett.Common/Definitions/nicept.yml, src/Jackett.Common/Definitions/okpt.yml, src/Jackett.Common/Definitions/panda.yml, src/Jackett.Common/Definitions/ptchina.yml, src/Jackett.Common/Definitions/ptlsp.yml, src/Jackett.Common/Definitions/rousi.yml, src/Jackett.Common/Definitions/zmpt.yml
=> assorted nexusphp: fix description

README.md, src/Jackett.Common/Definitions/dark-shadow.yml, src/Jackett.Updater/Program.cs
plus a few updated cats
* Fixes #XXXX
=> Revert "dark-shadow: gone. removed. resolves #7892"

README.md, src/Jackett.Common/Definitions/kimoji.yml
=> kimoji: add new Chinese private tracker. resolves #14934

README.md, src/Jackett.Common/Definitions/satclubbing.yml
=> satclubbing: change to private

README.md, src/Jackett.Common/Definitions/agsvpt.yml
=> agsvpt: add private Chinese tracker. resolves #14946

README.md, src/Jackett.Common/Definitions/lastdigitalunderground.yml
=> lastdigitalunderground: add new private tracker. resolves #14955

README.md, src/Jackett.Common/Definitions/hd-club.yml
=> hd-club: change to private. #14827

README.md, src/Jackett.Common/Definitions/rptscene-api.yml, src/Jackett.Common/Services/IndexerManagerService.cs, src/Jackett.Updater/Program.cs
=> rptorrents-api: rename to rptscene-api

src/Jackett.Common/Definitions/kinozal-magnet.yml, src/Jackett.Common/Definitions/kinozal.yml
Section 1003 contains cartoons and anime.
Sections 21 and 22 contain cartoons, not anime.
Section 23 contains mostly PC games.
=> kinozal: fix categories mappings

src/Jackett.Common/Indexers/DonTorrent.cs
DonTorrent URL has changed from yokohama to makeup. https://t.me/DonTorrent/199
=> DonTorrent Site Change 30.01.2024

README.md, src/Jackett.Common/Definitions/cinematik.yml
=> cinematik: update to unit3d. resolves #15035

src/Jackett.Common/Definitions/siambit.yml
siambit: new domain
* Fixes #XXXX
=> siambit: new domain

README.md, src/Jackett.Common/Indexers/Wolfmax4K.cs
Add new indexer Wolfmax4K
* Fixes #14511
=> Add new indexer Wolfmax4K

src/Jackett.Common/Definitions/eniahd.yml, src/Jackett.Common/Definitions/marinetracker.yml, src/Jackett.Common/Definitions/newstudiol.yml, src/Jackett.Common/Definitions/torrentslocal.yml
=> assorted: correct freeleech and 50% freeleech search

README.md, src/Jackett.Common/Definitions/tgay.yml
=> tgay: add new Russian private tracker. resolves #14989

README.md, src/Jackett.Common/Definitions/dariustracker.yml, src/Jackett.Updater/Program.cs
=> Revert "dariustracker: removed, down for 30 days. resolves #9768 (#14664)"

src/Jackett.Common/Definitions/torrent911.yml, src/Jackett.Common/Definitions/torrent9clone.yml
=> torrent911 & torrent9clone: fix details link. resolves #15062

src/Jackett.Common/Definitions/gktorrent.yml, src/Jackett.Common/Definitions/torrent911.yml, src/Jackett.Common/Definitions/torrent9clone.yml
=> assorted: fix details regexp

README.md, src/Jackett.Common/Definitions/hdvideo.yml, src/Jackett.Updater/Program.cs
=> Revert "hdvideo: removed, down for 30 days. resolves #14294"

src/Jackett.Common/Content/custom.js, src/Jackett.Common/Content/index.html
Add status update to document.title during and after search in webui
=> [enhancement] [webui] Add status update to document.title during and after search in webui

README.md, src/Jackett.Common/Definitions/ilcorsaronero.yml, src/Jackett.Updater/Program.cs
=> Revert "ilcorsaronero: removed. resolves #986"

README.md, src/Jackett.Common/Definitions/frozenlayer.yml, src/Jackett.Updater/Program.cs
=> Revert: "frozenlayer: removed. resolves #1556"

src/Jackett.Common/Content/custom.css, src/Jackett.Common/Content/custom_mobile.css, src/Jackett.Common/Content/index.html
Add a color-coded status for each tracker utilized in dashboard search
Fixed spacing around commas
* Fixes #15080
=> [webui] [enchantment] Add a color-coded status for each tracker utilized in dashboard search

README.md, src/Jackett.Common/Definitions/lilleskyorg.yml
=> lilleskyorg: add private tracker. resolves #15104

README.md, src/Jackett.Common/Definitions/oldgreektracker.yml
=> oldgreektracker: add Greek private tracker. resolves #15111

src/Jackett.Common/Definitions/3changtrai.yml, src/Jackett.Common/Definitions/agsvpt.yml, src/Jackett.Common/Definitions/animetorrentsro.yml, src/Jackett.Common/Definitions/animeworld-api.yml, src/Jackett.Common/Definitions/brsociety-api.yml, src/Jackett.Common/Definitions/btschool.yml, src/Jackett.Common/Definitions/carpt.yml, src/Jackett.Common/Definitions/cinemamovies.yml, src/Jackett.Common/Definitions/cinematik.yml, src/Jackett.Common/Definitions/coastalcrew.yml, src/Jackett.Common/Definitions/digitalcore.yml, src/Jackett.Common/Definitions/divteam.yml, src/Jackett.Common/Definitions/falkonvisionteam.yml, src/Jackett.Common/Indexers/AnimeTorrents.cs, src/Jackett.Common/Indexers/CinemaZ.cs
Couldn't find anything for Classix or Enthralled.
* Fixes #XXXX
=> assorted A-F: add activity info to config

src/Jackett.Common/Indexers/AnimeTorrents.cs, src/Jackett.Common/Indexers/AvistaZ.cs, src/Jackett.Common/Indexers/CinemaZ.cs, src/Jackett.Common/Indexers/MyAnonamouse.cs, src/Jackett.Common/Indexers/NorBits.cs, src/Jackett.Common/Indexers/SpeedCD.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataAnimeTorrents.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataAvistazTracker.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataMyAnonamouse.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataNorbits.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataSceneTime.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataSpeedAppTracker.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataSpeedCD.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataTVstore.cs
Move config data to bespoke configs. Also moved freeleech in NorBits.
* Fixes #XXXX
=> assorted bespoke C#: move or add activity info to config

src/Jackett.Common/Definitions/3changtrai.yml, src/Jackett.Common/Definitions/agsvpt.yml, src/Jackett.Common/Definitions/btschool.yml, src/Jackett.Common/Definitions/carpt.yml
=> assorted: fix #15120

src/Jackett.Common/Definitions/femdomcult.yml, src/Jackett.Common/Definitions/freefarm.yml, src/Jackett.Common/Definitions/fsm.yml, src/Jackett.Common/Definitions/funkytorrents.yml, src/Jackett.Common/Definitions/generationfree-api.yml, src/Jackett.Common/Definitions/hdarea.yml, src/Jackett.Common/Definitions/hdatmos.yml, src/Jackett.Common/Definitions/hdu.yml, src/Jackett.Common/Definitions/hdvideo.yml, src/Jackett.Common/Definitions/hhanclub.yml, src/Jackett.Common/Definitions/icc2022.yml
Nothing for Fantastiko, HD-Only, HDTurk, or Immortuos.
GimmePeers is paid, so you have an account for as long as you pay.
* Fixes #XXXX
=> assorted F-I: add activity info to config

README.md, src/Jackett.Common/Definitions/ptgtk.yml
=> ptgtk: add Chinese private tracker. resolves #15127

README.md, src/Jackett.Common/Definitions/tormac.yml
Credentials login causes browser instance to logout, so use cookies
* Fixes #15130
=> tormac: add Russian private tracker. resolves #15130

src/Jackett.Common/Definitions/linkomanija.yml, src/Jackett.Common/Definitions/monikadesign-api.yml, src/Jackett.Common/Definitions/nicept.yml, src/Jackett.Common/Definitions/ourbits.yml, src/Jackett.Common/Definitions/polishsource.yml, src/Jackett.Common/Definitions/ptcafe.yml, src/Jackett.Common/Definitions/ptlsp.yml, src/Jackett.Common/Definitions/pttime.yml, src/Jackett.Common/Definitions/r3vwtf.yml, src/Jackett.Common/Definitions/rmhd.yml
Nothing for KIMOJI, Kufiric, LearnFlakes, Making Off, and MOJBLiNK.
Also added MR to MonikaDesign.
* Fixes #XXXX
=> assorted J-R: add activity info to config

src/Jackett.Common/Definitions/soulvoice.yml, src/Jackett.Common/Definitions/superbits.yml, src/Jackett.Common/Definitions/tasmanit.yml, src/Jackett.Common/Definitions/thefallingangels.yml, src/Jackett.Common/Definitions/torrentleech-pl.yml, src/Jackett.Common/Definitions/utopia.yml
Nothing for SatClubbing, SceneRush, SnowPT, TGay, WinterSakura (rules page is blank), x-ite.me, or xTorrenty.
* Fixes #XXXX
=> assorted S-Z: add activity info to config

src/Jackett.Common/Definitions/1ptbar.yml, src/Jackett.Common/Definitions/bithorlo.yml, src/Jackett.Common/Definitions/dark-shadow.yml, src/Jackett.Common/Definitions/gaytorrentru.yml, src/Jackett.Common/Definitions/hawke-uno.yml, src/Jackett.Common/Definitions/hellashut.yml, src/Jackett.Common/Definitions/hqmusic.yml, src/Jackett.Common/Definitions/itatorrents.yml, src/Jackett.Common/Definitions/lastfiles.yml, src/Jackett.Common/Definitions/mdan.yml, src/Jackett.Common/Definitions/mnv.yml, src/Jackett.Common/Definitions/peeratiko.yml, src/Jackett.Common/Definitions/pixelcove2fa.yml, src/Jackett.Common/Definitions/reelflix-api.yml, src/Jackett.Common/Definitions/shareisland-api.yml, src/Jackett.Common/Definitions/siambit.yml, src/Jackett.Common/Definitions/theleachzone.yml, src/Jackett.Common/Definitions/thenewfun.yml, src/Jackett.Common/Definitions/torrenting.yml, src/Jackett.Common/Definitions/trezzor.yml, src/Jackett.Common/Definitions/trezzorcookie.yml, src/Jackett.Common/Definitions/ultrahd.yml, src/Jackett.Common/Definitions/universaltorrents.yml, src/Jackett.Common/Definitions/wdt.yml, src/Jackett.Common/Definitions/xider-torrent.yml, src/Jackett.Common/Definitions/xwtclassics.yml, src/Jackett.Common/Definitions/zamundanet.yml, src/Jackett.Common/Definitions/zelkaorg.yml
=> assorted: add activity info to config

src/Jackett.Common/Indexers/RuTracker.cs
searchString regexp fix to include russian characters ё and Ё
=> rutracker: searchString regexp fix

README.md, src/Jackett.Common/Definitions/crabpt.yml
=> crabpt: add Chinese private tracker. resolves #15140

src/Jackett.Common/Definitions/crabpt.yml, src/Jackett.Common/Definitions/ptgtk.yml
=> ptgkt & crabpt: add doubanid search

README.md, src/Jackett.Common/Definitions/at12project.yml
=> at12project: add private tracker. #15150

README.md, src/Jackett.Common/Definitions/polishtorrent.yml
=> polishtorrent: add Polish private tracker. #15151

README.md, src/Jackett.Common/Definitions/rotorrent.yml
=> rotorrent: add Romanian private tracker. resolves #15175

src/Jackett.Common/Indexers/Wolfmax4K.cs
Wolfmax4k: fix download torrents with password
For example: https://wolfmax4k.com/descargar/serie-en-hd/constelacion/temporada-1/capitulo-01/
=> Wolfmax4k: fix download torrents with password

src/Jackett.Common/Definitions/newstudio.yml, src/Jackett.Common/Definitions/newstudiol.yml
=> Revert "newstudio; CA expired"

README.md, src/Jackett.Common/Definitions/kelu.yml
=> kelu: add Chinese private tracker. resolves #15205

README.md, src/Jackett.Common/Definitions/hdt-lafenice.yml
=> hdt-lafenice: add Italian private tracker. resolves #15206

src/Jackett.Common/Definitions/thepiratebay.yml
Added new/updated links, and removed dead and not working links.
FYI: There is a guide on Github to create your own TPB site.
All Proxy URL: https://proxybay.unblockit.africa/
Setup Guide URL: https://proxybay.unblockit.africa/setup.html
GitHub: https://github.com/piratebayproxy/UnblockedPiratebayClean
=> Cleaned Piratebay

README.md, src/Jackett.Common/Definitions/qingwa.yml
=> qingwa: add chinese name and info fix

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/eztv.yml, src/Jackett.Common/Definitions/kickasstorrents-to.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/thepiratebay.yml, src/Jackett.Common/Definitions/yts.yml
Found various working proxies from https://abcproxy.org/ and added them to the respective ones.
@garfield69 I could not find any file for magnetdl (original sites: https://www.magnetdl.com/ & https://www.magnetdl.org/)), so was unable to add the proxy itself. I can "try" & create a file for magnetdl if you say so?
=> Added various proxy sites

README.md, src/Jackett.Common/Definitions/plusteca.yml
=> plusteca: add Portuguese private tracker. resolves #15246

src/Jackett.Common/Indexers/TorrentDay.cs
TorrentDay: add rawsearch support. Resolves #15255
* Fixes #15255
=> TorrentDay: add rawsearch support. Resolves #15255

.github/workflows/codeql-analysis.yml, .github/workflows/issuebot.yml
Hey! :slightly_smiling_face: 
I want to contribute the following changes to your workflow: 
- Avoid executing  scheduled workflows on forks
- Stop running workflows when there is a newer commit in PR
- Stop running workflows when there is a newer commit in branch
(These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html))
=> Fix potential github action smells

src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
=> Update yggtorrent.yml & yggcookie.yml

src/Jackett.Common/Definitions/animeworld-api.yml
Animeworld has upgraded to unit3d 8.0.0
ilike2burnthing please test and also see if #14776 can be reversed
=> animeworld: -> 8.0.0

README.md, src/Jackett.Common/Definitions/hddolby.yml, src/Jackett.Updater/Program.cs
=> hddolby: restore & update. resolves #6334

src/Jackett.Common/Indexers/DonTorrent.cs
~Add pagination logic to the DonTorrent tracker.~
Now it uses the whole query for searching (not only the longest word), ~and it will iterate over all the available pages with results (while "_Next_" button is available and not disabled).~
~It will take longer for many pages due to the way it is implemented, but it will get all posible results (same as using the original web).~
=> [Feature] Allow multiple words search in DonTorrent tracker

README.md, src/Jackett.Common/Definitions/yggcookie.yml, src/Jackett.Common/Definitions/yggtorrent.yml
=> ygg: name and description fixes, move in readme

src/Directory.Build.props
=> ci/cd: remove revision info from version

nuget.config
=> ci/cd: remove nuget workaround

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/extratorrent-st.yml, src/Jackett.Common/Definitions/glodls.yml, src/Jackett.Common/Definitions/kickasstorrents-to.yml, src/Jackett.Common/Definitions/limetorrents.yml, src/Jackett.Common/Definitions/thepiratebay.yml, src/Jackett.Common/Definitions/therarbg.yml, src/Jackett.Common/Definitions/torrent9.yml, src/Jackett.Common/Definitions/torrent911.yml, src/Jackett.Common/Definitions/torrentdownloads.yml, src/Jackett.Common/Definitions/torrentfunk.yml, src/Jackett.Common/Definitions/torrentgalaxy.yml, src/Jackett.Common/Definitions/yts.yml
remove abcproxy.org
add proxyninja.net
add torrentsbay.org
remove individual cases of broken proxies
* Fixes #XXXX
=> assorted: proxies updates

README.md, src/Jackett.Common/Definitions/yoinked.yml
=> yoinked: add private tracker. resolves #15408

src/Jackett.Common/Indexers/Wolfmax4K.cs
Fix wolfmax4k search
* Fixes #14511
=> wolfmax4k: rebuild search

src/Jackett.Common/Indexers/Wolfmax4K.cs
- improve title cleaning.
- if guid contains episode but no season, fallback to parse "Cap." from title
- support multi episode parse from title's "Cap."
* Fixes #15418
=> wolfmax4k: fix #15418

src/Jackett.Common/Definitions/1337x.yml, src/Jackett.Common/Definitions/demonoid.yml, src/Jackett.Common/Indexers/EpubLibre.cs
=> assorted: update proxies

README.md, src/Jackett.Common/Definitions/homeporntorrents.yml, src/Jackett.Updater/Program.cs
Untested, as I managed to get my IP blocked for a few hours because of a stupid typo, and I'm pretty sure they don't allow VPNs/proxies. Will check in a few hours once the block is lifted.
* Fixes #14522
=> homeporntorrents: restore indexer. resolves #14522

README.md, src/Jackett.Common/Definitions/bluraytracker.yml
=> bluraytracker: add Czech private tracker. resolves #15458

src/Jackett.Common/Definitions/unionfansub.yml
Improve season support for Union Fansub inspired by Nya indexer and add release group (fansub) to title name.
=> Improve season support for UnionFansub

src/DateTimeRoutines/DateTimeRoutines.cs
specifed -> specified
* Fixes #XXXX
=> docs: update DateTimeRoutines.cs

README.md, src/Jackett.Common/Definitions/bitstream.yml
=> Add BitStream.click

src/Jackett.Common/Definitions/thevault.yml
- Added missing categories
- Removed categories that don't exist anymore
- Ordered all the categories to make it easy to spot and review future changes
* Missing torrent categories won't show up in the feed
=> Update thevault.yml categories

src/Jackett.Common/Definitions/thegeeks.yml
- Added missing categories
- Removed categories that don't exist anymore
- Renamed some categories to match 
- Ordered all the categories to make it easy to spot and review future changes
* Missing torrent categories won't show up in the feed
=> Update thegeeks.yml categories

src/Jackett.Common/Indexers/Definitions/RuTracker.cs
For Anime category add query "ТВ | Сезон" and add regex for S01 or Episode N of N or N+N of N+N
* Fixes #15566
=> Add to RuTracker fix for Anime category

src/Jackett.Common/Definitions/exitorrent-org.yml
Fix searching only release with polish language on exitorrent.org tracker.
=> Fix searching only release with polish language on exitorrent.org

README.md, src/Jackett.Common/Definitions/rockethd.yml, src/Jackett.Updater/Program.cs
=> rockethd: restore and update. resolves #15237

src/Jackett.Common/Definitions/torrentgalaxy.yml
=> torrentgalaxy: change to parent_cat search. #15358

src/Jackett.Common/Definitions/enthralled.yml, src/Jackett.Common/Definitions/enthralled2fa.yml
=> enthralled: update row selector

src/Jackett.Common/Definitions/dasunerwartete.yml
Das Unerwartete switched their search, so that the current configuration would only return the latest releases, ignoring keywords. The new search endpoint also supports search for IMDB id which is also implemented in this commit.
The configuration was also tested with Prowlarr, Sonarr and Radarr. Since this is my first contribution to this project, I'm happy for any feedback provided.
n.A.
n.A.
=> dasunerwartete.yml new endpoint and add imdb search

src/Jackett.Common/Indexers/Definitions/CGPeers.cs, src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataGazelleTracker.cs
=> cgpeers: cookie login. resolves #15802

src/Jackett.Common/Definitions/u2.yml
* Fixes https://github.com/Jackett/Jackett/issues/15822
=> u2: fix parse error #15822

src/Jackett.Common/Indexers/Definitions/DonTorrent.cs
DonTorrent URL has changed from football to wiki
t.me/DonTorrent/241
=> DonTorrent Site Change 29.01.2025

README.md, src/Jackett.Common/Definitions/hdbao.yml
This is my second new indexer definition. Thanks to the maintainers'
gracious response to my previous request for education about what to
test, I know much more what I don't know. So this time I had more
questions while writing the definition before submitting a PR and I
captured them in `# TODO: ` comments. Please reply to each of the
questions in each of those comments in your review. As I ingest review
feedback I'll cleanup those comments and force push without them.
For this new definition, I performed all the testing I originally did
for my previour PR plus all the additional testing I learned from the
maintainers on my previous PR. I'll do the same as I incorporate
feedback for this new definition.
This PR includes this commit and the previous which just copies the
example …
=> feat(hdbao): Add new HDBao Chinese private tracker

README.md, src/Jackett.Common/Definitions/leech24.yml, src/Jackett.Updater/Program.cs
=> leech24: restore indexer. #12553

README.md, src/Jackett.Common/Indexers/Definitions/PhoenixProject.cs
Add support for Phoenix Project tracker
=> Add Phoenix Project

README.md, src/Jackett.Common/Definitions/letseed.yml
This is my third new indexer definition but still includes new territory for me:
- My first `download:/before:/path: takethanks.php` indexer
- The only PHP indexer I can remember that embeds the torrent DB IDs into the details
and download URL *paths* as opposed to query parameters
So pay particular attention to those factors when reviewing.
There are also still some `# TODO: ` comments from me to address. One is specific to
this indexer and the others are general indexer definition questions that hadn't
occurred to me before.
* Fixes #15901
=> feat(letseed): Add LetSeed private tracker

README.md, src/Jackett.Common/Definitions/bitgamer.yml
4th new indexer, no technical questions this time, though I'm sure there are still things I don't know that I don't know. The only things I know to ask about are more questions about category edge cases now that I've spent more time with them, I've included them in `TODO: ` comments for review. I think I've done all the testing I did for previous PRs, cumulatively.
* Fixes #15915
=> feat(bitgamer): Add bitGAMER private tracker

src/Jackett.Common/Indexers/Definitions/PhoenixProject.cs
Added MR and MST as mentioned here: https://github.com/Jackett/Jackett/pull/15910#issuecomment-2723441392
=> added MR and MST

README.md, src/Jackett.Common/Definitions/rastastugan-api.yml
=> rastastugan: add new Nordic private tracker. resolves #15924

README.md, src/Jackett.Common/Definitions/bitsearch.yml, src/Jackett.Updater/Program.cs
=> bitsearch: restore indexer, merge solidtorrents. #4751 #12232

src/Jackett.Common/Definitions/postman.yml
[A few sentences describing the overall goals of the pull request's commits.](postman: add test for re-login handling)
* Fixes #12541
=> postman: add test for re-login handling

src/Jackett.Common/Definitions/amigosshare.yml, src/Jackett.Common/Definitions/cpabien.yml, src/Jackett.Common/Definitions/cpasbienclone.yml, src/Jackett.Common/Definitions/nortorrent.yml, src/Jackett.Common/Definitions/oxtorrent-co.yml, src/Jackett.Common/Definitions/oxtorrent-vip.yml, src/Jackett.Common/Definitions/torrent9.yml, src/Jackett.Common/Definitions/zetorrents.yml, src/Jackett.Common/Definitions/zktorrent.yml
=> assorted: fix year regex

src/Jackett.Common/Definitions/acrossthetasman.yml, src/Jackett.Common/Definitions/fenyarnyek-tracker.yml, src/Jackett.Common/Definitions/unionfansub.yml, src/Jackett.Common/Indexers/Definitions/LostFilm.cs
=> assorted: indexer description fixes

README.md, src/Jackett.Common/Definitions/eztvl.yml
=> eztvl: add semi-private indexer for login support. resolves #16108

src/Jackett.Common/Definitions/cinemageddon.yml, src/Jackett.Common/Definitions/hdroute.yml, src/Jackett.Common/Definitions/redstartorrent.yml, src/Jackett.Common/Definitions/sktorrent.yml
=> assorted: add settings block for credentials only

src/Jackett.Common/Definitions/digitalcore-api.yml, src/Jackett.Updater/Program.cs
https://redirect.github.com/autobrr/autobrr/issues/2140
=> digitalcore: switch to API

README.md, src/Jackett.Common/Definitions/sewerpt.yml
=> sewerpt: add chinese private tracker. resolves #16133

src/Jackett.Common/Definitions/spiritofrevolution.yml
add missing category 192 wich is the category for single UHD episodes
=> Fix missing category spiritofrevolution

README.md, src/Jackett.Common/Definitions/postman-api.yml
* #12541
* https://github.com/Prowlarr/Indexers/issues/563
=> postman: add semi-private API indexer #12541

README.md, src/Jackett.Common/Definitions/freejavtorrent.yml
=> freejavtorrent: add 3x public tracker. resolves #16165

src/Jackett.Common/Definitions/arenabg.yml, src/Jackett.Common/Definitions/hellashut-api.yml, src/Jackett.Common/Definitions/hellashut.yml, src/Jackett.Common/Definitions/libranet.yml, src/Jackett.Common/Definitions/mojblink.yml, src/Jackett.Common/Definitions/theempire.yml, src/Jackett.Common/Definitions/theplace.yml, src/Jackett.Common/Definitions/torrent-turk.yml, src/Jackett.Common/Definitions/tribalmixes.yml, src/Jackett.Common/Definitions/x-ite.me.yml, src/Jackett.Common/Definitions/xxxtor.yml
=> assorted: remove old cert exceptions

src/Jackett.Common/Definitions/rockethd.yml
Updates Rocket-HD url and minimum seedtime.
* Fixes #XXXX
=> [Update] Fix Rocket-HD url and minimum seedtime

src/Jackett.Common/Definitions/reelflix-api.yml
Updates ReelFlix inactivity rule and updates minimum ratio. Also bumps the engine tag.
* Fixes #XXXX
=> [UPDATE] ReelFlix minimum ratio, inactivity rule and engine tag

src/Jackett.Common/Definitions/cdfile.yml
1: Keep uploading for a total of 48 hours
* Fixes #XXXX
=> [Update] CD File minimum seedtime and inactivity rule

src/Jackett.Common/Definitions/darkpeers.yml
=> [Update] DarkPeers minimum ratio and inactivity rule

src/Jackett.Common/Definitions/f1gp.yml
Tolerance: 3 Days, If you do not seed for 3 days constantly you will be hit with a Hit & Run
This tracker is for F1, F2, F3, FE, F1 Academy Torrents only, no other motor sport.
* Fixes #XXXX
=> [Update] F1GP minimum seedtime, engine tag, and description

src/Jackett.Common/Definitions/generationfree-api.yml
Translated from French.
* Fixes #XXXX
=> [Update] GenerationFree inactivity rule

src/Jackett.Common/Definitions/lastdigitalunderground.yml
=> [Update] LDU inactivity rule

src/Jackett.Common/Indexers/Definitions/BitHDTV.cs
Updates BitHDTV inactivity rule.
* Fixes #XXXX
=> [Update] BitHDTV inactivity rule

src/Jackett.Common/Definitions/yoinked.yml
=> [Update] Yoinked minimum ratio
